### ISSUE TITLE
新建页面没有反应

### ISSUE THREAD

**Issue by xilej** [Qexo/Qexo#144]
### Qexo 版本

v1.7

### 问题描述

新建页面几分钟了，还没有好。

### 截图

![Screenshot_20220505_211827](https://user-images.githubusercontent.com/75837117/166932201-82bae40a-5b27-407b-b9d5-4192d3fa6293.jpg)

**Comment by am-abudu** [comment]
目测是静态资源没有加载 请尝试刷新，更换网络环境或编辑高级设置中的CDN_PREV项为https://npm.eleme.com/

**Comment by am-abudu** [comment]
时间过长没有应答 如未解决请Reopen
