### ISSUE TITLE
在macos本地搭建qexo服务报错

### ISSUE THREAD

**Issue by fee-studio** [Qexo/Qexo#156]
### Qexo 版本

v1.7.0

### 问题描述

我搭建流程是按wiki中的本地部署中的命令来的，但是在本地并没有搭建成功。
我在macos本地安装的是mongodb数据库，下载qexo release 1.7.0的包解压后，执行
```
pip3 install -r requirements.txt
python3 manage.py makemigrations
python3 manage.py migrate
python3 manage.py runserver
```

1，当用户名&密码都配置后，在登录的时候却不报错，如下：
<img width="364" alt="image" src="https://user-images.githubusercontent.com/3103734/169551391-22403e0f-63a8-4b3f-884f-29d81db45901.png">

2，登录页有如下报错，
<img width="520" alt="image" src="https://user-images.githubusercontent.com/3103734/169551529-aa85134d-0ccd-4794-ada9-4066b98664d3.png">

3，解压后，在首次运行配置时，为什么一定要填github仓库/分支等信息，像我这种使用场景，我的hexo并不是托管在github上的，而是在本地/阿里云服务器上的。我这种场景目前支持吗？

调研了比较多的hexo管理后台，特别喜欢qexo，望支持以上3个问题。多谢

### 截图

请看以上问题描述

**Comment by am-abudu** [comment]
1. 我认为是本地mongodb环境的问题，这个报错的意思是无主键，但理应在0.1版本修复了，可能是本地与官方免费的数据库存在差异，事实上用vercel免费部署速度或许不比本地部署慢，因为涉及到github的api
2. 目前qexo只是支持github 原理为调用github api，你可以尝试使用github action推送至你的服务器

**Comment by fee-studio** [comment]
> 1. 我认为是本地mongodb环境的问题，这个报错的意思是无主键，但理应在0.1版本修复了，可能是本地与官方免费的数据库存在差异，事实上用vercel免费部署速度或许不比本地部署慢，因为涉及到github的api
> 2. 目前qexo只是支持github 原理为调用github api，你可以尝试使用github action推送至你的服务器

**Comment by fee-studio** [comment]
今天尝试了使用vercel部署，在vercel上已经成功，如下图：
<img width="792" alt="image" src="https://user-images.githubusercontent.com/3103734/169635955-8997c9c3-2dae-4f2a-8116-9adf9349ba22.png">
但是，在配置github页面，一直报错，而且不清楚具体的原因，卡在这里了。
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/3103734/169635897-4bbb5c0a-c8bd-480a-97ff-ba7401401b3f.png">

另，还有2点问题反馈：
1，整个接入过程比较不清楚，一方面是自身的原因，没用过vercel等。一方面是您这边的接入教程比较简单，应该只适用于此流程的前端同学。希望接入流程能从新人入手，一步步展开。
2， 目前的的运行环境是基于远程的mongodb、vercel、github等，但目前github在国内并不友好。希望能支持本地部署的解决方案呢。

**Comment by Fgaoxing** [comment]
@fee-studio github仓库是你的博客所在位置，需要集成部署Hexo

**Comment by am-abudu** [comment]
请参考文档自行查错

**Comment by fee-studio** [comment]
> @fee-studio github仓库是你的博客所在位置，需要集成部署Hexo

thanks! got it
