### ISSUE TITLE
Vercel 报错

### ISSUE THREAD

**Issue by jsh-jsh** [Qexo/Qexo#163]
### Qexo 版本

v1.7.0

### 问题描述

未知原因错误

### 截图

![image](https://user-images.githubusercontent.com/68993466/171971533-1beab37f-5acc-4021-a4ad-dd526465cac3.png)

**Comment by jsh-jsh** [comment]
![image](https://user-images.githubusercontent.com/68993466/171971557-c7a891e6-baec-4658-aa1c-f79d71d9d32e.png)
这是 vercel.json 的截图，好像已经有了错误中所说的东西

**Comment by am-abudu** [comment]
请确认，这与我的分支中的vecel.json不一样
