### ISSUE TITLE
[bug]qexo中不显示文章

### ISSUE THREAD

**Issue by xilej** [Qexo/Qexo#165]
### Qexo 版本

v1.7.0

### 问题描述

除了最初的几篇文章，后来的文章全都不在qexo中显示（包括页面），但可以正常写文章，创建页面，就是在qexo中不显示

### 复现链接

https://github.com/xilej/Qexo
https://github.com/xilej/hexo

### 截图

https://nicexl.vercel.app/

**Comment by Fgaoxing** [comment]
你截个图

**Comment by am-abudu** [comment]
在设置中清除缓存并一键配置WEBHOOK解决。

**Comment by Fgaoxing** [comment]
#112

**Comment by xilej** [comment]
> 在设置中清除缓存并一键配置WEBHOOK解决。

给力鸭！！大佬

**Comment by xilej** [comment]
https://github.com/xilej/hexo/blob/main/source/link/index.md，接入友链按照官方配置的没有成功，是咋回事。

**Comment by Fgaoxing** [comment]
你需要到友链页面（Qexo的）添加啊，注意隐藏和显示，这不是Qexo的问题

**Comment by Fgaoxing** [comment]
![image](https://user-images.githubusercontent.com/92655031/172282637-36bb5a40-e867-401c-8e1e-c5871c0eb33b.png)
@xilej

**Comment by xilej** [comment]
@Fgaoxing 这个我当日知道，我是没有引入成功。直接变成代码块了。
https://nicexl.vercel.app/link/

**Comment by Fgaoxing** [comment]
@xilej 
![image](https://user-images.githubusercontent.com/92655031/172287102-59c07b3e-367f-48a7-bf0a-bc18c7fc2e98.png)

**Comment by Fgaoxing** [comment]
你自己加了```

**Comment by Fgaoxing** [comment]
你可以https://github.com/Qexo/Qexo/wiki/%E5%8F%8B%E9%93%BE%E7%AE%A1%E7%90%86#%E5%8F%8B%E9%93%BE%E7%94%B3%E8%AF%B7

**Comment by xilej** [comment]
@Fgaoxing 无语，不知道怎么加上的

**Comment by Fgaoxing** [comment]
编辑器检测到你是从代码框里复制的就会自动加上

**Comment by Fgaoxing** [comment]
你可以https://github.com/Qexo/Qexo/wiki/%E5%8F%8B%E9%93%BE%E7%AE%A1%E7%90%86#%E5%8F%8B%E9%93%BE%E7%94%B3%E8%AF%B7
这是一个友链申请的一个东西，github-cdn可以使用https://cdnn.vercel.app/gh/Fgaoxing/blog-cdn@main/source/js/friends-api.js
