### ISSUE TITLE
图片插入失败

### ISSUE THREAD

**Issue by qystudio0** [Qexo/Qexo#172]
### Qexo 版本

dev

### 问题描述

我终于知道是什么问题了
firefox102上传图片没有插入

### 截图

你觉得我有

**Comment by qystudio0** [comment]
之前问题我知道怎么复现了

**Comment by Fgaoxing** [comment]
@qystudio0

**Comment by am-abudu** [comment]
我将尝试检查并修复，但Firefox可能因此被抛弃

**Comment by qystudio0** [comment]
?！

**Comment by am-abudu** [comment]
经检查是`{time}`的错误，故暂且去除对时间戳重命名的支持5c4f9181fbd8168f947cf9e81ddb8cb1db2a52c6
