### ISSUE TITLE
更新后页面管理出现故障

### ISSUE THREAD

**Issue by NoctuG** [Qexo/Qexo#176]
### Qexo 版本

2.0.0-Pre

### 问题描述

更新成功，发现页面管理部分异常，在高级设置部分尝试自动修复（如下图），问题未解决
![屏幕截图 2022-07-18 135948](https://user-images.githubusercontent.com/49110788/179452680-2e7feb78-9560-46d8-bc3f-57d6b5d7124a.jpg)

### 复现链接

https://hexo-admin-nine.vercel.app/new_page.html

### 截图

![屏幕截图 2022-07-18 135413](https://user-images.githubusercontent.com/49110788/179452423-d54ac33e-7861-4704-8f18-dff38a7df53f.jpg)

**Comment by Fgaoxing** [comment]
请截图高级配置CDN部分

**Comment by am-abudu** [comment]
检查本地网络环境与 [https://unpkg.com/](https://unpkg.com/) 的连通性 或将其修改为 [https//npm.elemecdn.com/](https://npm.elemecdn.com/)

**Comment by NoctuG** [comment]
故障已排除

**Comment by Chgocn** [comment]
更新到了master分支最新版本，遇到同样问题，但修改CDN_PREV为[https//npm.elemecdn.com/](https://npm.elemecdn.com/)并未解决问题。

**Comment by am-abudu** [comment]
> 更新到了master分支最新版本，遇到同样问题，但修改CDN_PREV为[https//npm.elemecdn.com/](https://npm.elemecdn.com/)并未解决问题。

是否可以提供F12报错信息和你的页面模板文件

**Comment by Chgocn** [comment]
登录之后打开首页就显示这样，页面模板文件是哪个呢
![image](https://user-images.githubusercontent.com/10706972/190069420-5b998f16-9570-4e67-a87b-fdf9c1aa8f0f.png)

**Comment by Fgaoxing** [comment]
@Chgocn 试试访问域名+/updata

**Comment by Fgaoxing** [comment]
@am-abudu

**Comment by am-abudu** [comment]
> 登录之后打开首页就显示这样，页面模板文件是哪个呢 ![image](https://user-images.githubusercontent.com/10706972/190069420-5b998f16-9570-4e67-a87b-fdf9c1aa8f0f.png)

/scaffords/page.md

**Comment by Chgocn** [comment]
![image](https://user-images.githubusercontent.com/10706972/190292408-8b1b98f9-ba2c-4fc7-ac29-191b90263c7b.png)
之前可以正常打开，升级master最新版本后就一直打不开了，下图是页面模板文件。
![image](https://user-images.githubusercontent.com/10706972/190292621-d3843f55-9e90-4ffa-8b46-9d5cd22d690e.png)

**Comment by am-abudu** [comment]
是update 并不是updata

**Comment by Chgocn** [comment]
访问 域名/update地址，会被重定向到首页，然后还是提示500错误

**Comment by am-abudu** [comment]
进入设置页面 /settings.html 检查配置是否异常（重点检查服务商配置）

**Comment by Chgocn** [comment]
检查了一下github 服务商的配置信息，也通过https://hexoplusplus.cronfly.workers.dev/?step=start检查了一下token的有效性，都是正常的，今天通过settings页面又重新更新了一下master，删除了一下缓存，再打开首页，控制台报错如下：
![image](https://user-images.githubusercontent.com/10706972/190935346-93591b14-89b4-4718-8908-97e6c97e870a.png)

**Comment by am-abudu** [comment]
建议你重新部署试试，因为我这边没办法复现你的错误 :)

**Comment by Chgocn** [comment]
好吧，感谢大佬

**Comment by Chgocn** [comment]
重新部署+删除mongodb里的数据库，然后重新初始化好了
