### ISSUE TITLE
增加颜色自定义

### ISSUE THREAD

**Issue by Fgaoxing** [Qexo/Qexo#18]
1.增加颜色自定义2.深色模式3.菜单增加自定义按钮（有直接跳转，和嵌在另一侧）

**Comment by am-abudu** [comment]
1. TODO
2. 因为默认主题色为浅色，故不添加
3. 浏览器书签会提供更好的体验

**Comment by Fgaoxing** [comment]
abudu：https://www.oplog.cn/    和你？

**Comment by Fgaoxing** [comment]
不喜可删

**Comment by am-abudu** [comment]
> 不喜可删

黑夜模式短期内不会上线，颜色自定义已在计划中

**Comment by am-abudu** [comment]
一直没有想到一个很棒的解决方案，所以该Feature无限期搁置...

**Comment by Fgaoxing** [comment]
可以建立一个库，作为主题，然后选择主题即可，主题是模板文件

**Comment by am-abudu** [comment]
#137
