### ISSUE TITLE
如何通过Github 配置校验

### ISSUE THREAD

**Issue by tinlly** [Qexo/Qexo#190]
### Qexo 版本

master

### 问题描述

我不知道Hexo需要配置什么参数才可以通过这两项验证
- Github 配置后，进行下一步提示“未检测到主题配置” 图一
- 通过HPP测试卡在”拉取仓库信息..“ 图二

### 复现链接

[这里是我的Hexo 主题仓库](https://github.com/tinlly/tinlly-blog/blob/master/_config.yml)

### 截图

![image](https://s2.loli.net/2022/07/26/RjMfKyShV8qTp1d.png)
![image](https://user-images.githubusercontent.com/28109385/180827625-5f7a8e0d-3f15-4922-83be-79c8dbe5e350.png)

**Comment by am-abudu** [comment]
主题目录删除.git文件重新上传

**Comment by tinlly** [comment]
重新上传了, 可以完美运行
