### ISSUE TITLE
qexo Hexo 配置报错

### ISSUE THREAD

**Issue by XINGMOUREN** [Qexo/Qexo#192]
### Qexo 版本

v1.5.3 master

### 问题描述

填写完毕后显示
检测到Hexo版本: 6.2.0
检测到Hexo配置文件
未检测到主题
未检测到主题配置
检测到主题目录
检测到package.json
检测到source目录
我的主题文件夹中的.git文件夹已经删除

### 截图

![DKJLPR6YQ_}H7SP%17{ZN1U](https://user-images.githubusercontent.com/101644034/181284930-e07ae269-cf7d-4d9b-a897-19df75436cd4.png)

**Comment by am-abudu** [comment]
程序会自动搜索您`_config.yml`中的theme项，这标志着您的配置中不存在theme项

**Comment by XINGMOUREN** [comment]
#主题配置
theme: butterfly
存在啊qwq

**Comment by am-abudu** [comment]
是否可以提供完整的config文件

**Comment by am-abudu** [comment]
或者用 [HPP校验助手](https://hexoplusplus.cronfly.workers.dev/?step=start) 自检配置

**Comment by XINGMOUREN** [comment]
完整的文件
`# Site
title: HappyKing
subtitle: '欢迎光临!'
description: '一个分享生活趣事和各种知识的地方'
keywords: 欢乐小王,博客,信息技术,教程
author: 欢乐小王
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://happyking.top/
root: /
# 链接更短 hexo-abbrlink插件
# permalink: :year/:month/:day/:title/
permalink: p/:abbrlink.html
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - 'README.md'
  - 'computer/**' #指定不渲染的文件夹(注意这里默认是source目录的,还有要带“”)

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 12
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

#主题配置
theme: butterfly

#上传配置
deploy:
- type: git
  repo:
    gitHub: ***************
  # [,branch]为可选项，表示部署的分支
  #2020年10月后github新建仓库默认分支改为main，注意更改
- type: baidu_url_submitter
- type: cjh_bing_url_submitter

#GitHub统计
githubcalendar:
  enable: true
  priority: 3
  enable_page: /
  user: XINGMOUREN
  layout:
    type: id
    name: recent-posts
    index: 0
  githubcalendar_html: '<div class="recent-post-item" style="width:100%;height:auto;padding:10px;"><div id="github_loading" style="width:10%;height:100%;margin:0 auto;display: block"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"  viewBox="0 0 50 50" style="enable-background:new 0 0 50 50" xml:space="preserve"><path fill="#d0d0d0" d="M25.251,6.461c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615V6.461z" transform="rotate(275.098 25 25)"><animateTransform attributeType="xml" attributeName="transform" type="rotate" from="0 25 25" to="360 25 25" dur="0.6s" repeatCount="indefinite"></animateTransform></path></svg></div><div id="github_container"></div></div>'
  pc_minheight: 280px
  mobile_minheight: 0px
  color: "['rgb(145, 145, 145, 0.2)', '#c6ecc1', '#a0e2bb', '#81D8CF', '#70c5d3', '#60a2ce', '#507ac9', '#4356c5', '#423cc4', '#5b3abc', '#7138b6']"
  api: https://python-github-calendar-api.vercel.app/api
  # api: https://python-gitee-calendar-api.vercel.app/api
  calendar_js: https://cdn1.tianli0.top/gh/Zfour/hexo-github-calendar@1.21/hexo_githubcalendar.js
  plus_style: ""

#文章密码
encrypt:
	enable: true

#音乐播放器
aplayer:
  meting: true
  asset_inject: false

#历史上的今天
history_calendar:
  priority: 4
  enable: false
  enable_page: /
  layout:
    type: class
    name: sticky_layout
    index: 0
  temple_html: '<div class="card-widget card-history"><div class="card-content"><div class="item-headline"><i class="fas fa-clock fa-spin"></i><span>那年今日</span></div><div id="history-baidu" style="height: 100px;overflow: hidden"><div class="history_swiper-container" id="history-container" style="width: 100%;height: 100%"><div class="swiper-wrapper" id="history_container_wrapper" style="height:20px"></div></div></div></div>'


#网络引擎搜索
plugins:
  - hexo-algoliasearch

#搜索引擎
algolia:
  appId: "******"
  apiKey: "*******"
  adminApiKey: "********************"
  chunkSize: 5000
  indexName: "hexo_blog"
  fields:
    - content:strip:truncate,0,2005d1ac2afb08f8"
  chunkSize: 5000
  indexName: "hexo_blog"
  fields:
    - content:strip:truncate,0,200
    - tags
    - tags
    - permalink
    - excerpt:strip
    - title
    - categories

#分类插件  
magnet:
  enable: true
  priority: 2
  enable_page: all
  type: tags
  devide: 2
  display:
    - name: butterfly🎨
      display_name: 魔改教程
      icon: 📚
    - name: 游戏🎮
      display_name: 游戏杂谈
      icon: 🎮
    - name: 生活🧤
      display_name: 生活琐事
      icon: 💻
    - name: 编程💻
      display_name: 编程笔记
      icon: 👩‍💻
    - name: 学习📝
      display_name: 学习笔记
      icon: 📒
    - name: 随想🎭
      display_name: 胡思乱想
      icon: 💡
  color_setting:
    text_color: var(--caojunyi)
    text_hover_color: white
    background_color: "var(--kk-card-bg)"
    background_hover_color: "#F44E5A"
  layout:
    type: id
    name: recent-posts
    index: 0
  temple_html: '<div class="recent-post-item" style="width:100%;height: auto"><div id="catalog_magnet">${temple_html_item}</div></div>'
  plus_style: ""
  
#标签外挂
# tag-plugins-plus
# see https://akilar.top/posts/615e2dec/
tag_plugins:
  enable: true # 开关
  priority: 5 #过滤器优先权
  issues: false #issues标签依赖注入开关
  link:
    placeholder: https://pic.rmb.bdstatic.com/bjh/ea65919cea5239e9e8fea47bb814864e.jpeg #link_card标签默认的图标图片
  CDN:
    anima: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/font-awesome-animation.min.css #动画标签anima的依赖
    jquery: https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js #issues标签依赖
    issues: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/issues.js #issues标签依赖
    iconfont: //at.alicdn.com/t/font_3294602_1f1y3b7pyh2.js #参看https://akilar.top/posts/d2ebecef/
    carousel: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/carousel-touch.js
    tag_plugins_css: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/tag_plugins.css

#留言板
envelope_comment:
  enable: true #控制开关
  custom_pic:      
    cover: https://cdn1.tianli0.top/gh/XINGMOUREN/pictures/img/留言板狗狗.jpeg #信笺头部图片
    line: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/line.png #信笺底部图片
    beforeimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/before.png # 信封前半部分
    afterimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/after.png # 信封后半部分
  message: #信笺正文，多行文本，写法如下
    - 有什么想问的？
    - 有什么想说的？
    - 有什么想吐槽的？
    - 哪怕是有什么想吃的，都可以告诉我哦~
  bottom: 欢乐小王为您服务！ #仅支持单行文本
  height: 1200px #1050px，信封划出的高度
  path: #【可选】comments 的路径名称。默认为 comments，生成的页面为 comments/index.html
  front_matter: #【可选】comments页面的 front_matter 配置
    title: 🎸留言板🎸
    comments: true
    aside: false
# 自动生成sitemap
sitemap: 
  path: sitemap.xml
baidusitemap: 
  path: baidusitemap.xml

# 图片懒加载
lazyload:
  enable: false # 是否开启图片懒加载
  onlypost: true # 是否只对文章的图片做懒加载
  loadingImg: /img/loading.gif

#中文链接转拼音
permalink_pinyin:
  enable: false
  separator: '-' # default: '-'

#百度自动提交
baidu_url_submit:
  count: 33               # 提交最新的多少个链接
  host: https://www.happyking.top/    # 在百度站长平台中添加的域名
  token: ******************     # 秘钥
  path: baidu_urls.txt   # 文本文档的地址， 新链接会保存在此文本文档里

#脚页计时器
footer_beautify:
  enable:
    timer: true # 计时器开关
    bdage: false # 徽标开关
  priority: 5 #过滤器优先权
  enable_page: all # 应用页面
  exclude: #屏蔽页面
    # - /posts/
    # - /about/
  layout: # 挂载容器类型
    type: id
    name: footer-wrap
    index: 0
  # 计时器部分配置项
  runtime_js: /js/runtime/runtime.js
  runtime_css: /css/runtime/runtime.css
  # 徽标部分配置项
  swiperpara: 3 #若非0，则开启轮播功能，每行徽标个数
  bdageitem:
    - link: https://hexo.io/ #徽标指向网站链接
      shields: https://img.shields.io/badge/Frame-Hexo-blue?style=flat&logo=hexo #徽标API
      message: 博客框架为Hexo_v5.4.0 #徽标提示语
    - link: https://butterfly.js.org/
      shields: https://img.shields.io/badge/Theme-Butterfly-6513df?style=flat&logo=bitdefender
      message: 主题版本Butterfly_v4.1.0
    - link: https://www.jsdelivr.com/
      shields: https://img.shields.io/badge/CDN-jsDelivr-orange?style=flat&logo=jsDelivr
      message: 本站使用JsDelivr为静态资源提供CDN加速
    - link: https://github.com/
      shields: https://img.shields.io/badge/Source-Github-d021d6?style=flat&logo=GitHub
      message: 本站项目由Github托管
    - link: http://creativecommons.org/licenses/by-nc-sa/4.0/
      shields: https://img.shields.io/badge/Copyright-BY--NC--SA%204.0-d42328?style=flat&logo=Claris
      message: 本站采用知识共享署名-非商业性使用-相同方式共享4.0国际许可协议进行许可
    - link: https://icp.gov.moe/?keyword=20220339
      shields: https://img.shields.io/badge/%E8%90%8CICP%E5%A4%87-20220339-green
      message: 本站已于萌国备案

  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css
  swiper_js: https://unpkg.com/swiper@8.3.0/swiper-bundle.min.js
  swiperbdage_init_js: https://cdn1.tianli0.top/gh/XINGMOUREN/XINGMOUREN/js/biaoti.min.js

#加速加速加速
service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true


#提交
hexo_submit_urls_to_search_engine:
  # 提交最新的 n 个链接
  count: 333
  # 提交修改时间在 n 秒内的链接，单位秒。例如：
  # 有两个文件 a.txt 和 b.txt，分别对应 https://yoursite.com/a.txt 和 https://yoursite.com/b.txt
  # 其更新时间距当前分别为 800s 和 1000s（period 字段设为 900）
  # 则 https://yoursite.com/a.txt 会被提交，https://yoursite.com/b.txt 不会
  period: 900
  # 提交链接的条件，可选值：count | period。不同取值的含义如下：
  # count ：应用上述的 count  配置项
  # period：应用上述的 period 配置项
  submit_condition: count
  # 是否向 Google 提交，可选值：1 | 0（0：否；1：是）
  google: 0
  # 是否向 Bing 提交，可选值：1 | 0（0：否；1：是）
  bing: 1
  # 是否向 Baidu 提交，可选值：1 | 0（0：否；1：是）
  baidu: 1
  # 文本文档的地址，要推送的链接会保存在此文本文档里
  txt_path: submit_urls.txt
  # 在百度站长平台中注册的域名
  baidu_host: https://happyking.top/
  # 百度自动推送 API 的 token（获取方式见插件文档：https://cjh0613.com/20200603HexoSubmitUrlsToSearchEngine.html）
  baidu_token: http://data.zz.baidu.com/urls?site=https://www.happyking.top&token=gYVCUwZ8LJSL0Oe2
  # 在必应站长平台中注册的域名
  bing_host: https://happyking.top/
  # 必应自动推送 API 的 token（获取方式见插件文档：https://cjh0613.com/20200603HexoSubmitUrlsToSearchEngine.html）
  bing_token: e7c52b7eebaa42ab8769cbb267bdacf7
  # 在谷歌站长平台中注册的域名
  google_host: https://yoursite.com/
  # 存放 google key 的 json 文件，放于网站根目录
  google_key_file: google_key.json

#推荐插件
swiper:
  enable: true # 开关
  priority: 1 #过滤器优先权
  enable_page: / # 应用页面
  timemode: updated #date/updated
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  default_descr: 小王还没有写描述哦
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css #swiper css依赖
  swiper_js: https://unpkg.com/swiper@8.3.0/swiper-bundle.min.js #swiper js依赖
  custom_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiperstyle.css # 适配主题样式补丁
  custom_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper_init.js # swiper初始化方法`

**Comment by am-abudu** [comment]
你用HPP校验助手看看，我感觉没什么问题，可能是注释、缩进或者空格？

**Comment by XINGMOUREN** [comment]
hpp一直拉取没反应
![S5~%M()}ZS8P_T{OT}NY_CI](https://user-images.githubusercontent.com/101644034/181289095-90b89595-e8d8-4a0e-ba7e-20c192835831.png)

**Comment by XINGMOUREN** [comment]
hpp助手多次拉取无反应

**Comment by am-abudu** [comment]
如果确信没有问题可以尝试使用最新Dev分支支持的`强制提交`

**Comment by XINGMOUREN** [comment]
目前问题已经解决
解决方法
1.在仓库新建分支，随便上传一个主题的代码
2.完成qexo配置后，覆盖分支原有的代码，上传自己的hexo源代码
3.qexo清除缓存

算是曲线救国了（虽然说现在我也不知道为什么拉取不到我的主题QwQ）

**Comment by MemoryShadow** [comment]
也是同样出现了, 我试试楼主给的办法

**Comment by tihuzhi** [comment]
> 如果确信没有问题可以尝试使用最新Dev分支支持的`强制提交`

使用插件(https://hexo.io/zh-cn/docs/one-command-deployment)推送hexo至Github，博客配置无法提交，提示“未检测到hexo”
![error](https://github.com/Qexo/Qexo/assets/81945135/7f2e6c49-928d-4aec-8e5a-42086a274648)，强制提交则无法正确识别博客及所有文章等，无法使用.
使用git push -u origin main提交至GitHub新分支则vercel报错“Error: Command "npm run build" exited with 126”，且无法指向新分支，旧页面依旧存在且可用，此时Qexo博客配置成功，指向的是一个全新的Hexo博客，且为初始主题，无任何修改痕迹，包括之前的文章
