### ISSUE TITLE
IOS端新建文章不显示编辑框

### ISSUE THREAD

**Issue by Mirakelor** [Qexo/Qexo#193]
### Qexo 版本

v2.0.0

### 问题描述

iOS端浏览器新建文章不显示编辑框

### 截图

![9C1A3EE1-22D4-4099-9954-7C668E5393FA](https://user-images.githubusercontent.com/63326519/181401801-330faddc-02ad-47d7-be73-9235357047cb.png)

**Comment by am-abudu** [comment]
我认为是网络问题，是否有办法看到console报错？

**Comment by Fgaoxing** [comment]
已测试，不存在不适配，网络问题或CDN问题

**Comment by Fgaoxing** [comment]
![image](https://user-images.githubusercontent.com/92655031/181406378-206a4c7d-c764-4129-8523-db105904e9fc.png)

**Comment by qystudio0** [comment]
请检查npm的cdn

**Comment by Fgaoxing** [comment]
@Mirakelor 电脑端可以试用吗

**Comment by Mirakelor** [comment]
> @Mirakelor 电脑端可以使用吗

电脑端可以的

**Comment by Mirakelor** [comment]
> 我认为是网络问题，是否有办法看到console报错？
> 
> 或者尝试在scaffolds里面创建_post.md并编辑

编辑文章有编辑框的
新建文章没有

**Comment by Mirakelor** [comment]
回退到1.7.0没有这个问题

**Comment by Mirakelor** [comment]
![image](https://user-images.githubusercontent.com/63326519/181670946-666a2486-f8c4-469f-8d92-08b10622113b.png)![image](https://user-images.githubusercontent.com/63326519/181670947-a76e4ee8-4ff8-4a9a-87e6-0015d6b4d8c2.png)

**Comment by Fgaoxing** [comment]
检查blog/scaffolds里是否有_post.md

**Comment by Fgaoxing** [comment]
@Mirakelor

**Comment by Mirakelor** [comment]
新建post.md后问题解决

**Comment by Fgaoxing** [comment]
@am-abudu 加个”无效“
