### ISSUE TITLE
500错误

### ISSUE THREAD

**Issue by i-abc** [Qexo/Qexo#206]
### Qexo 版本

v2.0.0

### 问题描述

当我对现有文章进行编辑时，会报如下错误；当我新建文章时，也出现了同一错误：

![Snipaste_2022-08-17_20-44-53](https://user-images.githubusercontent.com/104631897/185137965-dabd60ea-0344-4411-b13a-f11aac1c89a1.png)

![Snipaste_2022-08-17_20-45-02](https://user-images.githubusercontent.com/104631897/185138709-77f627e3-354f-49bf-ac8d-350a0da45146.png)

当我对页面进行编辑时，被红框圈住那个会报如下错误，另外三个正常：

![Snipaste_2022-08-17_20-46-39](https://user-images.githubusercontent.com/104631897/185139558-d89ecd3b-c6c1-40f8-bfe8-4c696ec6b81d.png)

![Snipaste_2022-08-17_20-46-50](https://user-images.githubusercontent.com/104631897/185139695-419a0251-181e-4ba0-9343-8b3887cf0c02.png)

应该可以排除Qexo的部署错误，具体原因下面细说：
这是目前我的配置：

![Snipaste_2022-08-17_20-53-07](https://user-images.githubusercontent.com/104631897/185137706-d9c982af-2496-43ca-80f4-8bffbbe7b961.png)

用的Hexo主题为[hexo-theme-stellar](https://github.com/xaoxuu/hexo-theme-stellar)；如果你要复现的话，可以用[这份源码库](https://github.com/xaoxuu/xaoxuu.github.io)，和我是同一个主题，是本主题作者的源码（我的源码就比较混乱了），同样报500。

然后我选择了我未换主题前的一个仓库，一切正常：

![Snipaste_2022-08-17_21-21-17](https://user-images.githubusercontent.com/104631897/185145355-3415da91-4435-4c87-b51d-5dd3d9efb1c7.png)

另外，其他版本的Qexo我也没尝试，不知道报错不，只试了2.0.0这个。

### 截图

如上

**Comment by am-abudu** [comment]
感谢你的反馈！

对于编辑文章的问题，我刚刚向Dev分支提交了修复，请测试

对于编辑页面的问题，是否可以提供一下完整的`bbtalk/index.md`文件以便确定问题

**Comment by i-abc** [comment]
牛，感谢博主，编辑文章问题解决了。

以下是bbtalk的具体位置：

```
source [106.68 KB]
|___bbtalk [329 B]
|___|___index.md [329 B]
```

bbtalk/index.md的代码：
appId、appKey、serverURLs的部分内容我略去了

![image](https://user-images.githubusercontent.com/104631897/185157953-c4ec72d7-82ad-4f24-9347-46633c0404bb.png)


```
<!-- 存放哔哔的容器 -->
<div id="bbtalk"></div>
<!-- 引用 bbtalk -->
<script src="https://cdn.jsdelivr.net/npm/bbtalk@0.1.5/dist/bbtalk.min.js"></script>
<script>
bbtalk.init({
  appId: "y8xxxxxxxxxxxx",
  appKey: "uaxxxxxxxxxxxxx",
  serverURLs: 'https://xxxxxxxxxxxx'
})
</script>
```

[这是bbtalk的官方文档](https://bb.js.org/quick-start.html#cdn%E5%BC%95%E7%94%A8)

**Comment by am-abudu** [comment]
看起来这个文件没有Front-Matter？我在新的Commit中对当无FrontMatter时返回空值，是否解决了这个问题？

**Comment by i-abc** [comment]
> 看起来这个文件没有Front-Matter？我在新的Commit中对当无FrontMatter时返回空值，是否解决了这个问题？

没，还是报错
```
错误! Error 500
报错信息：'NoneType' object has no attribute 'group'
```

**Comment by am-abudu** [comment]
晕，只改了一半，现在应该没问题了

**Comment by i-abc** [comment]
> 晕，只改了一半，现在应该没问题了

能打开了，但有点奇怪，就像直接加载网页了，这是[网页](https://www.shifeiti.com/bbtalk/)。

![image](https://user-images.githubusercontent.com/104631897/185173635-ddec5741-c340-43d1-9cc1-f11b88acc52d.png)

**Comment by i-abc** [comment]
> 是这样的，因为默认的模式为即时渲染。故不建议使用Qexo直接编辑HTML，容易出现问题

原来如此，谢谢老哥了
Qexo挺好用的
