### ISSUE TITLE
部署完之后，error500

### ISSUE THREAD

**Issue by SuHaiHome** [Qexo/Qexo#211]
### Qexo 版本

v1.5.3

### 问题描述

这是怎么回事

### 复现链接

https://qexo-container.vercel.app/

### 截图

![1661867700205](https://user-images.githubusercontent.com/82497826/187455833-d9e99715-6350-4268-8927-503328a62b94.png)

**Comment by am-abudu** [comment]
我暂时不知道你的操作流程，是否可以简述你的操作流程，或提供PSR录制文件？
![image](https://user-images.githubusercontent.com/51912589/187456760-181bc570-07d2-430a-bdb8-ad9b064c17f9.png)

**Comment by SuHaiHome** [comment]
之前连接github,提示我远程连接失败，我重新生成token填入之后，点击确认之后就卡住了，我刷新之后重新登录就报错了。

**Comment by SuHaiHome** [comment]
我重新建一个新的部署一下试试

**Comment by am-abudu** [comment]
https://qexo-container.vercel.app/advanced.html

尝试访问这个URL，并检查配置

**Comment by am-abudu** [comment]
https://qexo-container.vercel.app/settings.html

或者在这个页面检查“服务商设置”

**Comment by SuHaiHome** [comment]
找到问题所在了，我导入的是已经部署过的Hexo，Qexo找不到配置文件是因为根本没有，谢谢大佬了，现在可以了。
![~VP`8W6$D@MU1JVY _067}2](https://user-images.githubusercontent.com/82497826/187568176-570e752b-fce7-4f5a-aed2-93fd8c5e4fad.png)
![7`K@6(KKRCM 7SCIQJ_@N 8](https://user-images.githubusercontent.com/82497826/187568376-e6640ad6-c56b-4c49-b3bb-70858d59db85.png)

**Comment by SuHaiHome** [comment]
![~VP`8W6$D@MU1JVY _067}2](https://user-images.githubusercontent.com/82497826/187568594-3e266d5d-11f6-4423-b896-79774039b80a.png)

**Comment by am-abudu** [comment]
@SuHaiHome 请注意：需要的是**Hexo自动部署**所在仓库
参考文章：https://crazywong.com/posts/74006f42/
