### ISSUE TITLE
通知错误

### ISSUE THREAD

**Issue by Fgaoxing** [Qexo/Qexo#224]
### Qexo 版本

最新dev

### 问题描述

@由于上个版本对于消息的过度防护：
![image](https://user-images.githubusercontent.com/92655031/192129426-6169bb85-8511-49ba-90af-e18d245db430.png)
解决办法：
对友链的通知在接收的API处直接过滤

### 截图

[](https:)

**Comment by am-abudu** [comment]
请检查现在的情况

**Comment by Fgaoxing** [comment]
@am-abudu OK
