### ISSUE TITLE
填写自定义域名后链接拼接不完整

### ISSUE THREAD

**Issue by Big-Cake-jpg** [Qexo/Qexo#230]
### Qexo 版本

v2.1.3

### 问题描述

我使用 Backblaze B2，并填写了自己的自定义域名。上传图片时，Qexo 只插入了自定义域名，没有插入图片路径，导致图片无法加载

### 复现链接

https://hexo-admin.bigcake.cakemc.top

### 截图

图稍后在评论中补齐，GitHub 又抽风上传不了图片

**Comment by Big-Cake-jpg** [comment]
![image](https://user-images.githubusercontent.com/76810494/193453891-5d422113-c45d-49b3-84fa-6532ac0a45d9.png)
![image](https://user-images.githubusercontent.com/76810494/193453899-bb05e695-462f-4843-8ed9-7405ad485b21.jpeg)

**Comment by am-abudu** [comment]
请参考WIKI，现在自定义域名需要填写完整域名

**Comment by Big-Cake-jpg** [comment]
好吧......我去试试
