### ISSUE TITLE
qexo本地部署编辑文章空白

### ISSUE THREAD

**Issue by chenbin3625** [Qexo/Qexo#234]
### Qexo 版本

v2.1.4

### 问题描述

<img width="1669" alt="图片" src="https://user-images.githubusercontent.com/56670467/201888538-d62719a4-36cc-4fdc-a6ea-c2df3dc4115e.png">
打开文章编辑空白 已经清除缓存 并且不显示编辑器 编辑非空的页面也是空白 不显示编辑器
但是编辑配置文件是正常的
<img width="1657" alt="图片" src="https://user-images.githubusercontent.com/56670467/201888705-435e5b19-431b-4988-8bbc-6aff5a208e71.png">
<img width="1118" alt="图片" src="https://user-images.githubusercontent.com/56670467/201889181-8c430040-7220-452e-b574-1556b6449d4a.png">

### 截图

<img width="1845" alt="图片" src="https://user-images.githubusercontent.com/56670467/201889363-eed088d2-3961-4b20-a21b-43638df132ad.png">

**Comment by am-abudu** [comment]
请检查你的网络环境，是否可以联通unpkg

**Comment by am-abudu** [comment]
请给出F12错误报告

另外，我需要知道的是你本地网络是否可以连通unpkg

**Comment by chenbin3625** [comment]
> 请给出F12错误报告
> 
> 另外，我需要知道的是你本地网络是否可以连通unpkg

![image](https://user-images.githubusercontent.com/56670467/201912420-2787d56f-05d7-40d2-a6c7-b1413f8c5ef8.png)
f12w无报错
本地可以ping通unpkg 并且已使用软路由除中国列表以外代理

**Comment by am-abudu** [comment]
点击右上角的14个错误，截图看看

**Comment by chenbin3625** [comment]
> 点击右上角的14个错误，截图看看

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/56670467/202493667-ab39aa88-48e5-46cd-9d36-63c491346ab6.png">
应该是油猴脚本的错误

**Comment by chenbin3625** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/56670467/202494121-b77310c7-fdfe-493c-9f78-bf08fd82c5a6.png">
似乎是冒号的问题
之前用的hexo-admin自动生成的字段

**Comment by am-abudu** [comment]
初步认为是我的程序问题，是否可以给出一个样本.md文件以便测试？

**Comment by chenbin3625** [comment]
> 初步认为是我的程序问题，是否可以给出一个样本.md文件以便测试？

[http://moresec.u1n1.com/HW%E9%97%AE%E9%A2%98.md](url)

**Comment by chenbin3625** [comment]
还有就是本地的qexo部署点一键更新好像不会自动刷新public目录下的文件。。还是需要手动ssh到服务器删除文件后执行hexo g才能更新

**Comment by am-abudu** [comment]
1. 第一个问题的原因是开头没有三个短横杠，将在下个版本或目前的DEV分支添加逻辑判断

2. 关于第二个问题，Qexo目前的本地文件管理功能只会完成文件修改，并不会自动执行命令，请自行使用程序监听或者在Discussion中提出你的Feature等待后续版本更新

**Comment by chenbin3625** [comment]
> 1. 第一个问题的原因是开头没有三个短横杠，将在下个版本或目前的DEV分支添加逻辑判断
> 2. 关于第二个问题，Qexo目前的本地文件管理功能只会完成文件修改，并不会自动执行命令，请自行使用程序监听或者在Discussion中提出你的Feature等待后续版本更新

好的 感谢大佬
