### ISSUE TITLE
数据库链接错误

### ISSUE THREAD

**Issue by zjhinsist** [Qexo/Qexo#252]
### Qexo 版本

v2.0

### 问题描述

<html>
<body>

pymongo.errors.OperationFailure: bad auth : Authentication failed., full error: {'ok': 0, 'errmsg': 'bad auth : Authentication failed.', 'code': 8000, 'codeName': 'AtlasError'}
--
10:59:15.704 | Error: Command "./migrate.sh" exited with 1

</body>
</html>

### 截图

![image](https://user-images.githubusercontent.com/80077571/204428662-56fd6f5d-6882-43ba-b397-40a5a6695a24.png)

**Comment by am-abudu** [comment]
我还是认为是数据库名、用户名、密码中存在错误，见 #188

**Comment by zjhinsist** [comment]
谢谢，是我粗心了
