### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by Liynw** [Qexo/Qexo#255]
### Qexo 版本

v2.1.0

### 问题描述

vercel 部署成功，但链接点进去显示 `Bad Request (400)`。

### 复现链接

https://admin.liynw.top/

### 截图

![image](https://user-images.githubusercontent.com/85772054/204934828-b99d1ee3-f9ac-45bd-bc5f-10c06876bf8b.png)

**Comment by Fgaoxing** [comment]
@Liynw 你的安全域名是不是没配置好？

**Comment by Liynw** [comment]
> @Liynw 你的安全域名是不是没配置好？

好像是的，我换了域名……

不过换了之后怎么再部署啊

**Comment by Liynw** [comment]
> @Liynw 你的安全域名是不是没配置好？

好了，谢谢

**Comment by beyond24** [comment]
> ### Qexo 版本
> v2.1.0
> 
> ### 问题描述
> vercel 部署成功，但链接点进去显示 `Bad Request (400)`。
> 
> ### 复现链接
> https://admin.liynw.top/
> 
> ### 截图
> ![image](https://user-images.githubusercontent.com/85772054/204934828-b99d1ee3-f9ac-45bd-bc5f-10c06876bf8b.png)

可以请教一下你是如何解决的吗
我自定义域名 admin.mydomain.com 后也出现了400error

**Comment by beyond24** [comment]
> @beyond24 删除你的DOMAINS环境变量 然后重新部署

已解决，感谢！
