### ISSUE TITLE
没显示说说

### ISSUE THREAD

**Issue by ning0818** [Qexo/Qexo#265]
### Qexo 版本

v2.2.0

### 问题描述

我发布了说说，也在index.md填写了官网描述的代码，我已经在那里面发了两篇说说，可是博客的说说界面就是什么都没有

### 复现链接

www.yuanning0818.tk

### 截图

![image](https://user-images.githubusercontent.com/117955401/206322997-cbc08385-717a-44d3-91b0-4edb3e1525fc.png)
![image](https://user-images.githubusercontent.com/117955401/206323050-df5076e1-3b80-4338-9a8a-b4a6a263992e.png)
![image](https://user-images.githubusercontent.com/117955401/206323084-a78b1bac-68b1-41e4-ad4e-ce1ca72fa480.png)

**Comment by am-abudu** [comment]
你引用的是错误的js/css资源，请查询[文档](https://www.oplog.cn/qexo/exts/talks.html)

**Comment by ning0818** [comment]
> 你引用的是错误的js/css资源，请查询[文档](https://www.oplog.cn/qexo/exts/talks.html)

文档里的和我的是一样的呀

**Comment by ning0818** [comment]
> 你引用的是错误的js/css资源，请查询[文档](https://www.oplog.cn/qexo/exts/talks.html)

难不成要把qexo-static@1.5.0/hexo/talks.min.js改成qexo-static@1.5.0/hexo/talks.min.js？

**Comment by Fgaoxing** [comment]
@ning0818 稍等，排查问题中

**Comment by Fgaoxing** [comment]
@ning0818 你在主题配置中把https://cdn.jsdelivr.net/npm替换成了https://unpkg.com/，但是https://unpkg.com/不支持压缩，所以没有talks.min.js，只要把talks.min.js改为talks.js即可，talks.min.css改为talks.css

**Comment by Fgaoxing** [comment]
这不是Qexo的原因，所以这个问题不成立

**Comment by ning0818** [comment]
> @ning0818 你在主题配置中把 https://cdn.jsdelivr.net/npm 替换成了 https://unpkg.com/ ，但是 https://unpkg.com/ 不支持压缩，所以没有talks.min.js，只要把talks.min.js改为talks.js即可，talks.min.css改为talks.css

![image](https://user-images.githubusercontent.com/117955401/206627597-e55997f8-8d72-4a1f-806d-e660dba6403f.png)

**Comment by Fgaoxing** [comment]
是上面的全局替换，这是vls主题的功能，不是Qexo的问题，只需要把css和js文件名上的.min去掉即可

**Comment by Fgaoxing** [comment]
@ning0818 关闭问题

**Comment by ning0818** [comment]
> https://cdn.jsdelivr.net/npm

![image](https://user-images.githubusercontent.com/117955401/206627803-69668f95-562f-485a-a78e-dd20fbbe9df9.png)
zh这样对吗

**Comment by Fgaoxing** [comment]
是的，建议把https://cdn.jsdelivr.net/npm 替换成了https://unpkg.com

**Comment by Fgaoxing** [comment]
@ning0818

**Comment by ning0818** [comment]
> @ning0818

现在的配置是对的，对吗

**Comment by ning0818** [comment]
![](https://user-images.githubusercontent.com/117955401/206627803-69668f95-562f-485a-a78e-dd20fbbe9df9.png)

**Comment by Fgaoxing** [comment]
对



在 2022-12-09 13:04:50，"ygblog" ***@***.***> 写道：

@ning0818

现在的配置是对的，对吗
