### ISSUE TITLE
github图床无法上传图片

### ISSUE THREAD

**Issue by ning0818** [Qexo/Qexo#266]
### Qexo 版本

v2.2.0

### 问题描述

github图床无法上传图片，详细信息见截图

### 复现链接

www.yuanning0818.tk

### 截图

![image](https://user-images.githubusercontent.com/117955401/206323609-36d27281-d961-42ff-b686-1a2a22b47391.png)
![image](https://user-images.githubusercontent.com/117955401/206323722-08173bfc-b903-4830-b5e2-8507c45108cb.png)
![image](https://user-images.githubusercontent.com/117955401/206323904-39c80978-3248-4b62-801d-b081db79882b.png)

**Comment by am-abudu** [comment]
你需要先向github上传一个文件以初始化仓库

**Comment by Fgaoxing** [comment]
@ning0818 关闭问题

**Comment by ning0818** [comment]
> @ning0818 关闭问题

还没解决呢，为什么关闭

**Comment by Fgaoxing** [comment]
abudu说的很明白，有git上传一个文件到仓库，然后再操作



在 2022-12-09 13:30:45，"ygblog" ***@***.***> 写道：

@ning0818 关闭问题

还没解决呢，为什么关闭
