### ISSUE TITLE
config.html页面超时

### ISSUE THREAD

**Issue by jer2008** [Qexo/Qexo#270]
### Qexo 版本

v2.2.1

### 问题描述

```log
[GET] /configs.html
14:58:34:41
获取路径成功
获取路径themes成功
获取路径themes/butterfly成功
获取路径source成功
获取路径source/TIY成功
获取路径source/_data成功
获取路径source/_posts成功
获取路径source/about成功
获取路径source/air-conditioner成功
获取路径source/categories成功
获取路径source/charts成功
获取路径source/comments成功
获取路径source/fcircle成功
获取路径source/html成功
获取路径source/img成功
获取路径source/js成功
获取路径source/link成功
2022-12-23T06:58:44.449Z 6c74e9c3-5962-4da5-bc9e-7adf3b18e129 Task timed out after 10.01 seconds
```

### 截图

![image](https://user-images.githubusercontent.com/117557416/209288226-3c6cb73a-718b-41f4-b120-70f667360336.png)

**Comment by am-abudu** [comment]
啊哈 这个不是404 而是超过了Vercel允许的时间

是否可以简单说明一下你的环境

数据库位置/使用的是Github还是Gitlab/Vercel函数位置

如果不清楚的画，请告诉我是默认的

**Comment by jer2008** [comment]
默认的

**Comment by am-abudu** [comment]
好的，你的问题在于数据库的位置。请你依文档所言重新创建正确位置的数据库AWS / N. Virginia (us-east-1)

**Comment by jer2008** [comment]
![image](https://user-images.githubusercontent.com/117557416/209433398-b450260b-0eec-4844-adad-b20e0b17a510.png)
还是不行。

**Comment by jer2008** [comment]
v2.2.0时还正常，更新后就不行了。

**Comment by am-abudu** [comment]
v2.2.1更新并没有动到这部分的内容，这方面原因可以排除

**Comment by am-abudu** [comment]
可能是你的目录过于复杂，导致获取的时间超过了vercel允许的时间。我认为你最好需要本地部署了。。

**Comment by am-abudu** [comment]
确认一下，你是用Github以存储Hexo源码吗，还是说Gitlab

**Comment by jer2008** [comment]
Github

**Comment by jer2008** [comment]
没事了，又正常了，可能是网不好或者vercel出了一些问题，谢谢您的答复。
可能影响的修改，期间在vercel中将Project Settings->Function Region->改为San Francisco, USA (West) - sfo1。

**Comment by am-abudu** [comment]
这个经过测试应该是Washington,D.C., USA (East)- iad1速度最佳

**Comment by am-abudu** [comment]
在最新的Dev分支中，我优化了这一块的逻辑，可以测试一下是否正常了
