### ISSUE TITLE
按照官网程序设置完说说后，一直显示说说加载中，后台已经有数据了

### ISSUE THREAD

**Issue by hxer520** [Qexo/Qexo#272]
### Qexo 版本

2.3.0

### 问题描述

如题

### 复现链接

https://hexo-qexo-phi.vercel.app/talks/

### 截图

![image](https://user-images.githubusercontent.com/12802662/210040897-d0bdb476-2dad-48cb-a06c-c0555dc5a4a8.png)
![image](https://user-images.githubusercontent.com/12802662/210040925-70f51f93-12be-4a56-ba3b-e16fbe4d3e9c.png)
![image](https://user-images.githubusercontent.com/12802662/210040945-8fb03875-ee44-4715-8707-8c3f8b59c818.png)

**Comment by hxer520** [comment]
应该是js的问题，更换其他的源，可正常使用

**Comment by am-abudu** [comment]
既然已经解决，我将关闭本Issue
