### ISSUE TITLE
Github连接超时

### ISSUE THREAD

**Issue by XINGMOUREN** [Qexo/Qexo#285]
### Qexo 版本

v2.4.2

### 问题描述

打开“页面"选项时会超时,图片如下
![image](https://user-images.githubusercontent.com/101644034/211149887-f42610d8-3ee8-45c1-91d4-549c3c5680a9.png)
1.我的source目录文件结构并不复杂
2.在之前的版本可以顺利打开
3.数据库都是默认的
4.vercel后台报错显示连接超时
![image](https://user-images.githubusercontent.com/101644034/211149949-dd690cb5-7156-4deb-a403-c250796ef595.png)

### 截图

![image](https://user-images.githubusercontent.com/101644034/211149887-f42610d8-3ee8-45c1-91d4-549c3c5680a9.png)
![image](https://user-images.githubusercontent.com/101644034/211149949-dd690cb5-7156-4deb-a403-c250796ef595.png)

**Comment by am-abudu** [comment]
最近出现了很多类似的情况，我怀疑是Github的网络连接速度出现问题。对于这个问题，我在最新的Dev分支做出了改进，你可以尝试**更新Dev**后查看问题是否存在。

但这依然不能保证能够不超时，现在有网友称将**Vercel无服务器函数以及你的数据库位置**切换到 日本/韩国 之后有显著改善，你可以进行尝试。

**Comment by XINGMOUREN** [comment]
vercel无函数服务器已经更改到香港,数据库未更改,并且简化了source目录的文件夹,还是一样的问题
看来就是github连接的问题

**Comment by Fgaoxing** [comment]
@XINGMOUREN 你可以使用其他版本，会快一些

**Comment by XINGMOUREN** [comment]
尝试修改mongodb数据库地址,但是提示要先暂停数据库,请问如何暂停(真心不会)

**Comment by am-abudu** [comment]
首先你需要备份好你的资料，如友链说说，可以通过设置页面的迁移功能备份（如果有）

然后打开MongoDB控制台，进行如图操作即可
![b5c768841d1bce9b505f32166d4be817.png](https://img.gejiba.com/images/b5c768841d1bce9b505f32166d4be817.png)

**Comment by XINGMOUREN** [comment]
这是直接销毁数据库了吧,这么直接的嘛

**Comment by am-abudu** [comment]
是的，或者请你重新创建一个MongoDB账号

**Comment by XINGMOUREN** [comment]
好的,接下来去试试

**Comment by XINGMOUREN** [comment]
我把vercel重新部署了一遍,提示
Error: Command "./migrate.sh" exited with 1
请问如何解决
环境变量已经填写好

**Comment by am-abudu** [comment]
这部分日志没有任何作用，请扩大所给的日志范围

**Comment by XINGMOUREN** [comment]
数据库切换至了香港,可以成功读取页面配置了
补充:新版本的wiki文档vercel部署中环境变量没有写
[".vercel.app", "127.0.0.1", ".yoursite.com"]

**Comment by am-abudu** [comment]
那就是说美国Vercel和Github的连接质量不佳导致了这个问题

**Comment by XINGMOUREN** [comment]
嗯,但是香港的mongodb数据库加载也是需要消耗一大段时间
我现在是数据库和vercel都设置的香港

**Comment by am-abudu** [comment]
Vercel和数据库的区域必须一致或者临近

**Comment by XINGMOUREN** [comment]
问题解决,关闭了
