### ISSUE TITLE
侧边栏样式错误

### ISSUE THREAD

**Issue by momo54181** [Qexo/Qexo#287]
### Qexo 版本

v2.4.3

### 问题描述

进入Qexo有很大概率会出现样式错误.

### 截图

![屏幕截图 2023-01-09 102416](https://user-images.githubusercontent.com/79344479/211234427-5a0de97b-f2a3-46e2-87d2-0cd1e28dc270.jpg)

**Comment by momo54181** [comment]
需要刷新好几次才会正常

**Comment by Fgaoxing** [comment]
这个问题，其实在就存在，尤其是改变窗口大小之后，你可以再次刷新即可

**Comment by momo54181** [comment]
一旦全屏就是这，窗口小点侧边栏就自动没了，全屏就回来了.

**Comment by am-abudu** [comment]
请提供屏幕比例

**Comment by momo54181** [comment]
1920*1080
貌似是16：9

**Comment by am-abudu** [comment]
我再测试后未出现错误
![3d16c597beb835d0187adf10fa04788c.png](https://img.gejiba.com/images/3d16c597beb835d0187adf10fa04788c.png)

**Comment by momo54181** [comment]
我用linux的Edge访问也没有问题

**Comment by Fgaoxing** [comment]
@am-abudu 
![image](https://user-images.githubusercontent.com/92655031/211455368-4b9e7f1e-5441-40c5-95ec-3206de051eb1.png)

**Comment by Fgaoxing** [comment]
@am-abudu 解决办法：监听窗口大小变化，然后调整body的class名称，如果比阈值小，就自动添加隐藏的class

**Comment by Fgaoxing** [comment]
同时增加按钮的监听事件

**Comment by am-abudu** [comment]
我实在没有遇到，不知道复现方法的话也不好解决

**Comment by Fgaoxing** [comment]
@am-abudu 额，有没有中可能，他没有dom监听，我怎么按

**Comment by am-abudu** [comment]
我这里是没有问题的，你是否可以给出动图描述？
![](https://img.gejiba.com/images/8a020723ec5d389fa63cd6f9a77adfb2.gif)

**Comment by Fgaoxing** [comment]
@am-abudu 没办法

**Comment by Fgaoxing** [comment]
@am-abudu 我把视频发给你QQ上！

**Comment by am-abudu** [comment]
请查看Dev分支是否问题解决！

**Comment by momo54181** [comment]
我还没更新Dev就好了

**Comment by momo54181** [comment]
问题解决

**Comment by Ezgx** [comment]
遇到了同样的问题，无法解决，使用的最新版
