### ISSUE TITLE
Github删除页面报错

### ISSUE THREAD

**Issue by Fgaoxing** [Qexo/Qexo#289]
### Qexo 版本

latest-PG版本

### 问题描述

删除页面时![image](https://user-images.githubusercontent.com/92655031/211244418-d613f79a-9dcc-4a7c-8c39-0f7bd927ac04.png)
就这个报错，还有pv迁移的时候
import_pv错误: DataError('value too long for type character varying(200)\n')

### 截图

上面

**Comment by Fgaoxing** [comment]
@am-abudu

**Comment by Fgaoxing** [comment]
![image](https://user-images.githubusercontent.com/92655031/211246161-83b2e34f-351e-40a9-948b-316c3d24e99b.png)

**Comment by Fgaoxing** [comment]
GithubException(422, {'message': 'path cannot start with a slash', 'errors': [{'resource': 'Commit', 'field': 'path', 'code': 'invalid'}], 'documentation_url': 'https://docs.github.com/rest/reference/repos#create-or-update-file-contents'}, {'server': 'GitHub.com', 'date': 'Mon, 09 Jan 2023 05:33:50 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '207', 'x-oauth-scopes': 'admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, delete:packages, delete_repo, gist, notifications, repo, user, workflow, write:discussion, write:packages', 'x-accepted-oauth-scopes': '', 'x-github-media-type': 'github.v3; format=json', 'x-github-api-version-selected': '2022-11-28', 'x-ratelimit-limit': '5000', 'x-ratelimit-remaining': '4957', 'x-ratelimit-reset': '1673243877', 'x-ratelimit-used': '43', 'x-ratelimit-resource': 'core', 'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset', 'access-control-allow-origin': '*', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'x-frame-options': 'deny', 'x-content-type-options': 'nosniff', 'x-xss-protection': '0', 'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'content-security-policy': "default-src 'none'", 'vary': 'Accept-Encoding, Accept, X-Requested-With', 'x-github-request-id': 'A504:16D9:7CA0AB:9A6957:63BBA73D'})
GithubException(422, {'message': 'path cannot start with a slash', 'errors': [{'resource': 'Commit', 'field': 'path', 'code': 'invalid'}], 'documentation_url': 'https://docs.github.com/rest/reference/repos#create-or-update-file-contents'}, {'server': 'GitHub.com', 'date': 'Mon, 09 Jan 2023 05:33:50 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '207', 'x-oauth-scopes': 'admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, delete:packages, delete_repo, gist, notifications, repo, user, workflow, write:discussion, write:packages', 'x-accepted-oauth-scopes': '', 'x-github-media-type': 'github.v3; format=json', 'x-github-api-version-selected': '2022-11-28', 'x-ratelimit-limit': '5000', 'x-ratelimit-remaining': '4957', 'x-ratelimit-reset': '1673243877', 'x-ratelimit-used': '43', 'x-ratelimit-resource': 'core', 'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset', 'access-control-allow-origin': '*', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'x-frame-options': 'deny', 'x-content-type-options': 'nosniff', 'x-xss-protection': '0', 'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'content-security-policy': "default-src 'none'", 'vary': 'Accept-Encoding, Accept, X-Requested-With', 'x-github-request-id': 'A504:16D9:7CA0AB:9A6957:63BBA73D'})

**Comment by Fgaoxing** [comment]
@am-abudu 额，好的

**Comment by Fgaoxing** [comment]
@am-abudu 改成 无效

**Comment by Fgaoxing** [comment]
@am-abudu 
删除页面还是报错TypeError("'ContentFile' object is not subscriptable")，还有迁移导入时，pv部分报错import_pv错误: DataError('value too long for type character varying(200)\n')

**Comment by am-abudu** [comment]
对于第一个问题，我不太理解，是否可以给出操作流程
对于第二个问题，这取决于你使用的数据库支持的字符长度，在一些数据库中该问题无解

**Comment by am-abudu** [comment]
已经确认为Bug 等待修复

**Comment by Fgaoxing** [comment]
@am-abudu 试着把数据库的文本类型改为text值会好些

**Comment by am-abudu** [comment]
都说了这个问题和数据库没关系，是我打错了
