### ISSUE TITLE
怎么自动编译hexo

### ISSUE THREAD

**Issue by Inetgeek** [Qexo/Qexo#293]
### Qexo 版本

v2.4.3

### 平台

MongDB &Vercel

### 问题描述

我根据博主的教程完成了部署，但是发现写文章以后并不能自动编译hexo成静态资源，博主能给一些参考资料吗？第一次用

### 截图

![image](https://user-images.githubusercontent.com/42563262/211796674-ae6d23ee-da4f-404b-adf0-46daf3bd0fb8.png)

**Comment by am-abudu** [comment]
参考文章:
https://blog.cyfan.top/p/e626cb30.html
https://www.oplog.cn/archives/24998.html
https://crazywong.com/posts/74006f42
