### ISSUE TITLE
南方科技大学cdn出现504错误，致使无法进入面板

### ISSUE THREAD

**Issue by sysfox** [Qexo/Qexo#295]
### Qexo 版本

v2.5.0

### 平台

Mongodb && Vercel

### 问题描述

如题

### 截图

<img width="1278" alt="截屏2023-01-15 07 50 16" src="https://user-images.githubusercontent.com/99103591/212502246-8c2c7474-d1de-4b34-b026-edc9b22be68d.png">

**Comment by sysfox** [comment]
以下为解决方案（注意有多图）
1. 进入mongodb
2. 点击 Browse collections
<img width="1440" alt="截屏2023-01-15 08 12 36" src="https://user-images.githubusercontent.com/99103591/212502691-aaed7100-08d1-412f-bf82-8918f87e265b.png">
3.找到`Django > hexoweb_settingmodel`,并进入
4.点击右下角next进入下一页
<img width="1440" alt="截屏2023-01-15 08 15 28" src="https://user-images.githubusercontent.com/99103591/212502780-19958f55-8c5f-426e-b446-41a2015eea11.png">
5.滑到最下面，找到这玩意儿：
<img width="1440" alt="截屏2023-01-15 08 19 08" src="https://user-images.githubusercontent.com/99103591/212502873-818caad9-4d1a-48e3-89bb-3543c20e5ede.png">
6.点击`Edit Document`，将`https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/`更换为`https://cdnjs.cloudflare.com/ajax/libs/`
7.

**Comment by am-abudu** [comment]
你的方法切实有效，下面我给出另外的一种简单方法：

你只需访问`/pub/fix?token=(Your API Key)`即可自动恢复该部分设置

**Comment by am-abudu** [comment]
我认为该镜像只是临时性无法使用，故暂时不移除该镜像
