### ISSUE TITLE
版本号bug

### ISSUE THREAD

**Issue by sysfox** [Qexo/Qexo#296]
### Qexo 版本

v2.5.0

### 平台

Mongodb && Vercel

### 问题描述

当用户从master分支更新最新版(如这回的2.5.0)，而github的release缓存没更新的时候(依然为2.4.3)，就会出现滑稽的一幕：
当前版本：
2.5.0
有新版本：
2.4.3

建议作者增加一个版本号大小对比

### 截图

<img width="1440" alt="截屏2023-01-15 08 10 33" src="https://user-images.githubusercontent.com/99103591/212502615-3d283e68-43d0-4652-8510-75c626580621.png">

**Comment by am-abudu** [comment]
经过排查是我忘记设置成 latest version 了，现在应该问题已经解决
