### ISSUE TITLE
友联添加页面500

### ISSUE THREAD

**Issue by MarcusYYDS** [Qexo/Qexo#297]
### Qexo 版本

v2.20

### 平台

mongodb & vercel

### 问题描述

应该就是在调用`pub/add_friend`的api时没有加上值的原因
~_~求帮助

### 截图

![Screenshot_2023-01-15-13-33-08-68](https://user-images.githubusercontent.com/102860926/212524695-b4cf6d29-e7a9-480d-bb26-d47e668a624d.jpg)

**Comment by am-abudu** [comment]
是否可以描述一下你的操作流程

**Comment by MarcusYYDS** [comment]
直接访问的/pub/add_friend?token=

**Comment by am-abudu** [comment]
我这样操作后得到的结果和你不一样，你是否有别的操作

请包含浏览器地址栏截图（API密钥使用马赛克处理）

**Comment by MarcusYYDS** [comment]
我给你描述一下全过程：早上想更新，按了更新按钮之后提示好像是访问不到文件(记不太清了)，然后更新了下vercel的配置(项目id)，也是不行，就试了试api，访问/pub/add_friend?token=，然后发现打不开了，发了这条issues，下午回复我时，又去试了试，说说也是这样新建了一条(不是api)后就500了(以前没用说说)，更新能更新了，更新完后问题解决

**Comment by am-abudu** [comment]
现在问题是否解决

**Comment by MarcusYYDS** [comment]
已解决，麻烦了
