### ISSUE TITLE
自定义CDNJS时出现不一致现象

### ISSUE THREAD

**Issue by Fgaoxing** [Qexo/Qexo#298]
### Qexo 版本

2.5

### 平台

PG&vercel

### 问题描述

我改成自己搭建的CdnJS域名，但是设置里面显示的是
![image](https://user-images.githubusercontent.com/92655031/212546852-b7b2bfb6-4810-4369-88a8-43763211e4a7.png)

### 截图

具体CDN地址暂时不透露

**Comment by am-abudu** [comment]
修改高级设置造成的问题不予解决

**Comment by Fgaoxing** [comment]
@am-abudu 我……，这个，你判断不是列表里的，你显示和自定义就行了，无语
