### ISSUE TITLE
无法编辑说说

### ISSUE THREAD

**Issue by jdjwzx233** [Qexo/Qexo#299]
### Qexo 版本

v2.5.0

### 平台

MongoDB & Vercel

### 问题描述

无法显示编辑界面
报错：Uncaught SyntaxError: Unexpected token ';' (at edit_talk.html:970:26)

### 截图

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/81498925/212595815-56912cb0-cece-485c-976e-461bd2408f66.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/81498925/212595911-4b470c9b-8e47-4008-8e12-976859a4fe19.png">
<img width="325" alt="image" src="https://user-images.githubusercontent.com/81498925/212595924-e284a88d-9d0d-4bbf-a31c-9f252608280c.png">

**Comment by am-abudu** [comment]
请访问 `/update/` 进行配置更新

如果还未解决，请截图高级设置里面的 `TALK_SIDEBAR` 字段

**Comment by jdjwzx233** [comment]
好了
