### ISSUE TITLE
无法删除子用户

### ISSUE THREAD

**Issue by jdjwzx233** [Qexo/Qexo#300]
### Qexo 版本

v2.5.0

### 平台

MongoDB & Vercel

### 问题描述

删除子用户时报错
响应：{"msg": "DatabaseError()", "status": false}

### 截图

<img width="238" alt="image" src="https://user-images.githubusercontent.com/81498925/212600415-8e49f95f-919a-4094-9cb1-1a5b2b701993.png">

**Comment by am-abudu** [comment]
是否可以描述一下你的操作流程，我没有遇到过这样的问题

**Comment by jdjwzx233** [comment]
我在使用云端命令中的删除子用户，上面不是要求输入用户名和密码吗?然后我就输入了我创建子用户时的那个用户名和密码，然后执行，就报错了

**Comment by sysfox** [comment]
我昨天在Scipts开过这个issue了，里面有复现图
https://github.com/Qexo/Scripts/issues/#1

**Comment by am-abudu** [comment]
https://github.com/Qexo/Scripts/commit/962a51c0248c034e9b6710c84849f2f9ce08c297
