### ISSUE TITLE
友链申请的js链接失效

### ISSUE THREAD

**Issue by laobinghu** [Qexo/Qexo#303]
### Qexo 版本

v2.5.0

### 平台

MongoDB & Vercel

### 问题描述

如题（
链接https://cdn.jsdelivr.net/gh/Fgaoxing/blog-cdn@main/source/js/friends-api.js打开提示Couldn't find the requested file /source/js/friends-api.js in Fgaoxing/blog-cdn.

### 截图

这个应该不用罢

**Comment by am-abudu** [comment]
这个并不是由我维护 @Fgaoxing

**Comment by laobinghu** [comment]
我去看了一下，原作者博客上的js是引用到[这个地址](https://npm.elemecdn.com/qexo-friends/friends-api.js)的

**Comment by Fgaoxing** [comment]
@laobinghu 现在已经换成别的了，那个过时了，你看https://github.com/Qexo/Qexo/discussions/168
