### ISSUE TITLE
无法“删除隐藏”

### ISSUE THREAD

**Issue by ning0818** [Qexo/Qexo#312]
### Qexo 版本

v2.5.1最新版

### 平台

MongoDB && Vercal

### 问题描述

友链管理页面，点击“删除隐藏”按钮后报错DatabaseError()
![image](https://user-images.githubusercontent.com/117955401/215955740-1fe0686d-65ca-47d9-b750-5746d363bb7f.png)
一个一个删除就没事
![image](https://user-images.githubusercontent.com/117955401/215955805-1b86f6f9-2c8d-4b65-a3b4-ce9debc2ae2a.png)

### 复现链接

admin.example.com/friends.html

### 截图

![image](https://user-images.githubusercontent.com/117955401/215955934-b7059ac0-5886-49de-8973-788fdcb40d6a.png)
![image](https://user-images.githubusercontent.com/117955401/215956034-bea97aba-8a72-4dc5-85bc-4bb1b237971f.png)
![image](https://user-images.githubusercontent.com/117955401/215955978-da42e19a-60f7-40a2-b8b1-0834028dbac0.png)

### 嗯嗯嗯
@am-abudu

**Comment by am-abudu** [comment]
该问题已经在Dev修复过。请等待下个版本号发布
