### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by JeamUmika** [Qexo/Qexo#317]
### Qexo 版本

v2.6.1

### 平台

vercel

### 问题描述

更新到 v2.6.1 重新登陆就会出现

### 截图

![图片](https://user-images.githubusercontent.com/93057377/216654023-819581bc-0086-46e9-aa2d-a5f7e424054e.png)

**Comment by am-abudu** [comment]
请描述你是从什么版本更新的。

这里给出一个临时解决方案: 进入 settings.html 找到博客配置直接提交

**Comment by JeamUmika** [comment]
> 请描述你是从什么版本更新的。
> 
> 这里给出一个临时解决方案: 进入 settings.html 找到博客配置直接提交

v2.6.0

**Comment by am-abudu** [comment]
请告诉我如此操作之后问题是否解决

**Comment by JeamUmika** [comment]
> 请告诉我如此操作之后问题是否解决

解决了
