### ISSUE TITLE
删除文章出错

### ISSUE THREAD

**Issue by beyond24** [Qexo/Qexo#318]
### Qexo 版本

v2.6.1

### 平台

MongoDB & Vercel

### 问题描述

删除某一文章出错，如删除《使用 qexo》出错

### 复现链接

UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/repos#get-repository-content'}, {'server': 'GitHub.com', 'date': 'Mon, 13 Feb 2023 09:02:52 GMT', 'content-type': 'application/json; charset=utf-8', 'transfer-encoding': 'chunked', 'x-oauth-scopes': 'repo', 'x-accepted-oauth-scopes': '', 'x-github-media-type': 'github.v3; format=json', 'x-github-api-version-selected': '2022-11-28', 'x-ratelimit-limit': '5000', 'x-ratelimit-remaining': '4974', 'x-ratelimit-reset': '1676282498', 'x-ratelimit-used': '26', 'x-ratelimit-resource': 'core', 'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset', 'access-control-allow-origin': '*', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'x-frame-options': 'deny', 'x-content-type-options': 'nosniff', 'x-xss-protection': '0', 'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'content-security-policy': "default-src 'none'", 'vary': 'Accept-Encoding, Accept, X-Requested-With', 'content-encoding': 'gzip', 'x-github-request-id': '9B4E:15D6:6790A02:D3914A6:63E9FCBC'})

### 截图

![截屏2023-02-13 17 06 40](https://user-images.githubusercontent.com/67420638/218416656-dc663075-70e0-4032-9606-c73f57fb6da7.png)

**Comment by beyond24** [comment]
source/_posts/使用 qexo.md

**Comment by am-abudu** [comment]
我认为是带空格的文章名引起的错误。不知道Github的逻辑是怎么样的

**Comment by beyond24** [comment]
是的，在仓库手动删除空格，在 qexo 面板成功删除。
空格是输入法自动生成的[doge]
感谢解答
