### ISSUE TITLE
无法显示验证码

### ISSUE THREAD

**Issue by jdjwzx233** [Qexo/Qexo#323]
### Qexo 版本

V2.6.1

### 平台

MongoDB & Vercel

### 问题描述

验证码无法显示,疑似recaptcha.net挂了
建议立刻支持hcaptcha用于替换recaptcha

### 截图

<img width="284" alt="image" src="https://user-images.githubusercontent.com/81498925/221866576-d26bfde5-fd64-4508-a88d-dde045819ce8.png">
<img width="655" alt="image" src="https://user-images.githubusercontent.com/81498925/221866952-228bc49a-b310-4693-96ce-58a719410793.png">
<img width="496" alt="image" src="https://user-images.githubusercontent.com/81498925/221867114-1d64ac8c-4d3e-4ba7-be35-7b0620b2d34d.png">

**Comment by am-abudu** [comment]
我这里是正常的，可能是地区差异。我将更换到recaptcha.google.cn

**Comment by miaowmint** [comment]
> 我这里是正常的，可能是地区差异。我将更换到recaptcha.google.cn

谷歌验证码 reCAPTCHA 的镜像业务域名 recaptcha.net 已被 GFW DNS 污染

所以快换吧（
