### ISSUE TITLE
远程链接错误

### ISSUE THREAD

**Issue by xiatianPE** [Qexo/Qexo#329]
### Qexo 版本

v2.4.3

### 平台

MangoDB & Vercel

### 问题描述

提交的时候说远程链接错误请检查tokey
可是我一生成出来就复制粘贴，也没有错

### 截图

![Uploading Snipaste_2023-03-25_13-03-30.png…]()

**Comment by xiatianPE** [comment]
![Snipaste_2023-03-25_13-03-30](https://user-images.githubusercontent.com/121849812/227697621-828ee73f-5a5b-4302-97bd-71c7d71fd6fb.png)

**Comment by am-abudu** [comment]
仓库多了空格。另外请使用最新版本

**Comment by xiatianPE** [comment]
> 仓库多了空格。另外请使用最新版本

还是不行
![Snipaste_2023-03-25_13-40-03](https://user-images.githubusercontent.com/121849812/227698746-eec950e6-12ba-4f4d-b28e-b305c8481e15.png)

**Comment by am-abudu** [comment]
如果你确定没问题，最新版支持强制提交

**Comment by xiatianPE** [comment]
> 如果你确定没问题，最新版支持强制提交

更新完后错误500
按照文档的来修复，但不见什么效果

**Comment by xiatianPE** [comment]
为什么检测不出来文章

**Comment by am-abudu** [comment]
1 你要确保你已经通读了[文档](https://www.oplog.cn/qexo)
2 你需要提供你的程序版本、仓库信息等。
3 请不要把你的Github Token放在截图里面。你现在需要 **立刻** 删除掉这个Token
