### ISSUE TITLE
使用自定义域名并挂CloudflareCDN之后提示重定向过多

### ISSUE THREAD

**Issue by hatsuyuki2333** [Qexo/Qexo#332]
### Qexo 版本

v2.4.3

### 平台

MongoDB & Vercel

### 问题描述

使用Vercel的自定义域名功能，为新部署的Qexo添加了dash.hatsuyuki.eu.org域名（考虑到vercelapp在大陆的低可访问性，通过Cloudflare代理了其流量）。初次部署完成之后，用自定义域名打开网页，提示重定向过多ERR_TOO_MANY_REDIRECTS，且清除缓存无效，使用原域名qadmin.vercel.app访问没有问题。

### 复现链接

https://dash.hatsuyuki.eu.org
https://qadmin.vercel.app

### 截图

![原链接，访问无问题](https://user-images.githubusercontent.com/62411526/228177779-66988b23-d325-4f3d-b0b0-86639569741b.png)
![自定义域名并代理流量之后提示过多重定向](https://user-images.githubusercontent.com/62411526/228178085-0636a04c-d7b3-4826-860b-9457efb874f5.png)

**Comment by Fgaoxing** [comment]
去掉代理试试，我这边用代理没事啊，eu.org有问题，容易出毛病



在 2023-03-28 16:36:08，"Hatsuyuki" ***@***.***> 写道：

Qexo 版本

v2.4.3

平台

MongoDB & Vercel

问题描述

使用Vercel的自定义域名功能，为新部署的Qexo添加了dash.hatsuyuki.eu.org域名（考虑到vercelapp在大陆的低可访问性，通过Cloudflare代理了其流量）。初次部署完成之后，用自定义域名打开网页，提示重定向过多ERR_TOO_MANY_REDIRECTS，且清除缓存无效，使用原域名qadmin.vercel.app访问没有问题。

复现链接

https://dash.hatsuyuki.eu.org
https://qadmin.vercel.app

截图

**Comment by am-abudu** [comment]
这是CDN的配置问题。请在CloudflareSSL设置中改为完全(Full)。这不是程序问题
