### ISSUE TITLE
Hugo部署不能正常发布文章及显示文章列表

### ISSUE THREAD

**Issue by wyxogo** [Qexo/Qexo#335]
### Qexo 版本

v2.6.3

### 平台

MongoDB & Vercel

### 问题描述

主页中获取的文章数量为0
页面列表正常显示
发布的文章创建在`content/post`文件夹，hugo的文章发布为`content/posts`文件夹

### 复现链接

[https://admin.wyxogo.top/](https://admin.wyxogo.top/)

### 截图

主页中获取的文章数量为0
![image](https://user-images.githubusercontent.com/61509470/228593848-293b8f29-eeb1-4142-b3a7-0e0c3838b30c.png)

![image](https://user-images.githubusercontent.com/61509470/228594227-9b4b70a2-fb64-40e6-ad5f-f2bbb7af00fc.png)

页面列表正常显示
![image](https://user-images.githubusercontent.com/61509470/228594303-417f17f9-9856-467f-98b0-435623cfe048.png)

发布的文章创建在`content/post`文件夹，hugo的文章发布为`content/posts`文件夹
![image](https://user-images.githubusercontent.com/61509470/228594430-4390efd0-acfe-4c09-8028-6eeb10cd9b7c.png)

**Comment by am-abudu** [comment]
在查阅文档后，我发现这确实搞错了，请尝试Dev分支！

**Comment by wyxogo** [comment]
> 在查阅文档后，我发现这确实搞错了，请尝试Dev分支！

修改`configs.py`后问题依然存在
管理界面修改配置为hugo，刷新页面又会变成hexo
![Screenshot_2023-03-30-00-15-27-449_com microsoft emmx](https://user-images.githubusercontent.com/61509470/228602696-0da3b6cd-c6e9-4988-8724-6b5d9a468f18.jpg)

**Comment by am-abudu** [comment]
请尝试Dev分支，如果还有问题请告诉我清除缓存后访问文章页面的日志

**Comment by wyxogo** [comment]
已解决
