### ISSUE TITLE
无法通过点击空白处退出菜单栏

### ISSUE THREAD

**Issue by Qian-F** [Qexo/Qexo#338]
### Qexo 版本

2.6.4

### 平台

mongodb vercel部署

### 问题描述

在手机端点击菜单栏后，无法通过点击左侧空白处退出菜单，当写文章误触时这样是致命的

### 截图

![IMG_20230331_110144.jpg](https://vip2.loli.io/2023/03/31/gj3unJPhZwNbkrQ.jpg)

**Comment by am-abudu** [comment]
这貌似是模板的问题，我只能尽力而为

**Comment by Qian-F** [comment]
> 这貌似是模板的问题，我只能尽力而为

没事 能解决最好解决 解决不了也没事

**Comment by am-abudu** [comment]
> > 这貌似是模板的问题，我只能尽力而为
> 
> 没事 能解决最好解决 解决不了也没事

最近事情比较多，我考虑在今年晚些时候更新页面样式的版本，届时问题会得到解决

**Comment by Qian-F** [comment]
> > > 这貌似是模板的问题，我只能尽力而为
> > 
> > 
> > 没事 能解决最好解决 解决不了也没事
> 
> 最近事情比较多，我考虑在今年晚些时候更新页面样式的版本，届时问题会得到解决

好的 感谢

**Comment by ning0818** [comment]
跟discuz3.5的后台问题一模一样，点开了要是不刷新你是别想关掉

**Comment by am-abudu** [comment]
Dev分支已修复。
