### ISSUE TITLE
阿里云图床无法正常上传

### ISSUE THREAD

**Issue by wyxogo** [Qexo/Qexo#339]
### Qexo 版本

v2.6.3

### 平台

MongoDB & Vercel

### 问题描述

使用S3协议配置阿里云图床，无法成功上传，但在管理界面显示上传成功，打开图片链接报错

### 截图

![image](https://user-images.githubusercontent.com/61509470/229030341-0b4e0497-4197-4685-bfe1-4b95ceb42aec.png)
![image](https://user-images.githubusercontent.com/61509470/229030357-11c31e7b-7b1f-4353-a97f-dc8fb355d28f.png)

**Comment by luomochengshang** [comment]
我的挂腾讯云挂上去了，能正常访问
你看一下是不是阿里云文档你哪个地方填错了
https://help.aliyun.com/document_detail/31946.html
或者按照腾讯云的文档试试看
https://cloud.tencent.com/document/product/436/41284

**Comment by am-abudu** [comment]
请再检查一下你的配置有没有问题，以及文件是否有在储存库中出现

**Comment by wyxogo** [comment]
> 请再检查一下你的配置有没有问题，以及文件是否有在储存库中出现

存储库中是没有上传的文件的
配置如下
![image](https://user-images.githubusercontent.com/61509470/229143230-400bbc6a-fcb3-4ee9-9cfa-d84583b0ac51.png)

**Comment by luomochengshang** [comment]
> > 请再检查一下你的配置有没有问题，以及文件是否有在储存库中出现
> 
> 存储库中是没有上传的文件的 配置如下 ![image](https://user-images.githubusercontent.com/61509470/229143230-400bbc6a-fcb3-4ee9-9cfa-d84583b0ac51.png)

阿里云的边缘节点那个修改为https://oss-cn-beijing.aliyuncs.com试一下

**Comment by wyxogo** [comment]
> > > 请再检查一下你的配置有没有问题，以及文件是否有在储存库中出现
> > 
> > 
> > 存储库中是没有上传的文件的 配置如下 ![image](https://user-images.githubusercontent.com/61509470/229143230-400bbc6a-fcb3-4ee9-9cfa-d84583b0ac51.png)
> 
> 阿里云的边缘节点那个修改为https://oss-cn-beijing.aliyuncs.com 试一下


更改后报错如下

![image](https://user-images.githubusercontent.com/61509470/229268642-10da8981-ceec-49e1-acbf-c03daa9238c1.png)

**Comment by luomochengshang** [comment]
> > > > 请再检查一下你的配置有没有问题，以及文件是否有在储存库中出现
> > > 
> > > 
> > > 存储库中是没有上传的文件的 配置如下 ![image](https://user-images.githubusercontent.com/61509470/229143230-400bbc6a-fcb3-4ee9-9cfa-d84583b0ac51.png)
> > 
> > 
> > 阿里云的边缘节点那个修改为https://oss-cn-beijing.aliyuncs.com 试一下
> 
> 更改后报错如下
> 
> ![image](https://user-images.githubusercontent.com/61509470/229268642-10da8981-ceec-49e1-acbf-c03daa9238c1.png)

检查应用密钥ID和应用密钥，还有存储桶的权限配置

**Comment by mosuzi** [comment]
我也遇到了相同的问题，最后卡在了
> ERROR: ClientError('An error occurred (SecondLevelDomainForbidden) when calling the PutObject operation: Please use virtual hosted style to access.')(api.py.upload_img[line:717])
[04/Apr/2023 15:03:06] "POST /api/upload/ HTTP/1.0" 200 167
我检查过ID、密钥和权限，似乎没啥问题

另外，我是用 [miaowmint/Qexo-docker](https://github.com/miaowmint/Qexo-docker) 部署在本地的

**Comment by luomochengshang** [comment]
> 我也遇到了相同的问题，最后卡在了
> 
> > ERROR: ClientError('An error occurred (SecondLevelDomainForbidden) when calling the PutObject operation: Please use virtual hosted style to access.')(api.py.upload_img[line:717])
> > [04/Apr/2023 15:03:06] "POST /api/upload/ HTTP/1.0" 200 167
> > 我检查过ID、密钥和权限，似乎没啥问题
> 
> 另外，我是用 [miaowmint/Qexo-docker](https://github.com/miaowmint/Qexo-docker) 部署在本地的

首先检查权限，其次检查ID和密钥，你可以参照一下我发的那个腾讯云的文档，我按照文档调整了就好了

**Comment by mosuzi** [comment]
> > 我也遇到了相同的问题，最后卡在了
> > > ERROR: ClientError('An error occurred (SecondLevelDomainForbidden) when calling the PutObject operation: Please use virtual hosted style to access.')(api.py.upload_img[line:717])
> > > [04/Apr/2023 15:03:06] "POST /api/upload/ HTTP/1.0" 200 167
> > > 我检查过ID、密钥和权限，似乎没啥问题
> > 
> > 
> > 另外，我是用 [miaowmint/Qexo-docker](https://github.com/miaowmint/Qexo-docker) 部署在本地的
> 
> 首先检查权限，其次检查ID和密钥，你可以参照一下我发的那个腾讯云的文档，我按照文档调整了就好了

emm，我是用的是阿里云，看了下腾讯云的配置，只有这里是意料之外的，但是阿里云oss没有应用ID，所以应该还是正常的桶名称
![image](https://user-images.githubusercontent.com/43341701/229724336-9bfd0767-4764-40f4-b66c-6fb74df05575.png)
另外，腾讯云的COS支持Path-Style 与 Virtual Hosted-Style
但是阿里云仅支持后者，是否跟这个有关呢

**Comment by mosuzi** [comment]
因为上述的保存里，明确提到需要使用Virtual Hosted-Style来访问，所以我猜qexo是不是默认用了Path-Style导致的OSS拒绝了请求

**Comment by am-abudu** [comment]
> 因为上述的报错里，明确提到需要使用Virtual Hosted-Style来访问，所以我猜qexo是不是默认用了Path-Style导致的OSS拒绝了请求

如果是这样的话，我可能需要单独对阿里云进行支持。如果可以的话希望能够添加我的QQ方便测试：2753534031

**Comment by am-abudu** [comment]
使用Dev分支并选择“阿里云OSS”驱动即可
