### ISSUE TITLE
初始化错误

### ISSUE THREAD

**Issue by luomochengshang** [Qexo/Qexo#341]
### Qexo 版本

2.6.1,2.6.3,dev

### 平台

本地mysql和本地服务器

### 问题描述

再提个bug，迁移数据库后运行 python3 manage.py runserver --noreload 0.0.0.0:8000
然后直接进入 IP:8000会报400

### 截图
![企业微信截图_20230401134255](https://user-images.githubusercontent.com/57298119/229268229-fbec2b03-d789-472d-9fc1-871220dbf739.png)

**Comment by luomochengshang** [comment]
https://imgse.com/i/ppWnkVK
那张截图好像没用上传不了，我上传到图床了

**Comment by am-abudu** [comment]
请修改`configs.py`，在`DOMAINS`变量中加入你的域名。
假使你的域名为qexo.google.com, 你可以把该变量改为
```python
DOMAINS = ["127.0.0.1", "qexo.google.com"]
```
