### ISSUE TITLE
通过Qexo发布文章，发布成功后为什么在Qexo的控制台看不到刚发布的文章？

### ISSUE THREAD

**Issue by UniStart2** [Qexo/Qexo#344]
### Qexo 版本

2.6.4

### 平台

MongoDB & Vercel

### 问题描述

我通过Qexo管理面板在线编辑并发布了一篇测试文章，项目的github action都成功部署完成了，博客页面刷新也出现了测试文章，但是我在Qexo管理面板中没有看到我之前发布的测试文章，这是为什么？

仓库说明如下：
hexo-shoka：存放hexo博客源码的仓库，也是Qexo管理面板关联的仓库，该仓库通过github action完成对unistart2.github.io的重新部署
unistart2.github.io：存放hexo生成的静态博客内容的仓库

我想问一下通过Qexo管理面板发布文章成功后，刷新管理面板看不到新发布的文章是正常的情况还是不正常的情况啊？

### 截图

hexo-shoka执行github action，将新生成的public文件推送给unistart2.github.io仓库
![hexo-shoka](https://i.imgur.com/GDKjEfy.png)

unistart2.github.io执行github action，完成静态页面的重新部署
![unistart2.github.io](https://i.imgur.com/uQAc7ID.png)

博客页面测试文章出现了
![blog](https://i.imgur.com/07Q0o7I.png)

Qexo管理面板缺看不到刚才发布的文章
![Qexo Dashboard](https://i.imgur.com/O6U3plj.gif)

**Comment by am-abudu** [comment]
See #165

**Comment by UniStart2** [comment]
解决了
