### ISSUE TITLE
更新的文章符号和时间有问题

### ISSUE THREAD

**Issue by JeamUmika** [Qexo/Qexo#345]
### Qexo 版本

v2.6.4

### 平台

Vercel

### 问题描述

在更新一篇文章后，更新时间变成了外国的时间，而且格式也是外国的。然后是大部分中文符号变成了英文符号。

### 截图

![图片](https://user-images.githubusercontent.com/93057377/230375710-67022b20-25cb-4581-bd2d-40276c0fa937.png)

---

![图片](https://user-images.githubusercontent.com/93057377/230376159-a41eb26d-f9e9-4870-b56b-9b7616fa6fee.png)

**Comment by am-abudu** [comment]
1. 时间是这样设计的。这是非常标准的时间格式，为了防止部分博客程序不兼容而这样设计
2. 第二个问题我并没有遇到，你需要检查一下

**Comment by JeamUmika** [comment]
> 1. 时间是这样设计的。这是非常标准的时间格式，为了防止部分博客程序不兼容而这样设计
> 
>     2. 第二个问题我并没有遇到，你需要检查一下，比如你的输入法是否处于半角符号模式

1. 以前更新的博客时间是这样的，而不是上面的图片所示
![图片](https://user-images.githubusercontent.com/93057377/230380205-a9dde634-ecc5-4e98-8030-9ce5e59bf429.png)

2. 我试过了，无论是更新文章还是发布新文章，点击`发布`后中文的符号就会变成英文的。

**Comment by JeamUmika** [comment]
> 1. 以前的格式Hugo无法自适应，所以现在统一改成了新的格式
> 
>     2. 我暂时没有复现出来这个问题。这可能是编辑器的问题，你可以到Vditor项目提起Issue。但是我自己的[文章](https://www.oplog.cn/archives/8962.html) 显然中文字符是正常的

格式改成这样没问题，但是好像时间变成伦敦的时间了而非北京时间，不知道这个`更新时间`是以什么来判定的

**Comment by am-abudu** [comment]
> > 1. 以前的格式Hugo无法自适应，所以现在统一改成了新的格式
> >    
> >    2. 我暂时没有复现出来这个问题。这可能是编辑器的问题，你可以到Vditor项目提起Issue。但是我自己的[文章](https://www.oplog.cn/archives/8962.html) 显然中文字符是正常的
> 
> 格式改成这样没问题，但是好像时间变成伦敦的时间了而非北京时间，不知道这个`更新时间`是以什么来判定的

格林尼治标准时间，只是时区不一样而已，程序读出来一样的时间戳。这是从浏览器获取到的时间

**Comment by JeamUmika** [comment]
退回到`v2.6.4`后正常了

**Comment by am-abudu** [comment]
> 退回到`v2.6.4`后正常了

但是现在最新版本就是2.6.4。并且新的推送里面没有对此进行修改

**Comment by JeamUmika** [comment]
> > 退回到`v2.6.4`后正常了
> 
> 但是现在最新版本就是2.6.4。并且新的推送里面没有对此进行修改

诶呀，说错了。是 2.6.3

**Comment by am-abudu** [comment]
那么可能是2.6.4版本添加的Unicode补丁导致的。我在Dev分支修改一下看看

**Comment by am-abudu** [comment]
请查看Dev分支

**Comment by JeamUmika** [comment]
> 请查看Dev分支

dev 分支已经解决`中文符号变成英文符号`的问题了

**Comment by am-abudu** [comment]
另一个并不是程序问题，本贴终结
