### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by Ezgx** [Qexo/Qexo#356]
### Qexo 版本

我不知道

### 平台

mongodb+vercel

### 问题描述

![image](https://user-images.githubusercontent.com/110729988/231829427-d32c56be-68cb-4f5c-8969-0f5476af8061.png)
![image](https://user-images.githubusercontent.com/110729988/231829577-4248db3a-d797-41cf-ba00-07ee3cc73801.png)

### 复现链接

无

### 截图

![image](https://user-images.githubusercontent.com/110729988/231829644-2eec5daf-21d3-46d0-b1d0-b052b08a19f3.png)
![image](https://user-images.githubusercontent.com/110729988/231829663-36cf422c-67f3-41d0-b6af-5594f73235d0.png)

**Comment by Ezgx** [comment]
![image](https://user-images.githubusercontent.com/110729988/231833156-49bf72cf-fb04-4f03-bb63-10ef84e4dd86.png)
删掉domains部署后这样了

**Comment by am-abudu** [comment]
数据库权限设置错误

**Comment by Ezgx** [comment]
> 数据库权限设置错误

我使用用mongodb，麻烦问下大佬该怎样设置权限，谢谢，

**Comment by Ezgx** [comment]
![Uploading image.png…]()

**Comment by Ezgx** [comment]
![image](https://user-images.githubusercontent.com/110729988/232237548-43c24979-e514-4ec5-aea8-4e151bc13195.png)为什么我的界面会出现遮挡
