### ISSUE TITLE
在线更新无反应

### ISSUE THREAD

**Issue by xiatianPE** [Qexo/Qexo#358]
### Qexo 版本

v.2.6.2

### 平台

mongodb&vercel

### 问题描述

在线更新无反应，等了十几分钟vercel也没反应

### 截图

![Snipaste_2023-04-15_11-18-14](https://user-images.githubusercontent.com/121849812/232180437-d8ac8bfb-3a3d-4bf5-b587-9793f4e2a6a0.png)

**Comment by xiatianPE** [comment]
太久没有，忘了。文档也看了

**Comment by am-abudu** [comment]
你需要在高级设置检查你的`VERCEL_TOKEN`和`PROJECT_ID`

**Comment by xiatianPE** [comment]
这个又是什么情况
![Snipaste_2023-05-03_10-23-22](https://user-images.githubusercontent.com/121849812/235822026-ce58faf7-6db2-493b-88d0-9f0443d9d1e4.png)

**Comment by am-abudu** [comment]
同样的问题

**Comment by xiatianPE** [comment]
这个又是什么情况
![Snipaste_2023-05-03_11-13-37](https://user-images.githubusercontent.com/121849812/235826925-21220fd3-7386-402f-b6c8-97e912428dba.png)

**Comment by am-abudu** [comment]
这个CDN可能出现问题，你需要在数据库里面修改。之后我会下掉这个CDN

**Comment by xiatianPE** [comment]
移动端又出现这个了重构也没问题
![Screenshot_20230514_132451](https://github.com/Qexo/Qexo/assets/121849812/69010ef3-537b-40d3-b6a4-387c599f6bb4)
![Screenshot_20230514_132455](https://github.com/Qexo/Qexo/assets/121849812/86c9f50f-8c15-4597-a084-123ea1a9b27c)
