### ISSUE TITLE
样式错乱

### ISSUE THREAD

**Issue by Ezgx** [Qexo/Qexo#359]
### Qexo 版本

最新版

### 平台

supabase+vercel

### 问题描述

出现遮挡

### 复现链接

无

### 截图

![image](https://user-images.githubusercontent.com/110729988/232238050-2f537039-ff18-43c4-926d-1baee2685f3a.png)
我看到别人发过这个问题，这个bug现在还是存在的。

**Comment by am-abudu** [comment]
等待样式重构

**Comment by Ezgx** [comment]
完成了咩？

**Comment by am-abudu** [comment]
> 作者大大别咕了（）

上个月底完成了一部分，最近因为一些事情耽搁了。我尝试在这两个月完成

**Comment by Ezgx** [comment]
> > 作者大大别咕了（）
> 
> 上个月底完成了一部分，最近因为一些事情耽搁了。我尝试在这两个月完成

好的 谢谢
