### ISSUE TITLE
文章编辑列表消失

### ISSUE THREAD

**Issue by yoloyb** [Qexo/Qexo#362]
### Qexo 版本

v2.7.0

### 平台

vercel

### 问题描述

文章编辑 详细细节吗 上方列表小时
![1681780144805](https://user-images.githubusercontent.com/118678239/232643363-00144b2d-3e74-423e-8407-13b13faaff00.png)

### 截图

![Uploading 1681780144805.png…]()

**Comment by Alcexn** [comment]
这个问题我也遇到了，有时可以加载出来，但是很多时候都加载不出来，更换网络环境也不行（挂过梯子）

**Comment by Alcexn** [comment]
这好像是默认https://unpkg.com/，好像也不行

**Comment by am-abudu** [comment]
那就请尝试改为`https://npm.onmicrosoft.cn/`

**Comment by Alcexn** [comment]
还是没有显示，cdn可以访问，控制台有几个报错
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
new.html:1097 
        
       Uncaught (in promise) TypeError: Cannot read properties of null (reading '0')
    at show_categories (new.html:1097:54)
    at showSidebar (new.html:1222:29)
    at Object.after (new.html:832:21)
    at index.min.js:1:267693

**Comment by am-abudu** [comment]
3dc6a03a20d9f18aba9eeaec07665a9ab9cbea35
