### ISSUE TITLE
SMMS 图床API报错

### ISSUE THREAD

**Issue by xiatianPE** [Qexo/Qexo#368]
### Qexo 版本

v2.7

### 平台

MongoDB & Vercel

### 问题描述

上传的时候报错，按照文档配置的

### 截图

![Snipaste_2023-05-02_14-28-51](https://user-images.githubusercontent.com/121849812/235595275-0e783380-4586-49e0-8641-7bac3fd323aa.png)

![Snipaste_2023-05-02_14-34-45](https://user-images.githubusercontent.com/121849812/235596487-1590caf9-94ed-4e3b-a8d4-53d3b952d98f.png)

**Comment by am-abudu** [comment]
未指定请求主体/请求头
