### ISSUE TITLE
无法发布文章和生成摘要

### ISSUE THREAD

**Issue by momo54181** [Qexo/Qexo#370]
### Qexo 版本

v2.8.0

### 平台

Vercel

### 问题描述

无法发布文章和生成摘要
点不动

### 截图

![image](https://user-images.githubusercontent.com/79344479/235605004-e7ddf1bf-5f6a-4c8e-b585-272e3e8396aa.png)

**Comment by momo54181** [comment]
说说报错误
! Error 500
报错信息：name 'excerpt_post' is not defined

**Comment by am-abudu** [comment]
请告诉我你是在哪个页面遇到的问题

**Comment by momo54181** [comment]
文章发布页

**Comment by momo54181** [comment]
qexourl/edit.html?file=source/_posts/

**Comment by am-abudu** [comment]
请加我QQ私聊排查

**Comment by momo54181** [comment]
生成摘要和发布点不了，保存草稿可以

**Comment by am-abudu** [comment]
如果有遇到类似情况可进入`设置->文章截取设置`点击保存以更新配置
