### ISSUE TITLE
一键更新失败

### ISSUE THREAD

**Issue by Mask37** [Qexo/Qexo#373]
### Qexo 版本

v2.7.0

### 平台

PostgreSQL & Vercel

### 问题描述

一键更新后天日志打印message":"Project name contains invalid characters. Only lower case alphanumeric characters and hyphens are allowed.

[WARNING]	2023-05-04T03:39:50.416Z	84008c7e-7cf6-4cf1-b53c-6da968c41ed7	开始更新, 使用Vercel方案
[WARNING]	2023-05-04T03:39:50.658Z	84008c7e-7cf6-4cf1-b53c-6da968c41ed7	下载更新完成, 开始解压
[WARNING]	2023-05-04T03:39:50.685Z	84008c7e-7cf6-4cf1-b53c-6da968c41ed7	解压完成, 寻找Index目录
[WARNING]	2023-05-04T03:39:50.694Z	84008c7e-7cf6-4cf1-b53c-6da968c41ed7	找到Index目录: /tmp/Qexo-Qexo-dab56b9
[WARNING]	2023-05-04T03:39:51.571Z	84008c7e-7cf6-4cf1-b53c-6da968c41ed7	更新完成: {"error":{"code":"bad_request","message":"Project name contains invalid characters. Only lower case alphanumeric characters and hyphens are allowed.","meta":{}}}
[WARNING]	2023-05-04T03:39:51.572Z	84008c7e-7cf6-4cf1-b53c-6da968c41ed7	开始删除文件...
[WARNING]	2023-05-04T03:39:51.742Z	84008c7e-7cf6-4cf1-b53c-6da968c41ed7	保存设置UPDATE_FROM => 2.7.0

### 截图

![image](https://user-images.githubusercontent.com/24933870/236113043-8d222638-7d62-419e-9bbd-35ed5662ac3a.png)
![image](https://user-images.githubusercontent.com/24933870/236113206-0421d51b-cad7-4a00-bfef-4a816fe35a54.png)

**Comment by am-abudu** [comment]
根据提示信息 你的项目名可能有问题。请告诉我你的项目名称是什么

**Comment by Mask37** [comment]
Qexo

**Comment by am-abudu** [comment]
请尝试重建一个项目 可以使用一样的数据库和环境变量。
我认为是Vercel的API问题

**Comment by Mask37** [comment]
确实，重建后可以正常更新
