### ISSUE TITLE
友链js文件阿里云掉了

### ISSUE THREAD

**Issue by xiaohao8** [Qexo/Qexo#382]
### Qexo 版本

2.4.3

### 平台

vercel

### 问题描述

如题
Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>645E5FCE57C68C3338CE1700</RequestId>
<HostId>fe-static-zbprod-zb1-oss-3.oss-cn-zhangjiakou.aliyuncs.com</HostId>
<Key>qexo-static@1.5.1/hexo/friends/friends.js</Key>
<EC>0041-00000113</EC>
</Error>

### 截图

https://npm.elemecdn.com/qexo-static@1.5.1/hexo/friends/friends.js

**Comment by A-pursuer** [comment]
我也遇到了同样的问题，是wiki没有更新导致的，你可以将链接替换为https://unpkg.com/qexo-static@1.6.0/hexo/friends.js就好啦

**Comment by Fgaoxing** [comment]
你好两位，请注意，在这里的链接已经被删除了，请看https://github.com/Qexo/Qexo-Friends/wiki

**Comment by Fgaoxing** [comment]
@xiaohao8 @A-pursuer

**Comment by am-abudu** [comment]
我会修复文档的

**Comment by am-abudu** [comment]
已经完成 https://github.com/Qexo/wiki/commit/9055c34a882b39607b65abf34c6bc7b877c8d1ca

**Comment by Fgaoxing** [comment]
@am-abudu 请将blog-cdn仓库改为Wiki中的链接，（算了我自己来吧）
