### ISSUE TITLE
出现 Error 500 报错

### ISSUE THREAD

**Issue by Can1425** [Qexo/Qexo#385]
### Qexo 版本

v2.7.0

### 平台

bit.io & Vercel

### 问题描述

程序在部署成功后正常运行了一段时间，但稍后出现了 Error 500 报错
主要表现为：登录后出现报错

### 截图

![Screenshot_20230521_073629_alook browser](https://github.com/Qexo/Qexo/assets/101759631/cc4bb823-314c-4ce9-8b6f-ae8bb4d61bb6)

**Comment by Jeamorg** [comment]
请阅读 `README.md` 进行排查

**Comment by am-abudu** [comment]
大概率是配置问题。访问settings.html以修改配置
