### ISSUE TITLE
qexo编辑文章后github有新文章，vercel这里报错

### ISSUE THREAD

**Issue by rzh0504** [Qexo/Qexo#388]
### Qexo 版本

v2.4.3

### 平台

MongoDB&Qexo

### 问题描述

如图所示

### 截图

![image](https://github.com/Qexo/Qexo/assets/93367900/5d19ffb9-9a18-4083-b809-e8d75c882595)

**Comment by Fgaoxing** [comment]
package有问题，跟Qexo没关系



在 2023-05-25 14:58:53，"Richard" ***@***.***> 写道：

Qexo 版本

v2.4.3

平台

MongoDB&Qexo

问题描述

如图所示

复现链接

No response

截图

**Comment by am-abudu** [comment]
于本程序无关
