### ISSUE TITLE
点击编辑文章&编辑其他页面 错误Error 500

### ISSUE THREAD

**Issue by dishao123** [Qexo/Qexo#391]
### Qexo 版本

v2.8.1

### 平台

PlanetScale & Vercel

### 问题描述

在点击编辑文章或编辑其他页面后出现以下提示

错误! Error 500
报错信息：'NoneType' object has no attribute 'keys'

尝试过文档中的所有办法，使用高级设置中的修复功能，更新稳定版以及开发版，重新部署还是无法解决

### 复现链接

https://qexo.8698888.xyz/edit.html?file=source/_posts/hello-world.md&postname=hello-world

### 截图

![IMG_1320](https://github.com/Qexo/Qexo/assets/58305876/7fdc2eb8-a9ad-4888-8085-43fc8861524e)

**Comment by am-abudu** [comment]
问题已解决
