### ISSUE TITLE
504: GATEWAY_TIMEOUT

### ISSUE THREAD

**Issue by musnows** [Qexo/Qexo#392]
### Qexo 版本

v2.4.3

### 平台

MonogoDB & Vercel

### 问题描述

部署成功，能成功打开初始化面板，但是无法正常初始化

### 截图

部署成功，能成功打开初始化面板

![image](https://github.com/Qexo/Qexo/assets/87506951/41723fdd-0bcf-4665-9807-770c7558f7c9)

点击开始之后就转到了下图页面

![image](https://github.com/Qexo/Qexo/assets/87506951/ea091b56-9ea0-45a1-a554-d2fb9746775e)

看了后台日志，似乎是保存配置什么的出现了问题

![image](https://github.com/Qexo/Qexo/assets/87506951/1cbfdfde-38e4-444d-a4e0-2146e272a1c9)

数据库已经配置了`0.0.0.0/0`允许所有ip访问

**Comment by am-abudu** [comment]
请使用对应地区的MongoDB数据库（见文档）
