### ISSUE TITLE
出现 500 报错

### ISSUE THREAD

**Issue by Alcexn** [Qexo/Qexo#397]
### Qexo 版本

v2.8.1

### 平台

Vercel 部署 (PostgreSQL/Vercel)Vercel 数据库

### 问题描述

刚部署没多久，就出现 500 报错使用 Vercel 数据库，登录正常可以登录，登录后主页无法进入出现 500 错误，只能访问 advanced.html，自动修复没用，数据库连接正常绑定在项目中
![Screenshot_20230607_215716_com microsoft emmx](https://github.com/Qexo/Qexo/assets/125755021/cbfc2a39-5520-42cc-aaaa-fed62b69792d
![Screenshot_20230607_215725_com microsoft emmx](https://github.com/Qexo/Qexo/assets/125755021/4a846347-cc62-4179-8386-7549bcef253b)
)
![Screenshot_20230607_215432_com microsoft emmx](https://github.com/Qexo/Qexo/assets/125755021/0172e992-03ee-4bb4-b485-9d5bcccaf18c)

### 复现链接

qexo.alcex.top

### 截图

![Screenshot_20230607_215725_com microsoft emmx](https://github.com/Qexo/Qexo/assets/125755021/5a6c46ca-e01e-49a1-a70e-d5a476a3adfe)

**Comment by am-abudu** [comment]
settings.html 能否进入。若能，请检查博客配置

**Comment by Alcexn** [comment]
不能，只能进入 advanced.html

**Comment by lgeger** [comment]
同样出现这个问题，登陆完成后报500，不能进settings.html，可以进advanced.html，点击修复，修复6个配置项，但是其他页面还是进不去

**Comment by Einstein-schrodinger** [comment]
同样的问题，settings.html无法进入

**Comment by Einstein-schrodinger** [comment]
![image](https://github.com/Qexo/Qexo/assets/62790820/0ddd7a23-b785-4762-9c60-0de22b676e79)
我github的token变了，修改这个参数之后可以进入settings.html了
