### ISSUE TITLE
文章缺失后不能删除

### ISSUE THREAD

**Issue by ljl2107** [Qexo/Qexo#400]
### Qexo 版本

2.4.3

### 平台

supabase+Vercel

### 问题描述

当我新建并发布了一个文章后，发现在网站中并没有更新，查看后也没有提交到我的个人博客仓库里，但是此时后台却有显示，如果点击编辑或者删除便会报错。

### 截图

![image](https://github.com/Qexo/Qexo/assets/106523995/e21ff5be-ae3b-4300-a94b-e72ab37a0987)

**Comment by am-abudu** [comment]
#112

**Comment by ljl2107** [comment]
已解决
