### ISSUE TITLE
数据库 找到包含settingmodel的表 然后找到字段里面包含RECAPTCHA的项 删除即可

### ISSUE THREAD

**Issue by ning0818** [Qexo/Qexo#402]
数据库 找到包含settingmodel的表 然后找到字段里面包含RECAPTCHA的项 删除即可

_Originally posted by @am-abudu in https://github.com/Qexo/Qexo/discussions/401#discussioncomment-6251458_

？？？？？？？？？？
![image](https://github.com/Qexo/Qexo/assets/117955401/057be4de-5757-4513-bd4e-fd159f559e38)
![image](https://github.com/Qexo/Qexo/assets/117955401/21e0d668-ecd4-4409-8093-c38dc681c77f)

**Comment by ning0818** [comment]
@am-abudu

**Comment by am-abudu** [comment]
你只需要删除content内容即可

**Comment by ning0818** [comment]
> 你只需要删除content内容即可

对，我只删了content里面的
但他现在500

**Comment by am-abudu** [comment]
请先参考[文档](https://www.oplog.cn/qexo/start/questions.html#%E5%AE%89%E8%A3%85-%E6%9B%B4%E6%96%B0%E5%90%8E%E5%87%BA%E7%8E%B0-5xx-%E9%94%99%E8%AF%AF) 排查，如果还未解决请给出函数报错信息

**Comment by ning0818** [comment]
> 函数报错信息

请问在哪里看函数报错信息？

**Comment by ning0818** [comment]
/advanced.html
为什么每次修复都
> 尝试自动修复了4个字段，请在稍后检查和修改配置
刷新完在修复还是
> 尝试自动修复了4个字段，请在稍后检查和修改配置

**Comment by am-abudu** [comment]
你可以尝试重新部署。我觉得你删除了错误的内容

**Comment by Fgaoxing** [comment]
请仔细阅读文档
请仔细阅读并背诵文档，或者重写部署



在 2023-06-24 16:48:38，"阳光下的小宁宁" ***@***.***> 写道：

/advanced.html
为什么每次修复都

尝试自动修复了4个字段，请在稍后检查和修改配置
刷新完在修复还是
尝试自动修复了4个字段，请在稍后检查和修改配置
