### ISSUE TITLE
上传图片保存路径不能转换大写的关键词

### ISSUE THREAD

**Issue by wanghaoxi3000** [Qexo/Qexo#404]
### Qexo 版本

v2.8.1

### 平台

PlanetScale & Vercel

### 问题描述

添加 S3 图床，保存路径为 `img/qexo/{YEAR}/{year}-{MONTH}-{DAY}-{md5}.{extName}`, 上传后实际路径为 `/{YEAR}/2023{MONTH}{DAY}-0f2392e07f84ab7e179b5783626cfef1.png` ，所有大写的关键词都没有转换成功。

### 截图

设置页面
<img width="544" alt="image" src="https://github.com/Qexo/Qexo/assets/10104549/1a1ce65c-1862-4025-a5b0-fa8f7cad95c6">

实际地址
<img width="819" alt="image" src="https://github.com/Qexo/Qexo/assets/10104549/f1d228b0-5cd1-4652-b9a4-38f6ec36aec3">

**Comment by am-abudu** [comment]
该功能还未推送至master。请使用dev分支
