### ISSUE TITLE
云服务器部署

### ISSUE THREAD

**Issue by wleelw** [Qexo/Qexo#405]
### Qexo 版本

v2.4.3

### 平台

本地

### 问题描述

我在远程服务器上部署了Qexo
使用ip+host访问，报错502无法访问

### 截图

![image](https://github.com/Qexo/Qexo/assets/74389842/c0d2feb4-4444-4db5-9965-6ab64ef5b680)
![image](https://github.com/Qexo/Qexo/assets/74389842/06fd8ab3-b082-4a2f-8af9-dc10daf247a1)
![image](https://github.com/Qexo/Qexo/assets/74389842/fdf0b34c-797c-4471-ace4-1abd191d31aa)
![image](https://github.com/Qexo/Qexo/assets/74389842/1b269b84-002d-45b1-8806-62245f29672f)

**Comment by am-abudu** [comment]
我需要更多日志。没有更多日志了吗

**Comment by wleelw** [comment]
没有，没有日志了，docker容器日志没有报错

**Comment by wleelw** [comment]
![image](https://github.com/Qexo/Qexo/assets/74389842/cf5fe54c-59af-46d9-8873-e80b6f48b843)


> 我需要更多日志。没有更多日志了吗

**Comment by wleelw** [comment]
![image](https://github.com/Qexo/Qexo/assets/74389842/291bcddc-a667-41c0-8815-c9a5cef5c73e)

**Comment by am-abudu** [comment]
请检查防火墙设置，端口转发配置以及nginx代理配置。或者验证相同状况下本地部署能否正常运行

**Comment by am-abudu** [comment]
请确认问题是否已经解决
