### ISSUE TITLE
不支持 Cloudflare 的 S3 API 吗？

### ISSUE THREAD

**Issue by Jeamorg** [Qexo/Qexo#407]
### Qexo 版本

 2.8.1 

### 平台

Vercel

### 问题描述

如图所示，调用 Cloudflare 的 S3 API 时发生错误

### 截图

![Snipaste_2023-06-30_20-50-39](https://github.com/Qexo/Qexo/assets/93057377/e5ff1147-7f71-4b08-b889-c77e846f9642)

![Snipaste_2023-06-30_20-52-30](https://github.com/Qexo/Qexo/assets/93057377/489c1b9d-468c-4780-864e-dd6386e27082)

**Comment by am-abudu** [comment]
或许是边缘节点填写错误？

**Comment by Jeamorg** [comment]
> 或许是边缘节点填写错误？

边缘节点我填的是 S3 的 API

**Comment by Jeamorg** [comment]
这是 cloudflare S3 的数据位置 https://developers.cloudflare.com/r2/buckets/data-location/#available-hints

**Comment by Jeamorg** [comment]
> 或许是边缘节点填写错误？

边缘节点没写错，就是S3 的API。在PicGo能上传，PicGo可以选择地区，我觉得是地区的问题

![Snipaste_2023-07-02_08-35-28](https://github.com/Qexo/Qexo/assets/93057377/6904f5f7-91f9-46fe-ade2-cc1b7665a23b)

**Comment by am-abudu** [comment]
我将加上这个配置项

**Comment by momo54181** [comment]
支持的

**Comment by Jeamorg** [comment]
> 支持的

那成功的操作是什么？

**Comment by am-abudu** [comment]
> > 支持的
> 
> 那成功的操作是什么？

目前或许确实存在问题。会和界面样式一同更新

**Comment by am-abudu** [comment]
已经在Dev分支更新

**Comment by Jeamorg** [comment]
> 已经在Dev分支更新

使用 dev 分支后出现 Error 500 。进入设置，将博客配置提交/强制提交出现以下错误
ProgrammingError(1146, 'target: xxx.-.primary: vttablet: Table \'xxx.hexoweb_postmodel\' doesn\'t exist (errno 1146) (sqlstate 42S02) (CallerID: 6nlelckr5mcipai4414j): Sql: "delete from hexoweb_postmodel", BindVars: {REDACTED}')

**Comment by am-abudu** [comment]
请先回到master分支，稍等我修复问题

**Comment by am-abudu** [comment]
你是通过一键更新进行的更新吗？我这边报错了。原因不明
<img width="428" alt="26ef1891a58a1a125f85fa8b36ca6ad1" src="https://github.com/Qexo/Qexo/assets/51912589/1e390b52-4619-4dca-904a-c7715aa8c8d2">

**Comment by Jeamorg** [comment]
> 你是通过一键更新进行的更新吗？我这边报错了。原因不明
> <img width="428" alt="26ef1891a58a1a125f85fa8b36ca6ad1" src="https://github.com/Qexo/Qexo/assets/51912589/1e390b52-4619-4dca-904a-c7715aa8c8d2">
> 
> 

我是通过合并 GitHub 仓库的 dev 分支，然后部署 dev 分支的

**Comment by Jeamorg** [comment]
dev 分支可以通过 Cloudflare S3 API 上传文件/图片了。除了主页是 error500，其他页面均正常

**Comment by am-abudu** [comment]
我将着手解决这个问题

**Comment by am-abudu** [comment]
现在应该可以了。你需要更新Dev分支。建议使用一键更新按键
