### ISSUE TITLE
[小问题]Qexo在init时校验主题时的错误，主题文件夹名包含大写的情况

### ISSUE THREAD

**Issue by 2877242250** [Qexo/Qexo#408]
### Qexo 版本

v2.8.1

### 平台

MySql本地部署

### 问题描述

使用Acrylic主题部署时，该主题文件夹首字母大写，初始化时一直校验报错，找到了问题所在functions.py的第660行
`theme = str(content.get("theme")).to_lower()`
去掉to_lower()方法即可

### 截图

![image](https://github.com/Qexo/Qexo/assets/22912744/14e087fc-05b2-4dfb-9199-43489ebb1b2e)

**Comment by am-abudu** [comment]
下个版本加入

**Comment by am-abudu** [comment]
已在Dev分支推送
