### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by xiaohao8** [Qexo/Qexo#413]
### Qexo 版本

2.4.3

### 平台

vercel

### 问题描述

之前一直正常，然后啥也没干再打开就显示
错误! Error 500
报错信息：程序遇到了错误！

### 复现链接

https://admin.202271.xyz/init/

### 截图

1

**Comment by am-abudu** [comment]
请检查github token是否过期。请尝试进入/settings.html或者/advanced.html进行修正

**Comment by Qian-F** [comment]
相同错误/settings.html和/advanced无法打开.html
