### ISSUE TITLE
访问/settings.html时，跳转回主页面

### ISSUE THREAD

**Issue by ning0818** [Qexo/Qexo#414]
### Qexo 版本

2.8.1

### 平台

Postgres & Vercel

### 问题描述

访问/settings.html时，重定向回主页面

视频链接：
https://github.com/Qexo/Qexo/assets/117955401/2bdfb741-5f6d-4b68-9d42-209fc13d3a78

### 复现链接

https://q.yuanning0818.tk/

已经出现过好多次了，上次出现是在2天前，我以为是fgaoxing给一阵恶意搞坏了，就重建了一个，结果今天又坏了

### 截图

视频链接：
https://github.com/Qexo/Qexo/assets/117955401/2bdfb741-5f6d-4b68-9d42-209fc13d3a78

**Comment by ning0818** [comment]
@am-abudu

**Comment by Fgaoxing** [comment]
我又不是闲的，我干嘛给你恶搞，而且没改代码不会出现问题的，除非我去改上游依赖或者CDN



在 2023-07-14 14:46:59，"阳光下的小宁宁" ***@***.***> 写道：

Qexo 版本

2.8.1

平台

Postgres & Vercel

问题描述

访问/settings.html时，重定向回主页面

视频链接：
https://github.com/Qexo/Qexo/assets/117955401/2bdfb741-5f6d-4b68-9d42-209fc13d3a78

复现链接

https://q.yuanning0818.tk/

已经出现过好多次了，上次出现是在2天前，我以为是fgaoxing给一阵恶意搞坏了，就重建了一个，结果今天又坏了

截图

视频链接：
https://github.com/Qexo/Qexo/assets/117955401/2bdfb741-5f6d-4b68-9d42-209fc13d3a78

**Comment by Fgaoxing** [comment]
我认为这不是Bug，而是你的问题，在我的Qexo没有出现该问题

**Comment by Fgaoxing** [comment]
检查过了，但是代码不会引起该操作，可能是你登录的问题

**Comment by Jeamorg** [comment]
开一个隐私窗口或者使用别的浏览器试试看，可能是浏览器的原因。

**Comment by ning0818** [comment]
> 检查过了，但是代码不会引起该操作，可能是你登录的问题

希望能够详细描述一下

**Comment by ning0818** [comment]
> 开一个隐私窗口或者使用别的浏览器试试看，可能是浏览器的原因。

我换了电脑、浏览器、ip都不好使..................

**Comment by Fgaoxing** [comment]
> > 检查过了，但是代码不会引起该操作，可能是你登录的问题
> 
> 希望能够详细描述一下

我检查过了没有Bug

**Comment by Fgaoxing** [comment]
> Refer

应该是你没配置好

**Comment by Fgaoxing** [comment]
从开数据库

**Comment by ning0818** [comment]
> 从开数据库

我要崩溃了
要不干脆不用了

**Comment by Jeamorg** [comment]
> > 从开数据库
> 
> 我要崩溃了
> 要不干脆不用了

我是按照这个教程搭建的，要不你去看看你 qexo 哪里配错了，如果没配错那就是你的域名解析有问题
https://jeam.org/b9fa919f

**Comment by ning0818** [comment]
> > > 从开数据库
> > 
> > 
> > 我要崩溃了
> > 要不干脆不用了
> 
> 我是按照这个教程搭建的，要不你去看看你 qexo 哪里配错了，如果没配错那就是你的域名解析有问题 https://jeam.org/b9fa919f

哎好吧 
我是用官方文档弄的
