### ISSUE TITLE
When the Firefox browser accesses qexo and uses the form, there is no small frame for adjusting the form

### ISSUE THREAD

**Issue by cyolc932** [Qexo/Qexo#416]
### Qexo 版本

v2.4.3

### 平台

Vercel & Vercel

### 问题描述

When the Firefox browser accesses qexo and uses the form, there is no small frame for adjusting the form

### 截图

![](https://github.com/Qexo/Qexo/assets/46415893/0c51e1be-cdf4-4b8e-9873-19a3c66c8b9a)

**Comment by Fgaoxing** [comment]
Hello, this is not a bug in Qexo. The editor is Vditor. If you believe there is a bug, please submit an Issue to this repository：https://github.com/Vanessa219/vditor

**Comment by cyolc932** [comment]
这是来自邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
