### ISSUE TITLE
重命名

### ISSUE THREAD

**Issue by felixesintot** [Qexo/Qexo#418]
### Qexo 版本

v2.4.3

### 平台

MongoDB & Vercel

### 问题描述

没法进行文件重命名

### 复现链接

https://edit.felixesintot.top
没有游客模式，密码不能告诉你QWQ

### 截图

![image](https://github.com/Qexo/Qexo/assets/98651799/4bf063cd-a65a-4535-bd63-1f03e6e280d9)

**Comment by am-abudu** [comment]
已经在Dev中添加
