### ISSUE TITLE
在配置Github图床后仍然无法显示图片和进行上传操作

### ISSUE THREAD

**Issue by LostPear** [Qexo/Qexo#421]
### Qexo 版本

v2.8.1

### 平台

MongoDB & Vercel

### 问题描述

如图，在后台配置好Github图床后，主页仍然无法显示仓库内的图片和进行上传操作等，使用相同配置在PicGO上可以正常进行操作。请问我是否遗漏了一些步骤，或者为程序bug？

### 截图

<img width="1018" alt="屏幕截图 2023-07-30 124532" src="https://github.com/Qexo/Qexo/assets/64293899/68cce114-8f36-41c8-a881-ca6c65d7a938">
<img width="1073" alt="屏幕截图 2023-07-30 124648" src="https://github.com/Qexo/Qexo/assets/64293899/dca36761-1d38-4729-90b2-bf879c6b8b1f">

**Comment by am-abudu** [comment]
图片需要在文章编辑页面上传

**Comment by am-abudu** [comment]
自定义域名 保存路径的填写逻辑与Picgo不同。请参考Qexo文档进行修改
