### ISSUE TITLE
编辑文章 Error 500

### ISSUE THREAD

**Issue by ShengQiBaoZao** [Qexo/Qexo#424]
### Qexo 版本

v2.8.1

### 平台

MongoDB & Vercel

### 问题描述

部署Qexo只有四个月左右，先前部署后测试一切都正常(包括编辑文章功能)，然后更新过两次版本，一直没使用编辑文章的功能，今天点击编辑文章，报错：
" 错误! Error 500
报错信息：'datetime.date' object has no attribute 'astimezone' "
其余功能应该都正常，我也清除了缓存，检查了数据库和github秘钥，在Vercel进行了ReDeploy，但还是这样报错，请问应该如何修改，我在 /setting 和 /advanced 里没找到所提示这两个属性

### 复现链接

bk.shengqibaozao.eu.org
普通账户：visitor     密码：123456

### 截图

![1](https://github.com/Qexo/Qexo/assets/99303427/bff38e36-a27f-44df-8dd1-d2dbaecdda7e)

**Comment by Fgaoxing** [comment]
应该是包错误，代码的问题，等吧

**Comment by am-abudu** [comment]
是否有functions的记录，让我知道是哪一行的代码问题

**Comment by Fgaoxing** [comment]
@am-abudu 建议以后改成traceback报错，比较详细

**Comment by Fgaoxing** [comment]
@am-abudu 应该是https://github.com/Qexo/Qexo/blob/d8542d10967ca305d8ca95f85eadd16d2f8f6617/hexoweb/functions.py#L296

**Comment by Fgaoxing** [comment]
或者https://github.com/Qexo/Qexo/blob/d8542d10967ca305d8ca95f85eadd16d2f8f6617/hexoweb/functions.py#L282

**Comment by ShengQiBaoZao** [comment]
> 是否有functions的记录，让我知道是哪一行的代码问题

您好，我应该给您哪里的截图，functions 是指 Vercel 的 functions 记录吗，我不是专业的所以不太清楚QAQ

**Comment by am-abudu** [comment]
我反复检查，但这不应该出现。你或许可以尝试一下Dev分支？

如果还是没有帮助，请给我Vercel functions内的日志，以及告诉我别的文章是否会出现这个问题

**Comment by ShengQiBaoZao** [comment]
我更新到了dev分支，但问题还是存在。编辑任何文章都会出现该问题。
下面是Vercel的日志内容，以及编辑文章报错信息的日志条目：
![1](https://github.com/Qexo/Qexo/assets/99303427/1cc82c69-43df-4b85-9bc6-b11dceb69cd9)
![2](https://github.com/Qexo/Qexo/assets/99303427/44c514c7-68ae-4624-ab5f-4f71d4e4ccc4)

目前Qexo的其他功能都正常，友链和说说功能都正常，在跟您反馈问题后两天我重新排布了博客文章的目录，Qexo中文章页面也能正常跟进，只有编辑文章不可使用：
![3](https://github.com/Qexo/Qexo/assets/99303427/3891c5ae-676c-4fe5-b4e4-c36d04bd41ab)

我可以确保于今年3月31日成功部署后可以正常编辑文章，也能顺利发布编辑的文章，此后就处理更新就没有调节过Qexo的设置项并且没有再使用过编辑文章功能（个人习惯了本地编辑再发布），期间只更新Qexo，使用友链和说说功能。
希望以上信息能对您有所帮助，如果属实是我个人原因导致的错误，那便不必费心了，对我的使用没有太大的影响，劳烦费心

**Comment by am-abudu** [comment]
我需要你提供报错的文章源文件 可以发到我的邮箱 abudulin@foxmail.com

**Comment by ShengQiBaoZao** [comment]
好的，我的博客可以在我的github仓库看到
https://github.com/ShengQiBaoZao/shengqibaozao_blog/tree/hexo
hexo分支就是 hexo 博客的生成前文件(包括配置文件)，该分支下的 /source/_posts/ 目录下都是博客的文章

**Comment by ShengQiBaoZao** [comment]
为方便您测试，我将Qexo后台的管理员账户的账号密码发您邮箱了

**Comment by ShengQiBaoZao** [comment]
经过回退测试，Qexo 2.7.0版本下，编辑文章功能正常使用，目前后台回退至2.7.0，如您需要测试可以自行更新测试

**Comment by am-abudu** [comment]
我做了修改。请检查Dev分支是否已经可用
