### ISSUE TITLE
七牛云的图床貌似没法用

### ISSUE THREAD

**Issue by momo54181** [Qexo/Qexo#425]
### Qexo 版本

v2.4.3

### 平台

Vercel

### 问题描述

上传失败
lueError('Invalid endpoint: s3地址')

### 截图

![image](https://github.com/Qexo/Qexo/assets/79344479/9e14ca4f-5253-4fed-b660-240fab0a0307)

**Comment by am-abudu** [comment]
请给出具体配置（抹除敏感信息）

**Comment by am-abudu** [comment]
请确认问题是否依然存在

**Comment by momo54181** [comment]
问题已解决
