### ISSUE TITLE
检测到主题，检测不到主题配置

### ISSUE THREAD

**Issue by gilGAMEsh002** [Qexo/Qexo#426]
### Qexo 版本

v2.8.1

### 平台

Mongo & Vercel

### 问题描述

检测不到主题配置文件，但_config.fluid.yaml确实是在根目录下的。强制部署之后，似乎一切正常

### 截图

![image](https://github.com/Qexo/Qexo/assets/111326611/3fabdc90-51da-427e-9a05-20a8de7afe8c)
![image](https://github.com/Qexo/Qexo/assets/111326611/438c5dd1-7101-4ba7-948c-1e60ae16a6b2)

**Comment by xixi-zhao** [comment]
这个问题似乎现在仍然存在

**Comment by am-abudu** [comment]
在新的版本中将删除该校验
