### ISSUE TITLE
[DEV] 使用master分支升级dev分支后登录报错error500

### ISSUE THREAD

**Issue by Qian-F** [Qexo/Qexo#427]
### Qexo 版本

最新master升级最新dev

### 平台

vercel + SupaBase

### 问题描述

**有很高概率复现**
从头走一遍master分支的部署方法
↓
点击更新dev通道
↓
登录
↓
error500

### 复现链接

https://qexo-qianfeng.vercel.app/

### 截图

![TabTip_0g9Ee6NZ9o](https://github.com/Qexo/Qexo/assets/111696321/2b0a0a4a-bb99-4db4-bee6-8390b4f92568)

**Comment by Qian-F** [comment]
有趣的是可以通过高级设置/advanced.html页面进入后台，但是只要点击主页就会error500

**Comment by Qian-F** [comment]
友链和说说也无法识别

**Comment by am-abudu** [comment]
目前找到的原因是PostModel数据库未成功Migrate。因为主页运用到了这个新特性所以无法打开。类似的有文章的保存

**Comment by am-abudu** [comment]
正在与迁移程序斗智斗勇...

**Comment by Qian-F** [comment]
烦请解决 我打算先回退master
还有个问题是貌似dev分组织无法正常更新

**Comment by Qian-F** [comment]
> 友链和说说也无法识别

好像已存在的是无法识别的
之前可以在Qexo上看到识别到的说说和友链

**Comment by am-abudu** [comment]
> > 友链和说说也无法识别
> 
> 好像已存在的是无法识别的 之前可以在Qexo上看到识别到的说说和友链

这个问题我没有遇到，并且这方面没有做修改。你可以F12看一下报错

**Comment by Qian-F** [comment]
这个很可能是我的问题 先解决主页error500吧.....

**Comment by Qian-F** [comment]
已推送 自动部署后反馈

**Comment by Qian-F** [comment]
可以正常进入 但是这个问题我还是需要反馈一下
![Screenshot_2023-08-17-21-05-42-95_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/Qexo/Qexo/assets/111696321/dfa1c8dc-5689-4138-b42c-c6a7b90bd926)

![Screenshot_2023-08-17-21-05-38-44_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/Qexo/Qexo/assets/111696321/2ae4ecf0-ed1b-4d30-a1f7-88662e963943)

说说可能是我的问题 但是这个（摊手

**Comment by Qian-F** [comment]
![Screenshot_2023-08-17-21-16-36-17_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/Qexo/Qexo/assets/111696321/e26a4776-471f-4920-a076-c7237de9e247)

可能是路径有问题？

**Comment by Qian-F** [comment]
应该是source/_data/link.yml吧

**Comment by am-abudu** [comment]
你这个link.yml跟Qexo的友情链接没有半毛钱关系。
See: https://www.oplog.cn/qexo/exts/flinks.html

**Comment by Qian-F** [comment]
配置这里是能正常看到内容的
![Screenshot_2023-08-17-21-18-56-02_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/Qexo/Qexo/assets/111696321/83f6dc45-5bbd-46aa-961f-8c12cd6cc86e)

**Comment by Qian-F** [comment]
对不起 我的问题

**Comment by Qian-F** [comment]
我才反应过来
