### ISSUE TITLE
dev 版本发布不了新文章

### ISSUE THREAD

**Issue by Jeamorg** [Qexo/Qexo#428]
### Qexo 版本

v3.0.0

### 平台

Planetscale & Vercel

### 问题描述

点击发布就会出现以下错误
IntegrityError(1048, 'target: xxx.-.primary: vttablet: rpc error: code = InvalidArgument desc = Column \'path\' cannot be null (errno 1048) (sqlstate 23000) (CallerID: 6nlelckr5mcipai4414j): Sql: "insert into hexoweb_postmodel(id, title, filename, `path`, `date`, front_matter, `status`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, null, :vtg4 /* FLOAT64 */, :vtg5 /* VARCHAR */, :vtg6 /* INT64 */)", BindVars: {REDACTED}')

### 截图

无

**Comment by am-abudu** [comment]
已修复
