### ISSUE TITLE
程序错误500

### ISSUE THREAD

**Issue by felixesintot** [Qexo/Qexo#432]
### Qexo 版本

v3.0.0

### 平台

MongoDB & Vercel

### 问题描述

![image](https://github.com/Qexo/Qexo/assets/98651799/e435f093-cb98-4c65-9d82-560ac31f21ae)
登录后就这样，重装也没用

### 复现链接

https://edit.felixesintot.top

### 截图

rt

**Comment by am-abudu** [comment]
因为之前的数据库结构过于混乱...若出现这个问题我只能建议你回退版本进行备份然后删除数据库重新部署

**Comment by felixesintot** [comment]
换数据库后暂时好了，不打扰了
