### ISSUE TITLE
反应问题

### ISSUE THREAD

**Issue by xiatianPE** [Qexo/Qexo#434]
### Qexo 版本

3.0

### 平台

vercel

### 问题描述

点击该按钮反应迟钝，或者直接点击无反应

**Comment by xiatianPE** [comment]
![19AF363A-B0F6-453A-9B10-D15CA2C1BC82](https://github.com/Qexo/Qexo/assets/121849812/2d4c360c-cfe2-496d-9335-f6761c4382dd)

**Comment by am-abudu** [comment]
我这里是正常的。你可以尝试更新版本或检查本地问题

**Comment by xiatianPE** [comment]
> 我这里是正常的。你可以尝试更新版本或检查本地问题

目前已经好了，但是我想插入视频在文章，有没有快捷的方法
