### ISSUE TITLE
短链接配置

### ISSUE THREAD

**Issue by Jeamorg** [Qexo/Qexo#436]
### Qexo 版本

3.0.0

### 平台

Planetscale & Vercel

### 问题描述

设置里的`短链接配置（abbrlink）`似乎无效了，年初的时候还能自动生成

### 复现链接

无

### 截图

![图片](https://github.com/Qexo/Qexo/assets/93057377/23ca448b-15b9-4567-bfbc-1524d747b971)
![图片](https://github.com/Qexo/Qexo/assets/93057377/52031df2-fd59-4739-b009-6ca65d2e073c)

**Comment by am-abudu** [comment]
我这里测试是正常的，请参考文档修改文章模板。之后可能会进行优化

**Comment by Jeamorg** [comment]
十分抱歉，这几天比较忙没有看到回复，已经看文档解决了
