### ISSUE TITLE
读取配置文件时，文件名显示错误

### ISSUE THREAD

**Issue by zhoubuzhiba** [Qexo/Qexo#441]
### Qexo 版本

v3.0.0

### 平台

MongoDB & Vercel

### 问题描述

“配置”页面读取配置文件时将"config.toml"显示为“onfig.toml”

### 截图

![screenshot](https://github.com/Qexo/Qexo/assets/78309660/c112ec87-50f8-46aa-a453-18eef4553551)

**Comment by am-abudu** [comment]
请现在尝试Dev分支

**Comment by zhoubuzhiba** [comment]
谢谢大佬
