### ISSUE TITLE
更新报错KeyError("deployments")

### ISSUE THREAD

**Issue by HaoTian22** [Qexo/Qexo#442]
### Qexo 版本

v2.8.1

### 平台

MongoDB & Vercel

### 问题描述

尝试更新3.0.0的时候出现如图报错

### 截图

![Screenshot_2023-08-28-08-59-31-983_com microsoft emmx-edit](https://github.com/Qexo/Qexo/assets/48882584/68e75b20-45b7-4ca1-8af5-89ed2b63c57c)

**Comment by am-abudu** [comment]
#358

**Comment by HaoTian22** [comment]
好的，是ID自动填了qexo上去
