### ISSUE TITLE
文章更新时间错误

### ISSUE THREAD

**Issue by momo54181** [Qexo/Qexo#444]
### Qexo 版本

v3.0.0

### 平台

Vercel

### 问题描述

文章的更新时间永远是今天
https://[blog.mocn.top/sitemap.xml](https://blog.mocn.top/sitemap.xml)

![image](https://github.com/Qexo/Qexo/assets/79344479/a7a1c125-c3fa-4f7b-8cc6-7123238a41b3)
![image](https://github.com/Qexo/Qexo/assets/79344479/bd686ed4-dc03-436c-8357-ceefcf0fe59f)

### 复现链接

Not

### 截图

.

**Comment by momo54181** [comment]
希望可以改为 2022-12-12 19:02:24 这种格式的时间

**Comment by Jeamorg** [comment]
hexo 确实有这方面的问题，我通过 fork 将时间格式回退到以前了

![图片](https://github.com/Qexo/Qexo/assets/93057377/89ba2000-87ee-497e-97b1-ecc539792758)

**Comment by am-abudu** [comment]
我现在需要知道一种同时满足Hexo和Hugo的格式。这个格式对于Hugo有时区问题。对于我的Hexo，这是正常工作的，你可以检查一下moment.js的版本

**Comment by Jeamorg** [comment]
hexo 和 hugo 都支持设置 `timezone`
<br>

hugo 相关

![图片](https://github.com/Qexo/Qexo/assets/93057377/6658dfca-e88a-474d-a090-2e89ff79900f)

hexo 相关

![图片](https://github.com/Qexo/Qexo/assets/93057377/ead2f5b7-ce5b-4713-8db6-a0f875cc5a4f)

**Comment by yzl3014** [comment]
### 相同问题
在[Fliud](https://github.com/fluid-dev/hexo-theme-fluid)最新版中，如果使用Qexo提供的时间发布文章，则页面上的更新时间永远是"几秒钟前"。

### 原因
这应该是因为时间的时分秒没有补0，即将 1:0:0 补全成 01:00:00 (凌晨一点)。
这导致JS根本无法解析这个时间，从而影响到后面的处理。我刚刚用同样的时间文本进行了在线测试，右下方是运行结果。
![](https://github.com/Qexo/Qexo/assets/79385954/c0aae4c2-6b13-4629-b7bb-7e0f2c9c6310)

@am-abudu 这可能是问题的根本

**Comment by Jeamorg** [comment]
> ### 相同问题
> 
> 在[Fliud](https://github.com/fluid-dev/hexo-theme-fluid)最新版中，如果使用Qexo提供的时间发布文章，则页面上的更新时间永远是"几秒钟前"。
> ### 原因
> 
> 这应该是因为时间的时分秒没有补0，即将 1:0:0 补全成 01:00:00 (凌晨一点)。 这导致JS根本无法解析这个时间，从而影响到后面的处理。我刚刚用同样的时间文本进行了在线测试，右下方是运行结果。 ![](https://user-images.githubusercontent.com/79385954/266761923-c0aae4c2-6b13-4629-b7bb-7e0f2c9c6310.png)
> 
> @am-abudu 这可能是问题的根本

这个主题我以前用过，那时候还没有 Qexo 也会出现这个问题（后续我找出并解决了），而且即便 Qexo 改成 00:00:00 的时间格式也许也还是会出现你所述的问题（你应该在 fluid 提这个issue）。

**Comment by am-abudu** [comment]
请现在尝试Dev分支

**Comment by Jeamorg** [comment]
已测试，该问题已修复

**Comment by momo54181** [comment]
已测试，该问题已被修复
