### ISSUE TITLE
Vercel部署后对登录异常

### ISSUE THREAD

**Issue by DOUZHANSHENGYANG** [Qexo/Qexo#445]
### Qexo 版本

v3.0

### 平台

Mongo&Vercel

### 问题描述

vercel部署后输入完账户密码后就突然这样，第一次部署后是可以的，但突然就登不进去了

### 复现链接

https://blog-dashboard-afgpzpueg-douzhanshengyang.vercel.app/

### 截图

<img width="1280" alt="Snipaste_2023-08-31_12-54-53" src="https://github.com/Qexo/Qexo/assets/92624374/25709584-5785-4b72-98cd-c2af916a4a15">

**Comment by am-abudu** [comment]
我需要日志，这个界面什么都没有
