### ISSUE TITLE
python3 manage.py makemigrations 报错

### ISSUE THREAD

**Issue by hyy34** [Qexo/Qexo#446]
### Qexo 版本

v3.0.0

### 平台

MySQL 本地

### 问题描述

root@23-8-20841:/www/wwwroot/example.com/Qexo# pip3 install -r requirements.txt
Collecting Django==3.2.18 (from -r requirements.txt (line 1))
  Using cached Django-3.2.18-py3-none-any.whl (7.9 MB)
Requirement already satisfied: PyMySQL==1.0.2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.0.2)
Requirement already satisfied: boto3==1.26.94 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (1.26.94)
Requirement already satisfied: requests==2.28.2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (2.28.2)
Requirement already satisfied: PyGithub==1.58.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (1.58.1)
Requirement already satisfied: python-gitlab==3.13.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (3.13.0)
Requirement already satisfied: html2text==2020.1.16 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (2020.1.16)
Requirement already satisfied: PyYAML==6.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (6.0)
Requirement already satisfied: urllib3==1.26.15 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (1.26.15)
Requirement already satisfied: Markdown==3.4.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (3.4.1)
Requirement already satisfied: djongo==1.3.6 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (1.3.6)
Requirement already satisfied: django-cors-headers==3.14.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (3.14.0)
Requirement already satisfied: pymongo==3.13.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (3.13.0)
Requirement already satisfied: dnspython==2.2.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (2.2.1)
Requirement already satisfied: sqlparse==0.2.4 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (0.2.4)
Requirement already satisfied: psycopg2-binary==2.9.5 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 16)) (2.9.5)
Requirement already satisfied: cryptography==39.0.2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 17)) (39.0.2)
Requirement already satisfied: pyopenssl==23.0.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 18)) (23.0.0)
Requirement already satisfied: oss2==2.17.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 19)) (2.17.0)
Requirement already satisfied: beautifulsoup4==4.11.2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 20)) (4.11.2)
Requirement already satisfied: asgiref<4,>=3.3.2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from Django==3.2.18->-r requirements.txt (line 1)) (3.7.2)
Requirement already satisfied: pytz in /www/server/panel/pyenv/lib/python3.7/site-packages (from Django==3.2.18->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: botocore<1.30.0,>=1.29.94 in /www/server/panel/pyenv/lib/python3.7/site-packages (from boto3==1.26.94->-r requirements.txt (line 3)) (1.29.165)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from boto3==1.26.94->-r requirements.txt (line 3)) (0.10.0)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from boto3==1.26.94->-r requirements.txt (line 3)) (0.6.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from requests==2.28.2->-r requirements.txt (line 4)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /www/server/panel/pyenv/lib/python3.7/site-packages (from requests==2.28.2->-r requirements.txt (line 4)) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /www/server/panel/pyenv/lib/python3.7/site-packages (from requests==2.28.2->-r requirements.txt (line 4)) (2022.12.7)
Requirement already satisfied: deprecated in /www/server/panel/pyenv/lib/python3.7/site-packages (from PyGithub==1.58.1->-r requirements.txt (line 5)) (1.2.14)
Requirement already satisfied: pyjwt[crypto]>=2.4.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from PyGithub==1.58.1->-r requirements.txt (line 5)) (2.8.0)
Requirement already satisfied: pynacl>=1.4.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from PyGithub==1.58.1->-r requirements.txt (line 5)) (1.5.0)
Requirement already satisfied: requests-toolbelt>=0.10.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from python-gitlab==3.13.0->-r requirements.txt (line 6)) (1.0.0)
Requirement already satisfied: importlib-metadata>=4.4 in /www/server/panel/pyenv/lib/python3.7/site-packages (from Markdown==3.4.1->-r requirements.txt (line 10)) (6.6.0)
Requirement already satisfied: cffi>=1.12 in /www/server/panel/pyenv/lib/python3.7/site-packages (from cryptography==39.0.2->-r requirements.txt (line 17)) (1.15.1)
Requirement already satisfied: crcmod>=1.7 in /www/server/panel/pyenv/lib/python3.7/site-packages (from oss2==2.17.0->-r requirements.txt (line 19)) (1.7)
Requirement already satisfied: pycryptodome>=3.4.7 in /www/server/panel/pyenv/lib/python3.7/site-packages (from oss2==2.17.0->-r requirements.txt (line 19)) (3.17)
Requirement already satisfied: aliyun-python-sdk-kms>=2.4.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from oss2==2.17.0->-r requirements.txt (line 19)) (2.16.0)
Requirement already satisfied: aliyun-python-sdk-core>=2.13.12 in /www/server/panel/pyenv/lib/python3.7/site-packages (from oss2==2.17.0->-r requirements.txt (line 19)) (2.13.36)
Requirement already satisfied: six in /www/server/panel/pyenv/lib/python3.7/site-packages (from oss2==2.17.0->-r requirements.txt (line 19)) (1.16.0)
Requirement already satisfied: soupsieve>1.2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from beautifulsoup4==4.11.2->-r requirements.txt (line 20)) (2.4.1)
Requirement already satisfied: typing-extensions>=4 in /www/server/panel/pyenv/lib/python3.7/site-packages (from asgiref<4,>=3.3.2->Django==3.2.18->-r requirements.txt (line 1)) (4.5.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from botocore<1.30.0,>=1.29.94->boto3==1.26.94->-r requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: pycparser in /www/server/panel/pyenv/lib/python3.7/site-packages (from cffi>=1.12->cryptography==39.0.2->-r requirements.txt (line 17)) (2.21)
Requirement already satisfied: zipp>=0.5 in /www/server/panel/pyenv/lib/python3.7/site-packages (from importlib-metadata>=4.4->Markdown==3.4.1->-r requirements.txt (line 10)) (3.15.0)
Requirement already satisfied: wrapt<2,>=1.10 in /www/server/panel/pyenv/lib/python3.7/site-packages (from deprecated->PyGithub==1.58.1->-r requirements.txt (line 5)) (1.15.0)
Installing collected packages: Django
  Attempting uninstall: Django
    Found existing installation: Django 3.2.20
    Uninstalling Django-3.2.20:
      Successfully uninstalled Django-3.2.20
Successfully installed Django-3.2.18
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@23-8-20841:/www/wwwroot/example.com/Qexo# python3 manage.py makemigrations
Traceback (most recent call last):
  File "/www/wwwroot/example.com/Qexo/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/www/wwwroot/example.com/Qexo/manage.py", line 22, in <module>
    main()
  File "/www/wwwroot/example.com/Qexo/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
root@23-8-20841:/www/wwwroot/example.com/Qexo# 

### 截图

![image](https://github.com/Qexo/Qexo/assets/26433019/9d707581-2768-4a34-882a-ed3aff32e3ce)

**Comment by hyy34** [comment]
我使用宝塔部署的，请问有宝塔的教程吗？？

**Comment by am-abudu** [comment]
你的requirements安装了吗？

**Comment by hyy34** [comment]
> 你的requirements安装了吗？
> 
> 请确认pip命令没有报错

root@23-8-20841:/www/wwwroot/example.com/Qexo# pip3 install -r requirements.txt
Collecting Django==3.2.18 (from -r requirements.txt (line 1))
Using cached Django-3.2.18-py3-none-any.whl (7.9 MB)
Requirement already satisfied: PyMySQL==1.0.2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.0.2)
Requirement already satisfied: boto3==1.26.94 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (1.26.94)
Requirement already satisfied: requests==2.28.2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (2.28.2)
Requirement already satisfied: PyGithub==1.58.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (1.58.1)
Requirement already satisfied: python-gitlab==3.13.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (3.13.0)
Requirement already satisfied: html2text==2020.1.16 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (2020.1.16)
Requirement already satisfied: PyYAML==6.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (6.0)
Requirement already satisfied: urllib3==1.26.15 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (1.26.15)
Requirement already satisfied: Markdown==3.4.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (3.4.1)
Requirement already satisfied: djongo==1.3.6 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (1.3.6)
Requirement already satisfied: django-cors-headers==3.14.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (3.14.0)
Requirement already satisfied: pymongo==3.13.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (3.13.0)
Requirement already satisfied: dnspython==2.2.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (2.2.1)
Requirement already satisfied: sqlparse==0.2.4 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (0.2.4)
Requirement already satisfied: psycopg2-binary==2.9.5 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 16)) (2.9.5)
Requirement already satisfied: cryptography==39.0.2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 17)) (39.0.2)
Requirement already satisfied: pyopenssl==23.0.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 18)) (23.0.0)
Requirement already satisfied: oss2==2.17.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 19)) (2.17.0)
Requirement already satisfied: beautifulsoup4==4.11.2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from -r requirements.txt (line 20)) (4.11.2)
Requirement already satisfied: asgiref<4,>=3.3.2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from Django==3.2.18->-r requirements.txt (line 1)) (3.7.2)
Requirement already satisfied: pytz in /www/server/panel/pyenv/lib/python3.7/site-packages (from Django==3.2.18->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: botocore<1.30.0,>=1.29.94 in /www/server/panel/pyenv/lib/python3.7/site-packages (from boto3==1.26.94->-r requirements.txt (line 3)) (1.29.165)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from boto3==1.26.94->-r requirements.txt (line 3)) (0.10.0)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from boto3==1.26.94->-r requirements.txt (line 3)) (0.6.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from requests==2.28.2->-r requirements.txt (line 4)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /www/server/panel/pyenv/lib/python3.7/site-packages (from requests==2.28.2->-r requirements.txt (line 4)) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /www/server/panel/pyenv/lib/python3.7/site-packages (from requests==2.28.2->-r requirements.txt (line 4)) (2022.12.7)
Requirement already satisfied: deprecated in /www/server/panel/pyenv/lib/python3.7/site-packages (from PyGithub==1.58.1->-r requirements.txt (line 5)) (1.2.14)
Requirement already satisfied: pyjwt[crypto]>=2.4.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from PyGithub==1.58.1->-r requirements.txt (line 5)) (2.8.0)
Requirement already satisfied: pynacl>=1.4.0 in /www/server/panel/pyenv/lib/python3.7/site-packages (from PyGithub==1.58.1->-r requirements.txt (line 5)) (1.5.0)
Requirement already satisfied: requests-toolbelt>=0.10.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from python-gitlab==3.13.0->-r requirements.txt (line 6)) (1.0.0)
Requirement already satisfied: importlib-metadata>=4.4 in /www/server/panel/pyenv/lib/python3.7/site-packages (from Markdown==3.4.1->-r requirements.txt (line 10)) (6.6.0)
Requirement already satisfied: cffi>=1.12 in /www/server/panel/pyenv/lib/python3.7/site-packages (from cryptography==39.0.2->-r requirements.txt (line 17)) (1.15.1)
Requirement already satisfied: crcmod>=1.7 in /www/server/panel/pyenv/lib/python3.7/site-packages (from oss2==2.17.0->-r requirements.txt (line 19)) (1.7)
Requirement already satisfied: pycryptodome>=3.4.7 in /www/server/panel/pyenv/lib/python3.7/site-packages (from oss2==2.17.0->-r requirements.txt (line 19)) (3.17)
Requirement already satisfied: aliyun-python-sdk-kms>=2.4.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from oss2==2.17.0->-r requirements.txt (line 19)) (2.16.0)
Requirement already satisfied: aliyun-python-sdk-core>=2.13.12 in /www/server/panel/pyenv/lib/python3.7/site-packages (from oss2==2.17.0->-r requirements.txt (line 19)) (2.13.36)
Requirement already satisfied: six in /www/server/panel/pyenv/lib/python3.7/site-packages (from oss2==2.17.0->-r requirements.txt (line 19)) (1.16.0)
Requirement already satisfied: soupsieve>1.2 in /www/server/panel/pyenv/lib/python3.7/site-packages (from beautifulsoup4==4.11.2->-r requirements.txt (line 20)) (2.4.1)
Requirement already satisfied: typing-extensions>=4 in /www/server/panel/pyenv/lib/python3.7/site-packages (from asgiref<4,>=3.3.2->Django==3.2.18->-r requirements.txt (line 1)) (4.5.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /www/server/panel/pyenv/lib/python3.7/site-packages (from botocore<1.30.0,>=1.29.94->boto3==1.26.94->-r requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: pycparser in /www/server/panel/pyenv/lib/python3.7/site-packages (from cffi>=1.12->cryptography==39.0.2->-r requirements.txt (line 17)) (2.21)
Requirement already satisfied: zipp>=0.5 in /www/server/panel/pyenv/lib/python3.7/site-packages (from importlib-metadata>=4.4->Markdown==3.4.1->-r requirements.txt (line 10)) (3.15.0)
Requirement already satisfied: wrapt<2,>=1.10 in /www/server/panel/pyenv/lib/python3.7/site-packages (from deprecated->PyGithub==1.58.1->-r requirements.txt (line 5)) (1.15.0)
Installing collected packages: Django
Attempting uninstall: Django
Found existing installation: Django 3.2.20
Uninstalling Django-3.2.20:
Successfully uninstalled Django-3.2.20
Successfully installed Django-3.2.18
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

也不知道安没安装上，没安装上也不清楚是啥原因。。

**Comment by am-abudu** [comment]
可能是你安装的Python太多了，与Pip不匹配。你需要重新配置你的本地环境

**Comment by hyy34** [comment]
> 可能是你安装的Python太多了，与Pip不匹配。你需要重新配置你的本地环境

额。不用宝塔不习惯啊。

**Comment by am-abudu** [comment]
你只需要使你的Pip同Python匹配即可。这并不难，也与宝塔不冲突
