### ISSUE TITLE
新版本前端问题

### ISSUE THREAD

**Issue by Fgaoxing** [Qexo/Qexo#449]
### Qexo 版本

latest

### 平台

All

### 问题描述

![image](https://github.com/Qexo/Qexo/assets/92655031/43e98fff-c90f-4f95-91a1-919cc8677475)
无法清理无效友链，
![image](https://github.com/Qexo/Qexo/assets/92655031/087835e2-6962-42b1-ae28-9db889c4846b)
没有清理按钮
![image](https://github.com/Qexo/Qexo/assets/92655031/c51bb8f3-5c6d-4ef9-badd-de268aab97fb)
按钮没居中，但有的有

### 截图

无

**Comment by am-abudu** [comment]
关于清除友链，可以前往云端命令库。

关于第二个问题，刚刚的推送或许有帮助。

**Comment by Fgaoxing** [comment]
@am-abudu 但是这回导致使用起来比较困难

**Comment by am-abudu** [comment]
我认为这个功能并不常用，不需要放在随时可用的地方
