### ISSUE TITLE
后台保存草稿后报错

### ISSUE THREAD

**Issue by Umpire2018** [Qexo/Qexo#454]
### Qexo 版本

3.0.0

### 平台

PostgreSQL/Vercel

### 问题描述

![image](https://github.com/Qexo/Qexo/assets/138990495/d55f5ee5-27a3-4ae6-860f-663af28889dd)

在点击保存后，发生了错误
```
IntegrityError('null value in column "path" of relation "hexoweb_postmodel" violates not-null constraint\nDETAIL: Failing row contains (53e85521-91af-4b5f-adc9-1894f71a4e45, title, 1.md, null, 1695048842.870272, {"title": "title", "date": "2023-09-18T22:53:50.334858+08:00", "..., f).\n')
```
以下是我的源代码项目
![image](https://github.com/Qexo/Qexo/assets/138990495/96348c0b-5fec-4709-b3d3-391951961b56)

发现文章已经被推送
![image](https://github.com/Qexo/Qexo/assets/138990495/afcb37b8-b5bc-4753-b299-d0ed05eddc32)

### 截图

![image](https://github.com/Qexo/Qexo/assets/138990495/09f17908-623e-4ce0-95d5-c2f3faa63f03)

**Comment by Fgaoxing** [comment]
你好请更新到最新DEV分支防止版本已解决问题



在 2023-09-18 23:03:40，"Arno.Edwards" ***@***.***> 写道：

Qexo 版本

3.0.0

平台

PostgreSQL/Vercel

问题描述

在点击保存后，发生了错误

IntegrityError('null value in column "path" of relation "hexoweb_postmodel" violates not-null constraint\nDETAIL: Failing row contains (53e85521-91af-4b5f-adc9-1894f71a4e45, title, 1.md, null, 1695048842.870272, {"title": "title", "date": "2023-09-18T22:53:50.334858+08:00", "..., f).\n')


以下是我的源代码项目


发现文章已经被推送


复现链接

No response

截图

**Comment by Umpire2018** [comment]
@Fgaoxing 
你好，先前的问题已解决。新发现在最近文章一处，无法显示文章标题。
![image](https://github.com/Qexo/Qexo/assets/138990495/67c66323-0473-4e36-b5ea-da4bc8fcaecc)

但随机文章处可以正常显示。
![image](https://github.com/Qexo/Qexo/assets/138990495/37cda5eb-0436-425a-9e29-60cbb764d84f)
