### ISSUE TITLE
初七云cdn用不了

### ISSUE THREAD

**Issue by xiaohao8** [Qexo/Qexo#467]
### Qexo 版本

最新

### 平台

vercel

### 问题描述

cdn改为初七云后，css加载不出来，而且改不回来，按钮没反应

### 复现链接

202271.xyz

### 截图

[![O7zUcG.md.png](https://ooo.0x0.ooo/2023/10/16/O7zUcG.md.png)](https://img.tg/image/O7zUcG)

**Comment by Fgaoxing** [comment]
抱歉，初七的CDN给你带来了不便，我去修，等一段时间吧，目前在给Web框架增加TLS



在 2023-10-16 23:25:46，"Abudu" ***@***.***> 写道：

初七云CDN有问题无法使用。你可以在数据库手动修改CDN_PREV配置项。如果可以使用，请不要随意修改CDN配置
