### ISSUE TITLE
/bin/sh: line 1: hexo clean : command not found

### ISSUE THREAD

**Issue by miaowmint** [Qexo/Qexo#469]
### Qexo 版本

v3.0.0

### 平台

本地部署&sqlite

### 问题描述

同 #419 
当我使用命令行运行hexo相关指令时是正常的
![image](https://github.com/Qexo/Qexo/assets/58991169/a0cb6de9-fa0c-4fc7-8a6d-103345c0ed2b)

，但是qexo部署就会报错

![image](https://github.com/Qexo/Qexo/assets/58991169/50f1fac6-5b0d-4c56-95ad-b29083dbde13)

于是我尝试 `npm i` ，但是错误没有解决
然后我尝试把相关文件注册为全局变量

![image](https://github.com/Qexo/Qexo/assets/58991169/a234ce4a-5bcd-4b4e-91d8-479d751d1525)
![image](https://github.com/Qexo/Qexo/assets/58991169/ebbaef79-c97a-4bb5-8f10-5738c0483741)

但是错误还是没有解决，最后我尝试在自动部署里把 `hexo clean && hexo g` 修改为 `/www/server/nodejs/v18.18.2/bin/hexo clean && /www/server/nodejs/v18.18.2/bin/hexo g` ，这回运行报错

![image](https://github.com/Qexo/Qexo/assets/58991169/a71a6568-cd74-4ce6-863f-10c35d9b65aa)

请问还有其他可能的解决方案吗TvT

### 截图

1

**Comment by cnrenil** [comment]
/绝对路径/hexo generate试试
只有这一条命令，其他删掉

**Comment by am-abudu** [comment]
只能说建议使用完整路径

**Comment by miaowmint** [comment]
> 只能说建议使用完整路径

已经试过使用完整路径了== 
![image](https://github.com/Qexo/Qexo/assets/58991169/543c3d3d-5637-4688-9e52-0d7b88f2ec3a)

**Comment by miaowmint** [comment]
> 只能说建议使用完整路径

我知道了，是这样的，而且不能使用软链接的路径（

**Comment by miaowmint** [comment]
> 只能说建议使用完整路径

使用完整路径最开始还是报错，不过后来又没问题了（
![image](https://github.com/Qexo/Qexo/assets/58991169/080b2760-1178-45f3-94e3-0c2c7f455623)

暂时没有什么问题了，我关issue了
