### ISSUE TITLE
Bug：由于YAML规范的安全解析错误

### ISSUE THREAD

**Issue by cnrenil** [Qexo/Qexo#473]
### Qexo 版本

最新版本

### 平台

本地部署

### 问题描述

![Screenshot_20231104_091814](https://github.com/Qexo/Qexo/assets/110750103/e6ae0c42-d19b-40e2-b85a-1ec20aacb1c7)

如果使用的是较新版本YAML，YAML会阻止带有！！符号的yaml文件
如图所示
在删除！后恢复正常
 #相似的Issue：`#192`

导致的报错提示：未检测到主题
导致的原因：html压缩代码调用的匹配代码造阻止
建议：在文档注明，无需修改代码，需要用户自行修改主题配置，如果需要修改代码，需将代码的SafeLoad改为UnsafeLoad

### 复现链接

参考链接：https://juejin.cn/post/7113939756827803656

### 截图

![Screenshot_20231104_092417](https://github.com/Qexo/Qexo/assets/110750103/bce15e52-4235-406f-a31c-8c02ed4d1bc1)

**Comment by am-abudu** [comment]
已在Dev分支更新
