### ISSUE TITLE
无法在qexo中更新至dev分支

### ISSUE THREAD

**Issue by yangpuzhen** [Qexo/Qexo#475]
### Qexo 版本

v3.0

### 平台

PostgreSQL/SupaBase & vercel

### 问题描述

在保存文件中出现[issue460](https://github.com/Qexo/Qexo/issues/460)的问题，在面板设置中更新至dev分支，在qexo页面提示更新成功，等待部署，但是并没有发生更新的行为
以下为vercel中最新的日志
`[WARNING]	2023-11-04T14:01:34.718Z	38e18dd9-0918-48da-8d2c-841343754d78	开始更新, 使用Vercel方案
[WARNING]	2023-11-04T14:01:34.920Z	38e18dd9-0918-48da-8d2c-841343754d78	下载更新完成, 开始解压
[WARNING]	2023-11-04T14:01:34.954Z	38e18dd9-0918-48da-8d2c-841343754d78	解压完成, 寻找Index目录
[WARNING]	2023-11-04T14:01:34.955Z	38e18dd9-0918-48da-8d2c-841343754d78	找到Index目录: /tmp/Qexo-Qexo-2df12fb
[WARNING]	2023-11-04T14:01:37.417Z	38e18dd9-0918-48da-8d2c-841343754d78	更新完成: {"alias":["blog-yangpuzhen.vercel.app"],"aliasAssigned":false,"automaticAliases":["blog-yangpuzhen.vercel.app"],"bootedAt":1699106496849,"buildingAt":1699106496849,"buildSkipped":false,"createdAt":1699106496849,"creator":{"uid":"5hOhDFFQctNPZmDuuzgArjkS","username":"yangpuzhen"},"id":"dpl_CicouLLgacyM47nk7tRahutS5xkH","lambdas":[{"id":"bld_jgdnkk6wd","createdAt":1699106497215,"entrypoint":".","readyState":"READY","readyStateAt":1699106497215,"output":[]}],"name":"qexo","meta":{},"public":false,"readyState":"QUEUED","regions":["iad1"],"status":"QUEUED","target":"production","type":"LAMBDAS","url":"blog-d1zy9pj2x-yangpuzhen.vercel.app","version":2,"previewCommentsEnabled":true,"aliasAssignedAt":null,"build":{"env":["CI","VERCEL","VERCEL_ENV","TURBO_REMOTE_ONLY","TURBO_RUN_SUMMARY","NX_DAEMON","VERCEL_URL","VERCEL_GIT_PROVIDER","VERCEL_GIT_PREVIOUS_SHA","VERCEL_GIT_REPO_SLUG","VERCEL_GIT_REPO_OWNER","VERCEL_GIT_REPO_ID","VERCEL_GIT_COMMIT_REF","VERCEL_GIT_COMMIT_SHA","VERCEL_GIT_COMMIT_MESSAGE","VERCEL_GIT_COMMIT_AUTHOR_LOGIN","VERCEL_GIT_COMMIT_AUTHOR_NAME","VERCEL_GIT_PULL_REQUEST_ID","VERCEL_TLA_LAUNCHER","VERCEL_DISCOVER_FOLDER_SIZES","VERCEL_NEXT_BUNDLED_SERVER","ENABLE_VC_BUILD","VERCEL_BUILD_OUTPUTS_EDGE_FUNCTION","VERCEL_EDGE_FUNCTIONS_REGIONAL_INVOCATION","VERCEL_EDGE_FUNCTIONS_EMBEDDED_SOURCEMAPS","VERCEL_EDGE_FUNCTIONS_STRICT_MODE","USE_OUTPUT_FOR_EDGE_FUNCTIONS","NEXT_PRIVATE_MULTI_PAYLOAD","VERCEL_RICHER_DEPLOYMENT_OUTPUTS","VERCEL_EDGE_SUSPENSE_CACHE","VERCEL_SERVERLESS_SUSPENSE_CACHE","VERCEL_BUILD_MONOREPO_SUPPORT","VERCEL_USE_NODE_BRIDGE_PRIVATE_LATEST","VERCEL_ENABLE_NODE_COMPATIBILITY","VERCEL_DEPLOYMENT_SKEW_HANDLING","VERCEL_ENCRYPT_DEPLOYMENT_BUILD_ENV","VERCEL_N1_LAMBDA_INVOCATION"]},"builds":[],"createdIn":"sfo1","env":["VERCEL","VERCEL_ENV","TURBO_REMOTE_ONLY","TURBO_RUN_SUMMARY","NX_DAEMON","VERCEL_URL","VERCEL_GIT_PROVIDER","VERCEL_GIT_PREVIOUS_SHA","VERCEL_GIT_REPO_SLUG","VERCEL_GIT_REPO_OWNER","VERCEL_GIT_REPO_ID","VERCEL_GIT_COMMIT_REF","VERCEL_GIT_COMMIT_SHA","VERCEL_GIT_COMMIT_MESSAGE","VERCEL_GIT_COMMIT_AUTHOR_LOGIN","VERCEL_GIT_COMMIT_AUTHOR_NAME","VERCEL_GIT_PULL_REQUEST_ID"],"functions":null,"inspectorUrl":"https://vercel.com/yangpuzhen/qexo/CicouLLgacyM47nk7tRahutS5xkH","isInConcurrentBuildsQueue":false,"ownerId":"5hOhDFFQctNPZmDuuzgArjkS","plan":"hobby","projectId":"prj_l3QgX5yQzVifEUsyWWGHmauZPto9","projectSettings":{"buildCommand":null,"devCommand":null,"framework":"hexo","commandForIgnoringBuildStep":null,"installCommand":null,"outputDirectory":null},"routes":null}
[WARNING]	2023-11-04T14:01:37.417Z	38e18dd9-0918-48da-8d2c-841343754d78	开始删除文件...
[WARNING]	2023-11-04T14:01:37.432Z	38e18dd9-0918-48da-8d2c-841343754d78	保存设置UPDATE_FROM => 3.0.0
`

### 截图

![$3TG5@80}15JZ`~814K%ICA](https://github.com/Qexo/Qexo/assets/61002536/9791d8b7-56c7-4106-b833-5f201321c0f7)
![V9~ZNNUDWXVOQ@({~NV2WPH](https://github.com/Qexo/Qexo/assets/61002536/0de2b953-f29e-449a-82f6-daad627d0c62)

**Comment by am-abudu** [comment]
更新行为只会推送至Vercel 不会同步更新到Github仓库
