### ISSUE TITLE
怎么配置chevereto项目搭建的图床API ？

### ISSUE THREAD

**Issue by 7noemo** [Qexo/Qexo#476]
### Qexo 版本

v3.0.0

### 平台

MongoDB & Vercel

### 问题描述

进行了如下配置后上传图片报错```JSONDecodeError('Expecting value: line 1 column 8 (char 7)')```

### 截图

![image](https://github.com/Qexo/Qexo/assets/103473489/7be67ac2-dea5-4113-91a4-d656b4cf4822)

**Comment by Ljhhhhhh** [comment]
请问这个问题有处理方式了吗，我按文档配置了 sm.ms 图库，遇到了同样的问题

**Comment by am-abudu** [comment]
可以先留空JSON路径查看情况

**Comment by ShwStone** [comment]
#482
