### ISSUE TITLE
根目录error500

### ISSUE THREAD

**Issue by beyond24** [Qexo/Qexo#478]
### Qexo 版本

3.0.0

### 平台

Mongodb & Vercel

### 问题描述

settings.html和advance.html都可以进入，posts.html可以正常编辑文章。
登录后，首页无法进入，error500。
更新，重新部署，重置数据库文件无效

### 截图

![截屏2023-11-21 21 22 14](https://github.com/Qexo/Qexo/assets/67420638/893a6eb7-62e1-4f46-9b27-540464eed16c)

**Comment by Fgaoxing** [comment]
@beyond24 我尝试解决一下

**Comment by Fgaoxing** [comment]
等一会我应该能解决



在 2023-11-21 21:24:53，"beyond24" ***@***.***> 写道：

Qexo 版本

3.0.0

平台

Mongodb & Vercel

问题描述

settings.html和advance.html都可以进入，posts.html可以正常编辑文章。
登录后，首页无法进入，error500。
更新，重新部署，重置数据库文件无效

复现链接

No response

截图

**Comment by am-abudu** [comment]
问题是否解决？

**Comment by beyond24** [comment]
更新版本到3.0.2，未解决
主页error500
![image](https://github.com/Qexo/Qexo/assets/67420638/5247e0c0-63d9-4eff-9bd1-db61e90e65e5)[](url)

**Comment by am-abudu** [comment]
尝试在settings.html界面保存一次服务商配置

**Comment by beyond24** [comment]
> 尝试在settings.html界面保存一次服务商配置

已解决，感谢！
