### ISSUE TITLE
在访问网址初始化的时候就报504错误

### ISSUE THREAD

**Issue by nic519** [Qexo/Qexo#479]
### Qexo 版本

v3.0.0

### 平台

PostgreSQL/Vercel

### 问题描述

首次在vercel部署到github就碰到这个问题：在访问网址初始化的时候就报504错误

### 截图

![image](https://github.com/Qexo/Qexo/assets/2610741/5b43b960-b662-4903-8102-c5355c74dd2e)

**Comment by nic519** [comment]
![image](https://github.com/Qexo/Qexo/assets/2610741/93a5cef0-30db-4982-9bd4-8f602f381fb8)

**Comment by nic519** [comment]
还有一个运行的错误日志：
使用环境变量中的PostgreSQL数据库
using Web Server Gateway Interface (WSGI)
[ERROR]	2023-11-29T19:03:29.233Z	be01efb7-0187-4ec2-8c16-85668e3c0c1e	Provider获取失败, 跳过
_               _ 
/\   | |             | |
/  \  | |__  _   _  __| |_   _ 
/ /\ \ | |_ \| | | |/ _| | | | |
/ ____ \| |_) | |_| | (_| | |_| |
/_/    \_\____/ \____|\____|\____|
当前环境: Vercel

**Comment by am-abudu** [comment]
请先搜索有无已经存在的相同issue
