### ISSUE TITLE
Telegram信息推送问题

### ISSUE THREAD

**Issue by gittyspirit** [Qexo/Qexo#480]
### Qexo 版本

v2.4.3

### 平台

Supabase & Vercel

### 问题描述

只填写api_token和chatid后，消息测试没有问题，但是博客更新后没有任何消息推送。

### 复现链接

https://t.me/spiriteden

### 截图

![Screenshot_20231130_085324_com microsoft emmx_edit_237028533228936](https://github.com/Qexo/Qexo/assets/118084962/44d19a12-c9e8-4c2b-856c-674b096cd6fe)

**Comment by gittyspirit** [comment]
那么他的它的作用是什么？我不太清楚，不好意思

**Comment by am-abudu** [comment]
主要是和友链申请的API配合使用，以及更新提醒
