### ISSUE TITLE
SMMS图床图片上传失败

### ISSUE THREAD

**Issue by xieqifei** [Qexo/Qexo#482]
### Qexo 版本

v3.0.0

### 平台

MySQL and Vercel

### 问题描述

上传图片，响应失败，错误信息为：
{
    "msg": "JSONDecodeError('Expecting value: line 1 column 18 (char 17)')",
    "url": false
}

### 截图

<img width="1133" alt="Screenshot 2023-12-02 at 00 20 28" src="https://github.com/Qexo/Qexo/assets/50683502/42b29200-f1cc-45f0-ae92-e9422aa50059">

**Comment by am-abudu** [comment]
可以先留空JSON路径查看情况

**Comment by ShwStone** [comment]
这个是 json 格式的原因，在冒号还有逗号之后不应该有空格。

@xieqifei
