### ISSUE TITLE
FTP 图床上传的逻辑错误以及其它图床的可能错误

### ISSUE THREAD

**Issue by ShwStone** [Qexo/Qexo#484]
### Qexo 版本

v3.0.1

### 平台

本地部署

### 问题描述

按照 wiki 配置 FTP 上传之后，虽然显示上传成功，但是 FTP 目录下其实是空文件。

我查看了源代码，发现是 `hexoweb/libs/image/providers/ftp.py` 有一个 bug，file 变量是一个 `<class 'django.core.files.uploadedfile.InMemoryUploadedFile'>`，这个类型在调用 read 方法要先调用 open，否则就会读到空文件。

我怀疑 #462 的问题也是如此

### 截图

<img width="282" alt="屏幕截图 2023-12-12 171802" src="https://github.com/Qexo/Qexo/assets/90076553/06307d42-232b-4f02-bbae-09dab49d89a9">

**Comment by ShwStone** [comment]
远程 api 应该也有这样的问题。

还有在向图床发送 post 的时候能不能加入随机生成 `boundary` 呢？

我可能会在有空的时候尝试修复

**Comment by am-abudu** [comment]
在过去似乎还是正常的，或许是某一次库更新的问题？得等我有空了再去修复了。。

**Comment by am-abudu** [comment]
我在刚刚测试了一下，远程API图床是正常的
![image](https://github.com/Qexo/Qexo/assets/51912589/1e77b221-088e-4bb3-897a-8f78263f33a0)

**Comment by am-abudu** [comment]
现在问题应当已经解决
