### ISSUE TITLE
docker file使用python:alpine3.17安装依赖失败

### ISSUE THREAD

**Issue by moyueheng** [Qexo/Qexo#490]
### Qexo 版本

master

### 平台

本地docker build构建镜像

### 问题描述

I failed to install the dependencies when I was using python:alpine3.17 as the base image, and it was tested because python 3.12 would fail to install the dependencies

### 复现链接

Run the following command:
```
docker build -t qexo .
```

## python:alpine3.17 installation dependency failed
![image.png|900](https://tuchuang-1301374207.cos.ap-nanjing.myqcloud.com/img/20231220102029.png)
## python3.12 installation dependency failed
![image.png|900](https://tuchuang-1301374207.cos.ap-nanjing.myqcloud.com/img/20231220103255.png)

**Comment by am-abudu** [comment]
这是 #487 的问题吗

**Comment by moyueheng** [comment]
> 这是 #487 的问题吗

是的
