### ISSUE TITLE
兰空图床最新版api对接不上

### ISSUE THREAD

**Issue by zlemoni** [Qexo/Qexo#491]
### Qexo 版本

3.0.1

### 平台

MongoDB & Vercel

### 问题描述

兰空图床最新版api对接不上，信息填写的都正确，按照兰空图床最新的api填写的

### 截图

![1](https://github.com/Qexo/Qexo/assets/36426590/2547eb53-79ef-4b56-a954-4c594563adfa)
![2](https://github.com/Qexo/Qexo/assets/36426590/f00097b9-35df-421d-81cf-1ef2e53615ce)

**Comment by am-abudu** [comment]
经过我多次测试 应该是{"Authorization":"Bearer 1000|xxx"}中的符号问题、
转换为unicode之后可以明显看出不同
复制的配置，其中空格为%a0而不是普通的空格导致无法正常解析
修改位于Bearer后的空格为正确的空格即可恢复正常
值得注意的是，Content-Type一定不能够设置，因为会与程序自动设置的发生冲突
