### ISSUE TITLE
S3协议在图片上传时，为图片生成的MD5重复

### ISSUE THREAD

**Issue by yzl3014** [Qexo/Qexo#492]
### Qexo 版本

v3.0.1

### 平台

Postgres Database & Vercel

### 问题描述

我在使用七牛云对象存储提供的S3接口，上传是没有问题的。
Qexo后台的图床设置中，将“保存路径”和“自定义域名”中的文件名称改成 `{md5}` 后，**在同一篇文章中，上传第1张图片没有问题，但上传第2张图片时，图片MD5与第1次的冲突**。
后来上传的图片虽然显示上传成功，但是返回的图片都是同一张，除非后缀名与第一次不同。
此问题在上一个正式版本存在。

### 截图

> ![](https://github.com/Qexo/Qexo/assets/79385954/0ede92e6-f854-493b-a3ce-e7d8ec61a8cf)
> 配置正确

> ![](https://github.com/Qexo/Qexo/assets/79385954/3b23c29e-b328-429a-960a-ac0edd3f6c36)
> 图中的两张图片生成的MD5值完全相同，但显然不是同一张图片。

**Comment by am-abudu** [comment]
请尝试dev分支

**Comment by yzl3014** [comment]
更新dev分支后问题解决

**Comment by am-abudu** [comment]
好的 已经推送到master分支 e4bf6a9
