### ISSUE TITLE
lsky-pro图床，如果存在多个储存策略，那么无法通过自定义body选择到对应的策略

### ISSUE THREAD

**Issue by zzy-ac** [Qexo/Qexo#495]
### Qexo 版本

v3.0.2

### 平台

Mongodb&vercel

### 问题描述

自建的lsky-pro图床，如果存在多个储存策略，那么无法通过自定义body内容填写为{"strategy_id":2}选择到对应的策略
如果只有一个策略，且自定义body留空的话是可以上传的。
通过curl是可以正常指定strategy_id并上传的

### 截图

![image](https://github.com/Qexo/Qexo/assets/74285757/1e591976-d7c7-4448-87b7-6336cc81fdf5)
![image](https://github.com/Qexo/Qexo/assets/74285757/2904871d-107f-41b1-80cb-bb71a01a6f33)

**Comment by zzy-ac** [comment]
求助，这里我该怎么填写才行？
{"strategy_id":”2“}也试过了，一样不行

**Comment by am-abudu** [comment]
与这个无关 请使用unicode编码器检查你输入的每一栏内容，查看是否有不符合规范的空格出现
See #491
