### ISSUE TITLE
部署Vercel失败

### ISSUE THREAD

**Issue by weixuna** [Qexo/Qexo#502]
### Qexo 版本

v2.4.3

### 平台

mongdb

### 问题描述

我已经在Environment Variables已经修改环境了，然后到Deployments重新部署还是失败

### 截图

![image](https://github.com/Qexo/Qexo/assets/68503528/cb2f6ee1-d761-423a-a77e-e2d0f516a379)

**Comment by am-abudu** [comment]
Mongodb数据库信息错误。不会配置可以考虑换别的部署方式

**Comment by MartinLiuMingZhi** [comment]
![image](https://github.com/Qexo/Qexo/assets/92780869/0f9f686e-fd28-4354-8553-6af3fdc743b6)
![image](https://github.com/Qexo/Qexo/assets/92780869/3d602892-0853-4407-a305-031b42a46836)
我这个也是差不多一样building的问题，显示python的环境好像
