### ISSUE TITLE
sm.ms图床上传时报错

### ISSUE THREAD

**Issue by lfyszy** [Qexo/Qexo#515]
### Qexo 版本

v3.2.1

### 平台

vercel & vercel

### 问题描述

报错
 `JSONDecodeError('Expecting value: line 1 column 18 (char 17)')`

### 截图

![image](https://github.com/Qexo/Qexo/assets/114333178/6af2743e-b933-4b01-8a6b-888cf582766d)

**Comment by am-abudu** [comment]
你的配置错误

**Comment by lfyszy** [comment]
![image](https://github.com/Qexo/Qexo/assets/114333178/3201f353-5e17-4296-8a68-1dd2e284344f)
但是都按文档里来的呀？

**Comment by Cappuccilo** [comment]
老版本sm.ms图床上传功能正常，更新了3.2.1之后同样出现这个问题，发现配置里多了个`删除 API`的选项，并且默认为undefined，删除或按提示填写该内容后同样报错。
![image](https://github.com/Qexo/Qexo/assets/51392786/2eef48f6-83ec-407b-9e0a-bc6cc8e562cd)

**Comment by am-abudu** [comment]
经过我的测试是正常的，一定是你们的配置出现了问题。

<img width="1115" alt="Snipaste_2024-03-06_23-11-37" src="https://github.com/Qexo/Qexo/assets/51912589/a81b6a46-9562-4bdf-a39a-370eed59c1e0">

可能的错误是：配置中出现了不应该存在的空格（自定义请求头部分，See #491 ）

**Comment by Cappuccilo** [comment]
已解决，经提示检查了自定义请求头，删除冒号后的空格后功能正常。建议[文档](https://www.oplog.cn/qexo/practice/smms.html)这里调整一下删除此空格

**Comment by lfyszy** [comment]
已解决，转unicode码后确实发现有问题
