### ISSUE TITLE
又拍云上传bmp图片提示网络错误？

### ISSUE THREAD

**Issue by im-pzy** [Qexo/Qexo#518]
### Qexo 版本

v3.2.1

### 平台

MongoDB & Vercel

### 问题描述

配置正确，png图片能传，但是bmp上传提示网络错误

### 截图

![QQ截图20240315114610](https://github.com/Qexo/Qexo/assets/53360123/f4ef603c-9c3c-4192-b2e6-6eb4c1c54b3a)

**Comment by am-abudu** [comment]
我需要更多报错信息

**Comment by im-pzy** [comment]
就是在图片页面，点击上传后，右上角弹出上传失败提示框

**Comment by am-abudu** [comment]
目前dev分支有又拍云组件。可以尝试一下
