### ISSUE TITLE
使用 S3 协议删除图片报错

### ISSUE THREAD

**Issue by fstyou** [Qexo/Qexo#520]
### Qexo 版本

v3.2.1

### 平台

Debian 11 x86_64, Python 3.12.0

## 错误  
在设置中使用 S3 协议配置图床，在图片列表中可以正常上传图片和预览图片，  
删除图片时如勾选“删除远程文件”，将会报错：  
```
AttributeError("'s3.Bucket' object has no attribute 'delete_object'")
```
同时日志显示：  
```
ERROR: AttributeError("'s3.Bucket' object has no attribute 'delete_object'")(api.py.delete_img[line:653])
```
## 解决  
在 `hexoweb/libs/image/providers/s3.py` 中，将第 24、25 行
```python
bucket = s3.Bucket(config.get("bucket"))
bucket.delete_object(Key=config.get("path"))
```
删掉，换成
```python
s3.Object(config.get("bucket"), config.get("path")).delete()
```

### 复现链接

https://qexo.example.com/images.html

### 截图

![image](https://github.com/Qexo/Qexo/assets/105190211/449d3b08-b3b9-41d3-a0d5-effcdb987e78)

**Comment by am-abudu** [comment]
你直接pr吧 最近没什么时间
