### ISSUE TITLE
希望能添加图片预览功能，只有一串文件名，管理起来太麻烦了

### ISSUE THREAD

**Issue by mohicai** [Qexo/Qexo#522]
### Qexo 版本

3.2.1

### 平台

postgre & vercel

### 问题描述

希望能添加图片预览功能，只有一串文件名，管理起来太麻烦了

### 截图

/
![19002C2A-6D54-48CB-8AA7-21651C17DA12](https://github.com/Qexo/Qexo/assets/96253815/4de62c85-e3a4-4402-bbc7-527eca1ef3ac)

**Comment by Evans-Cai** [comment]
同感！这里管理图片太麻烦了，而且我发现项目不是spa模式的 每次切换页面都挺慢的，也可能是我服务器带宽小把  哈哈

**Comment by mohicai** [comment]
用vercel部署的挺快的

**Comment by am-abudu** [comment]
或许会在以后的版本引入类似fancybox的模块

**Comment by tetepay** [comment]
![image](https://github.com/Qexo/Qexo/assets/129178480/0df7c4b7-50bf-4442-aa52-0dcd97eca10d)
这是哪里没设置对吗

**Comment by NakanoSanku** [comment]
> ![image](https://private-user-images.githubusercontent.com/129178480/334654268-0df7c4b7-50bf-4442-aa52-0dcd97eca10d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5Nzc5MjksIm5iZiI6MTcxODk3NzYyOSwicGF0aCI6Ii8xMjkxNzg0ODAvMzM0NjU0MjY4LTBkZjdjNGI3LTUwYmYtNDQ0Mi1hYTUyLTBkY2Q5N2VjYTEwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQxMzQ3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGVhM2QxNThhNzY1NTI2YzIwZjc1NDA2NzliZTdiN2ZkZmY1ZjNkMWExY2Y3NTFiODQ3NTE2NTE1ZTRmYTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9ZhlDD-QBCSibKDZO2dQhTupZlsyUERb0i0Dy2HGtPU) 这是哪里没设置对吗

#524

**Comment by NakanoSanku** [comment]
希望能有图片分类类似于文件夹的功能

**Comment by am-abudu** [comment]
现在已经在Dev分支中支持

**Comment by tianpengwan** [comment]
确实 图片文件名不好看

**Comment by am-abudu** [comment]
我可以考虑新增更多的文件名配置项
