### ISSUE TITLE
看报错是说hexo-offline和hexo版本不符合，我需要将hexo降级吗

### ISSUE THREAD

**Issue by weixuna** [Qexo/Qexo#525]
### Qexo 版本

3.2.1

### 平台

vercel

### 问题描述

看报错是说hexo-offline和hexo版本不符合，我需要将hexo降级吗

### 截图

<img width="706" alt="image" src="https://github.com/Qexo/Qexo/assets/68503528/e95201e0-a35d-4198-b5c3-18ef683da162">

**Comment by am-abudu** [comment]
我觉得这个问题与Qexo无关
