### ISSUE TITLE
butterfly主题下页面板块的2个问题

### ISSUE THREAD

**Issue by zxjzxj0010** [Qexo/Qexo#534]
### Qexo 版本

3.2.1

### 平台

vercel

### 问题描述

在页面板块新建页面时，默认创建的是source/<文件名>.md
而在hexo，butterfly主题下，应该为source/<文件名>/index.md才可以正常渲染
另外，二级页面（如source/page/test/index.md）不会再页面板块显示，一级页面正常。

### 截图

在页面板块新建页面时，默认创建的是<文件名>.md
而在hexo，butterfly主题下

**Comment by am-abudu** [comment]
对于第一个问题，你可以在文件名内加上目录
如 pagename/index

对于第二个问题，为了防止超时，设计如此。你可以自行修改config

**Comment by zxjzxj0010** [comment]
ok，谢谢啦
