### ISSUE TITLE
有的页面编辑会报错：'str' object has no attribute 'keys'

### ISSUE THREAD

**Issue by jbeta001** [Qexo/Qexo#540]
### Qexo 版本

v3.2.1

### 平台

mysql+本地部署

### 问题描述

页面编辑或者新增的时候，会提示 'str' object has no attribute 'keys'
不是所有页面都这样，只有个别页面。
检查了MD文件内容也没发现有啥特殊符号之类的

**附一个报错MD文件内容：**

# 羊毛百科

羊毛百科，旨在为更好的服务广大客户和合作伙伴，解决从入门到精通过程中会遇到的常见问题。

> 如果你是想薅点羊毛，初入门槛轻松做到
>
> 如果你是想赚点零花钱，略知一二就能做到
>
> 如果你是想搞个稳定副业，稍加钻研也能实现

---

# 快速前往

更多内容`请点击左下角导航按钮`

> [值得玩的活动](activity/hdjj.md)
>
> [主要银行玩法](bank/wzyh.md)
>
> [酒店集团玩法](hotel/wzjd.md)
>
> [主流航司玩法](airline/wzhk.md)
>
> [卡盟神器用法](start/tool.md)
>
> [卡盟代理指南](agent/jrkm.md)
>
> [各种实用表格](start/form.md)
>
> [卡盟官方商城](https://kmshop.zjkmkj.com/)

---

# 关于卡盟

浙江卡盟由几位资深玩家成立，致力于为广大老铁提供安全、领先、稳定的全方位服务。

> **专业：**资深团队，拥有雄厚资金实力和自有核心业务体系
>
> **专注：**提供最完善的羊毛方案
>
> **口碑：**无忧服务，业内口碑最佳

<img src="https://wiki.zjkmkj.com/media/45.jpeg" width=400 style="zoom: 67%;" />

---

# 联系与支持

##### 一、联系客服，7/24小时无间断服务

<img src="https://wiki.zjkmkj.com/media/202312172341408.png" alt="image-20231217234154296" style="zoom: 50%;" />

##### 二、关注公众号，新鲜羊毛每日推送

<img src="https://wiki.zjkmkj.com/media/1582171524338997-20211214212908596.jpg" width=400 style="zoom: 50%;" />

### 截图

![Uploading 微信图片_20240429103838.png…]()

**Comment by jbeta001** [comment]
已解决

**Comment by am-abudu** [comment]
应该Dev没问题的
