### ISSUE TITLE
提交的时候ERROR:root:KeyError('newer_text')

### ISSUE THREAD

**Issue by clearany** [Qexo/Qexo#550]
### Qexo 版本

v.3.2.1

### 平台

本地

### 问题描述

提交posts的保存发布后不生效，错误日志ERROR:root:KeyError('newer_text')
![image](https://github.com/user-attachments/assets/cefa2aa8-e8c5-485a-b05f-eb059ad08052)

### 截图

![image](https://github.com/user-attachments/assets/7f3b644c-8cd9-4a1f-af6e-d1bd4b87ecad)

**Comment by am-abudu** [comment]
不是这个报错信息，这个和检查更新相关，与该问题无关
