### ISSUE TITLE
部署出错

### ISSUE THREAD

**Issue by Boring1998** [Qexo/Qexo#551]
### Qexo 版本

V3.2.1

### 平台

Vercel 部署 (PostgreSQL/Vercel)

### 问题描述

部署出错

### 截图

![image](https://github.com/user-attachments/assets/1e488759-5842-4031-bed4-bff60adc4ae4)
![image](https://github.com/user-attachments/assets/9be451fb-7d3d-4277-a104-105c0fccb71a)

**Comment by am-abudu** [comment]
#541
