### ISSUE TITLE
更新后数据丢失

### ISSUE THREAD

**Issue by hqycloud** [Qexo/Qexo#555]
### Qexo 版本

3.2.1---3.3.0

### 平台

本地

### 问题描述

更新后数据全部丢失

### 截图

[21/Jul/2024 23:26:09] "GET /api/get_notifications/?csrfmiddlewaretoken=NnaFyPng1HkJAt4L3PC9kIQoQB8Pdt2lNkzSoyPznedVgy40J6JLn2Q66wFQ90SE HTTP/1.1" 200 937
^Croot@hqycloud:/opt/blog/Qexo# python3 manage.py runserver 0.0.0.0:38000 --noreload
使用sqlite数据库
Performing system checks...

           _               _
     /\   | |             | |
    /  \  | |__  _   _  __| |_   _
   / /\ \ | |_ \| | | |/ _| | | | |
  / ____ \| |_) | |_| | (_| | |_| |
 /_/    \_\____/ \____|\____|\____|
当前环境: 本地
System check identified no issues (0 silenced).
July 21, 2024 - 23:30:01
Django version 3.2.25, using settings 'core.settings'
Starting development server at http://0.0.0.0:38000/
Quit the server with CONTROL-C.
[21/Jul/2024 23:30:02] "GET /settings.html HTTP/1.1" 200 117308
[21/Jul/2024 23:30:02] "GET /api/get_notifications/?csrfmiddlewaretoken=lfsWAvVxvkIbenUzEWGnF8bACOA7EcqnlcR9qenQRRBnUsUOkdNZIsbiSJ78AJgG HTTP/1.1" 200 937
[21/Jul/2024 23:30:07] "GET /migrate/ HTTP/1.1" 200 22646
[21/Jul/2024 23:30:08] "GET /api/get_notifications/?csrfmiddlewaretoken=W2pYHp70BttY1iH39D871ft0BepBZQSiWZObx8zjX0maHnHiPUfJ4ztIR9WCVnIB HTTP/1.1" 200 937
[21/Jul/2024 23:30:09] "POST /migrate/ HTTP/1.1" 200 13473
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Requirement already satisfied: Django==3.2.25 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (3.2.25)
Requirement already satisfied: PyMySQL==1.0.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (1.0.2)
Requirement already satisfied: boto3==1.34.44 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (1.34.44)
Requirement already satisfied: requests==2.31.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (2.31.0)
Requirement already satisfied: PyGithub==2.2.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 5)) (2.2.0)
Requirement already satisfied: python-gitlab==4.4.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 6)) (4.4.0)
Requirement already satisfied: html2text==2020.1.16 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 7)) (2020.1.16)
Requirement already satisfied: PyYAML==6.0.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 8)) (6.0.1)
Requirement already satisfied: urllib3==1.26.18 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 9)) (1.26.18)
Requirement already satisfied: Markdown==3.5.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 10)) (3.5.2)
Requirement already satisfied: djongo5==1.3.9 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 11)) (1.3.9)
Requirement already satisfied: django-cors-headers==4.1.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 12)) (4.1.0)
Requirement already satisfied: pymongo==3.13.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 13)) (3.13.0)
Requirement already satisfied: dnspython==2.2.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 14)) (2.2.1)
Requirement already satisfied: sqlparse==0.2.4 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 15)) (0.2.4)
Requirement already satisfied: psycopg2-binary==2.9.9 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 16)) (2.9.9)
Requirement already satisfied: cryptography==42.0.4 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 17)) (42.0.4)
Requirement already satisfied: pyopenssl==24.0.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 18)) (24.0.0)
Requirement already satisfied: oss2==2.18.4 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 19)) (2.18.4)
Requirement already satisfied: beautifulsoup4==4.12.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 20)) (4.12.3)
Requirement already satisfied: upyun==2.5.5 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 21)) (2.5.5)
Requirement already satisfied: asgiref<4,>=3.3.2 in /usr/local/lib/python3.10/dist-packages (from Django==3.2.25->-r requirements.txt (line 1)) (3.8.1)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from Django==3.2.25->-r requirements.txt (line 1)) (2022.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from boto3==1.34.44->-r requirements.txt (line 3)) (0.10.1)
Requirement already satisfied: botocore<1.35.0,>=1.34.44 in /usr/local/lib/python3.10/dist-packages (from boto3==1.34.44->-r requirements.txt (line 3)) (1.34.117)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from boto3==1.34.44->-r requirements.txt (line 3)) (0.10.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.31.0->-r requirements.txt (line 4)) (2020.6.20)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests==2.31.0->-r requirements.txt (line 4)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.31.0->-r requirements.txt (line 4)) (3.3)
Requirement already satisfied: Deprecated in /usr/local/lib/python3.10/dist-packages (from PyGithub==2.2.0->-r requirements.txt (line 5)) (1.2.14)
Requirement already satisfied: pyjwt[crypto]>=2.4.0 in /usr/local/lib/python3.10/dist-packages (from PyGithub==2.2.0->-r requirements.txt (line 5)) (2.8.0)
Requirement already satisfied: pynacl>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from PyGithub==2.2.0->-r requirements.txt (line 5)) (1.5.0)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from PyGithub==2.2.0->-r requirements.txt (line 5)) (4.12.1)
Requirement already satisfied: requests-toolbelt>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from python-gitlab==4.4.0->-r requirements.txt (line 6)) (1.0.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography==42.0.4->-r requirements.txt (line 17)) (1.16.0)
Requirement already satisfied: aliyun-python-sdk-kms>=2.4.1 in /usr/local/lib/python3.10/dist-packages (from oss2==2.18.4->-r requirements.txt (line 19)) (2.16.3)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from oss2==2.18.4->-r requirements.txt (line 19)) (1.16.0)
Requirement already satisfied: pycryptodome>=3.4.7 in /usr/local/lib/python3.10/dist-packages (from oss2==2.18.4->-r requirements.txt (line 19)) (3.20.0)
Requirement already satisfied: aliyun-python-sdk-core>=2.13.12 in /usr/local/lib/python3.10/dist-packages (from oss2==2.18.4->-r requirements.txt (line 19)) (2.15.1)
Requirement already satisfied: crcmod>=1.7 in /usr/local/lib/python3.10/dist-packages (from oss2==2.18.4->-r requirements.txt (line 19)) (1.7)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4==4.12.3->-r requirements.txt (line 20)) (2.5)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.10/dist-packages (from botocore<1.35.0,>=1.34.44->boto3==1.34.44->-r requirements.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12->cryptography==42.0.4->-r requirements.txt (line 17)) (2.22)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.10/dist-packages (from Deprecated->PyGithub==2.2.0->-r requirements.txt (line 5)) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
开始迁移数据库
No changes detected
Operations to perform:
  Apply all migrations: auth, contenttypes, hexoweb, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying hexoweb.0001_initial... OK
  Applying hexoweb.0002_postmodel... OK
  Applying hexoweb.0003_imagemodel_deleteconfig... OK
  Applying sessions.0001_initial... OK
更新完成，五秒后重启线程
保存设置UPDATE_FROM => 3.2.1
[21/Jul/2024 23:30:21] "POST /api/do_update/ HTTP/1.1" 200 52
root@hqycloud:/opt/blog/Qexo# python3 manage.py runserver 0.0.0.0:38000 --noreload
使用sqlite数据库
Performing system checks...

ERROR:root:Provider获取失败, 跳过
           _               _
     /\   | |             | |
    /  \  | |__  _   _  __| |_   _
   / /\ \ | |_ \| | | |/ _| | | | |
  / ____ \| |_) | |_| | (_| | |_| |
 /_/    \_\____/ \____|\____|\____|
当前环境: 本地
System check identified no issues (0 silenced).
July 21, 2024 - 23:30:46
Django version 3.2.25, using settings 'core.settings'
Starting development server at http://0.0.0.0:38000/
Quit the server with CONTROL-C.
[21/Jul/2024 23:30:46] "GET /settings.html HTTP/1.1" 302 0
[21/Jul/2024 23:30:46] "GET /login/?next=/settings.html HTTP/1.1" 302 0
[21/Jul/2024 23:30:47] "GET /init/ HTTP/1.1" 200 16699
[21/Jul/2024 23:30:51] "GET /api/get_notifications/?csrfmiddlewaretoken=GGXa2rx4kR7h4A2O9II5MHBdESWUz7F0GDmnSaZnGo0tKF23PZPHP1BVUNtVvEvj HTTP/1.1" 302 0
[21/Jul/2024 23:30:51] "GET /login/?next=/api/get_notifications/%3Fcsrfmiddlewaretoken%3DGGXa2rx4kR7h4A2O9II5MHBdESWUz7F0GDmnSaZnGo0tKF23PZPHP1BVUNtVvEvj HTTP/1.1" 302 0
[21/Jul/2024 23:30:52] "GET /init/ HTTP/1.1" 200 16699
[21/Jul/2024 23:30:54] "GET / HTTP/1.1" 302 0
[21/Jul/2024 23:30:55] "GET /login/?next=/ HTTP/1.1" 302 0
[21/Jul/2024 23:30:55] "GET /init/ HTTP/1.1" 200 16699
[21/Jul/2024 23:30:55] "GET /api/get_notifications/?csrfmiddlewaretoken=ITuwKa8EohmSWD8LTbPuPZmxXMCbdx5lIQTJATAXKOf4CI80zsW6SjmfdH9c94VE HTTP/1.1" 302 0
[21/Jul/2024 23:30:55] "GET /login/?next=/api/get_notifications/%3Fcsrfmiddlewaretoken%3DITuwKa8EohmSWD8LTbPuPZmxXMCbdx5lIQTJATAXKOf4CI80zsW6SjmfdH9c94VE HTTP/1.1" 302 0
[21/Jul/2024 23:30:55] "GET /init/ HTTP/1.1" 200 16699
root@hqycloud:/opt/blog/Qexo#

**Comment by am-abudu** [comment]
你把Sqlite数据库文件放哪了

**Comment by hqycloud** [comment]
目录下就这些文件
启动命令：python3 manage.py runserver 0.0.0.0:38000 --noreload
```
root@hqycloud:/opt/blog/Qexo# ls
core                 Dockerfile                  hexoweb  Makefile   migrate.sh  Pipfile.lock  README.md         requirements_withoutmysql.txt  templates      vercel.json
docker-compose.yaml  Dockerfile_aio_sqlite_hexo  LICENSE  manage.py  Pipfile     qexo_data.db  requirements.txt  start.sh                       update_tag.sh
```

**Comment by am-abudu** [comment]
请在目录下新建一个 `db` 目录，然后将数据库文件放在该目录下方可防止删除

**Comment by hqycloud** [comment]
建了，但是qexo没调用db/qexo_data.db里的数据库，而是在当前目录下生成了一个把之前的db文件覆盖掉了

**Comment by am-abudu** [comment]
请你认真阅读文档，配置正确的`configs.py`文件
示例: 
```python
import sqlite3
DOMAINS = ["127.0.0.1", "yoursite.com"]
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db/qexo_data.db',
    }
}
```

**Comment by hqycloud** [comment]
感谢，问题已解决
