### ISSUE TITLE
静态资源无法加载

### ISSUE THREAD

**Issue by Rainblooding** [Qexo/Qexo#559]
### Qexo 版本

v2.4.3

### 平台

MongoDB&vercel/Mysql&Ubuntu22

### 问题描述

今天打开突然就这样了, 不论是在vercel平台部署的,还是在自己的服务器上部署都是这样的.
```cmd
>ping npm.onmicrosoft.cn
Ping 请求找不到主机 npm.onmicrosoft.cn。请检查该名称，然后重试。
```

尝试ping 也无法ping通这个地址.
版本其实我不太清楚用的是那个,vercel上面的早就部署了,自己本地今天刚从github上克隆部署的也是这样

### 复现链接

https://qexo-one-gold.vercel.app/

### 截图

![image](https://github.com/user-attachments/assets/54e68a51-1784-44c9-97c8-736a0a8ad71d)

**Comment by am-abudu** [comment]
你有两种方案

1. 修改数据库的 settingmodel->cdn_prev字段

2. 使用´pub/fix´api修复
