### ISSUE TITLE
unpkg静态资源403

### ISSUE THREAD

**Issue by yuzhi-jiang** [Qexo/Qexo#568]
### Qexo 版本

v3.4.1

### 平台

vercel

### 问题描述

{"error":"Invalid URL: /qexo-static@/qexo/argon/argon-dashboard.js"}

不止本地,用过几个公网服务器测试均

### 复现链接

unpkg.com相关链接
https://unpkg.com/qexo-static@/qexo/argon/argon-dashboard.js

### 截图

![image](https://github.com/user-attachments/assets/36ced450-2434-421b-a362-645913e7126e)

**Comment by am-abudu** [comment]
能告诉我这是哪个页面吗

**Comment by yuzhi-jiang** [comment]
主页，登录进去就不行了
![image](https://github.com/user-attachments/assets/9b1cde66-69b3-4c0b-b050-4f1cd4b1e8bf)

**Comment by am-abudu** [comment]
我认为是500/404/403页面错误，你可以现在尝试一下更新之后是不是可以正常抛出500错误了

**Comment by yuzhi-jiang** [comment]
更新是指拉代码  重新构建(这个就是今天访问不了，拉代码重新构建的)？

**Comment by am-abudu** [comment]
可以这样更新

**Comment by yuzhi-jiang** [comment]
我只fork了master，但是我看代码提交是dev，有什么方案让我能更新到吗

**Comment by am-abudu** [comment]
你是在拉起了最新版本后出现这个问题的吗？

**Comment by yuzhi-jiang** [comment]
不是的，一直用着，今天发现cdn失效，以为更新了cdn就拉了新版本代码构建

**Comment by am-abudu** [comment]
你试试直接进入`/settings.html`然后点击一键更新

**Comment by yuzhi-jiang** [comment]
无法进入settings页面，可以进入advanced页面但是不知道我需要设置什么来修复
![image](https://github.com/user-attachments/assets/b9b33734-898b-4a2b-877b-73438a8526c9)

**Comment by am-abudu** [comment]
点击高级设置一旁的扳手
<img width="370" alt="Snipaste_2024-08-28_20-36-41" src="https://github.com/user-attachments/assets/6fe9c959-ae3d-4d87-a255-c5dbbc8f245c">

**Comment by yuzhi-jiang** [comment]
显示成功，但是刷新页面没有生效，清楚缓存也没用

**Comment by am-abudu** [comment]
看来确实是程序出现了不可修复的错误。请问你是从哪个版本更新到最新版本的

**Comment by yuzhi-jiang** [comment]
我是vercel构建，所以是没有提前fork，所以建立的仓库只要一个init commit，不过时间大概是1个月前

**Comment by am-abudu** [comment]
如果还没有解决，请在`advanced.html`尝试在右上角切换语言

**Comment by yuzhi-jiang** [comment]
有相关错误，但是默认为zh_cn, ，刚才/update/ 也改了zh_cn，依然是那个500页面
![image](https://github.com/user-attachments/assets/93b6a31a-b12d-4fbf-9863-882f0d2b60a2)

**Comment by am-abudu** [comment]
这时候你再在右上角切换一下语言就好了

**Comment by yuzhi-jiang** [comment]
切换页面后，友链，说说等可以访问，但是主页，文章，配置相关依然不行
![image](https://github.com/user-attachments/assets/39667ba7-6c08-4a12-ab85-acca81fdd371)

**Comment by am-abudu** [comment]
在右上角第三个按键切换语言，刷新语言配置

**Comment by am-abudu** [comment]
不对，看样子是你的Platform配置有问题，请进入`settings.html`在博客设置内点击保存按钮

**Comment by yuzhi-jiang** [comment]
打错字了，刚才就是进入右上角切换语言的

> 在右上角第三个按键切换语言，刷新语言配置

**Comment by yuzhi-jiang** [comment]
> 不对，看样子是你的Platform配置有问题，请进入`settings.html`在博客设置内点击保存按钮

可是我似乎并没有修改过仓库以为的配置，而且现在无法进入`settings.html`

**Comment by am-abudu** [comment]
这真是太奇怪了，咋会进不去settings.html

**Comment by yuzhi-jiang** [comment]
是的，报500，无法进入settings.html

**Comment by yuzhi-jiang** [comment]
实在没办法的话我尝试清楚数据库从零部署吧

**Comment by am-abudu** [comment]
确实只能这样了，因为我也分析不出来是什么问题

**Comment by yuzhi-jiang** [comment]
我重新部署，初始化后依然报错
![image](https://github.com/user-attachments/assets/6d56f0f4-6d16-4243-9451-7aa69df197b8)

**Comment by yuzhi-jiang** [comment]
可以了，重新部署后等一段时间，可能是vercel的cdn在同步

**Comment by Sasariki** [comment]
我也遇到了这个问题，在talks页面
![image](https://github.com/user-attachments/assets/ec8c31ea-0514-4226-a714-fe1403851094)
https://unpkg.com/qexo-static@/qexo/argon/argon-dashboard.css%20Request%20Method:%20GET
遇到了403

**Comment by am-abudu** [comment]
> 我也遇到了这个问题，在talks页面
> ![image](https://github.com/user-attachments/assets/ec8c31ea-0514-4226-a714-fe1403851094)
> https://unpkg.com/qexo-static@/qexo/argon/argon-dashboard.css%20Request%20Method:%20GET
> 遇到了403

请先尝试更新到最新版本

**Comment by Sasariki** [comment]
![bb6164a6d1969b7c95f64f86c64971e1](https://github.com/user-attachments/assets/7ed03307-0e0c-4660-a2d4-63a38f59dd79)
更新之后打开/talks.html是这样

**Comment by am-abudu** [comment]
> ![bb6164a6d1969b7c95f64f86c64971e1](https://private-user-images.githubusercontent.com/151856485/369605737-7ed03307-0e0c-4660-a2d4-63a38f59dd79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDc2OTYsIm5iZiI6MTcyNjkwNzM5NiwicGF0aCI6Ii8xNTE4NTY0ODUvMzY5NjA1NzM3LTdlZDAzMzA3LTBlMGMtNDY2MC1hMmQ0LTYzYTM4ZjU5ZGQ3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQwODI5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzcyODdjM2I4ZmNkNzBhMmFmMWNhY2QyMDUzY2NmY2M1ODAxYTdlNWJjMjhjYzg4YTE0MmE1YzFjNTRiYTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vSiAaqH6UiOGi9T7QcP2d38Z1WIjlOheKP9Tty9Dvoo) 更新之后打开/talks.html是这样

你的数据库连接出现了问题，请参考文档自行排查

**Comment by INYXIN** [comment]
> 主页，登录进去就不行了 ![image](https://github.com/user-attachments/assets/9b1cde66-69b3-4c0b-b050-4f1cd4b1e8bf)

![Image](https://github.com/user-attachments/assets/34615074-053e-475d-9341-c07bab8fc1ba)

可以不用cdn吗
