### ISSUE TITLE
github 图床删除远程文件失败

### ISSUE THREAD

**Issue by felixesintot** [Qexo/Qexo#572]
### Qexo 版本

v3.4.1

### 平台

MongoDB & Vercel

### 问题描述

如题，只成功了一次，后面都要我手动 commit，上传是正常的

### 复现链接

edit.felixesintot.top

### 截图

![image](https://github.com/user-attachments/assets/c491063f-44c6-4f02-a2dc-53c3d254be65)

**Comment by am-abudu** [comment]
只有新上传的图片支持远程删除

**Comment by felixesintot** [comment]
那要删除的不大部分都是不用的旧图……
这在不自己改仓库的情况下应该是可以实现的把，要不未来版本支持下？

**Comment by am-abudu** [comment]
由于先前上传的图片没有记录相关信息故无法支持，请自行修改相应仓库

**Comment by felixesintot** [comment]
没记录那确实没办法
所以用 github+CDN 的还是推荐用其他软件
