### ISSUE TITLE
hugo发表文章提交位置错误

### ISSUE THREAD

**Issue by zhjurz** [Qexo/Qexo#575]
### Qexo 版本

v3.4.1

### 平台

PostgreSQL&Vercel

### 问题描述

![{5AD9CD97-A40B-47DE-B934-1442DAAF10CE}](https://github.com/user-attachments/assets/42acd30f-e757-40af-9553-24fed04c94e0)
在今年6月份左右，hugo更新了页面的组织形式，现在使用的页面包格式为：
![{7FB3F298-2796-43BF-A7A5-FC29D34496C8}](https://github.com/user-attachments/assets/344cb6a4-669f-4f2f-8673-740edb7e62de)

而目前的qexo上传后的为
![{B263280A-9D81-4EF6-95EF-A77FFD88B67B}](https://github.com/user-attachments/assets/fc39f079-c6a7-41ef-b805-a3a728454eab)
望改进！

### 复现链接

本地环境

### 截图

![{5AD9CD97-A40B-47DE-B934-1442DAAF10CE}](https://github.com/user-attachments/assets/42acd30f-e757-40af-9553-24fed04c94e0)

**Comment by am-abudu** [comment]
之后会进行修改，你也可以自行向dev分支 /hexoweb/libs/platforms/configs 提交pr

**Comment by am-abudu** [comment]
我检查了Hugo文档，发现现在的创建方式也是可行的。如果你需要带目录，请自行在文件名中使用`/`分隔
<img width="1115" alt="Snipaste_2024-09-28_10-40-34" src="https://github.com/user-attachments/assets/3c9b0e37-4140-472e-beac-ae11b9043c28">

**Comment by zhjurz** [comment]
好的！我看了确实可行。非常感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月28日(周六) 上午10:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Qexo/Qexo] hugo发表文章提交位置错误 (Issue #575)




 
我检查了Hugo文档，发现现在的创建方式也是可行的。如果你需要带目录，请自行在文件名中使用/分隔
 Snipaste_2024-09-28_10-40-34.png (view on web)
