### ISSUE TITLE
github图床上传报错

### ISSUE THREAD

**Issue by miaoyanginfo** [Qexo/Qexo#576]
### Qexo 版本

v3.4.1

### 平台

vercel

### 问题描述

配置完github图床后上传图片报错如下：
GithubException(422 {"message": "Invalid request.\n\n\"sha\" wasn't supplied.", "documentation_url": "https://docs.github.com/rest/repos/contents#create-or-update-file-contents", "status": "422"})

### 截图

![erro](https://github.com/user-attachments/assets/4e0184a9-22f1-4cbc-b17d-064e3bab0b7b)

**Comment by miaoyanginfo** [comment]
查了一圈大部分422报错是有重名文件，但我检查了一遍确认仓库里没有重名文件。

**Comment by am-abudu** [comment]
周末测试

**Comment by am-abudu** [comment]
周末测试

**Comment by am-abudu** [comment]
经过我的测试是正常的，请检查你的配置谬误
<img width="1115" alt="Snipaste_2024-09-28_10-47-06" src="https://github.com/user-attachments/assets/d56af63f-bc2b-4440-8996-0efaf8ec1aea">

**Comment by miaoyanginfo** [comment]
![image](https://github.com/user-attachments/assets/1df67de8-cf4a-4c0f-88a4-0bb38003b250)
配置应该没问题，picgo和piclist都是用的这个配置

**Comment by miaoyanginfo** [comment]
![image](https://github.com/user-attachments/assets/33a69d15-1763-491b-899d-06d852a732da)
这是piclist的配置

**Comment by miaoyanginfo** [comment]
又读了一遍文档，是保存路径输入有误，更改后已正常，感谢。
