### ISSUE TITLE
lsky图床上传图片报错

### ISSUE THREAD

**Issue by miniLQ** [Qexo/Qexo#588]
### Qexo 版本

v3.4.1

### 平台

supabase

### 问题描述

使用如下的配置lsky图床无法上传图片
配置如下：
![image](https://github.com/user-attachments/assets/b169c495-7b48-4a32-a875-33341878058f)

### 截图

配置如下：
![image](https://github.com/user-attachments/assets/b169c495-7b48-4a32-a875-33341878058f)
报错如下：
![image](https://github.com/user-attachments/assets/fda50c2f-4c1b-435b-80bd-536148d4e3aa)
![image](https://github.com/user-attachments/assets/bd570132-8dbd-458f-8de3-c88a21e7235f)

但是我用curl以及写了一个python程序去调接口都是可以成功的
![image](https://github.com/user-attachments/assets/b840fbba-2470-4a0f-894a-1c23c7e5984e)
![image](https://github.com/user-attachments/assets/ef64ce17-a989-48d7-9246-5b1008e27d5e)

**Comment by am-abudu** [comment]
这是支持的。你可以在服务端看看报错信息，是不是把Vercel屏蔽了

**Comment by miniLQ** [comment]
> 这是支持的。你可以在服务端看看报错信息，是不是把Vercel屏蔽了

lsky服务那边的日志？我看了lsky没有任何的日志吐出来
